// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: audit.sql

package gensql

import (
	"context"
)

const auditCreate = `-- name: AuditCreate :exec
INSERT INTO audits (
  actor,
  description,
  object_type,
  object_id
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type AuditCreateParams struct {
	Actor       string
	Description string
	ObjectType  string
	ObjectID    string
}

func (q *Queries) AuditCreate(ctx context.Context, arg AuditCreateParams) error {
	_, err := q.db.Exec(ctx, auditCreate,
		arg.Actor,
		arg.Description,
		arg.ObjectType,
		arg.ObjectID,
	)
	return err
}

const auditForEnvironment = `-- name: AuditForEnvironment :many
SELECT id, actor, description, object_type, object_id, created_at
FROM audits
WHERE CASE WHEN $1::text != '' THEN
  object_id = concat($2::text, ':', $1::text)
ELSE
  starts_with(object_id, $2::text)
END
ORDER BY created_at DESC
LIMIT $3
`

type AuditForEnvironmentParams struct {
	Featurename   string
	EnvironmentID string
	PageSize      int32
}

func (q *Queries) AuditForEnvironment(ctx context.Context, arg AuditForEnvironmentParams) ([]Audit, error) {
	rows, err := q.db.Query(ctx, auditForEnvironment, arg.Featurename, arg.EnvironmentID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Audit{}
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Description,
			&i.ObjectType,
			&i.ObjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
