// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: deploy_instructions.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
)

const deployInstructionsByID = `-- name: DeployInstructionsByID :one
SELECT id, environment_id, feature_name, feature_version, status, hash, created, last_modified, values FROM deploy_instructions WHERE id = $1
`

func (q *Queries) DeployInstructionsByID(ctx context.Context, id uuid.UUID) (DeployInstruction, error) {
	row := q.db.QueryRow(ctx, deployInstructionsByID, id)
	var i DeployInstruction
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.FeatureName,
		&i.FeatureVersion,
		&i.Status,
		&i.Hash,
		&i.Created,
		&i.LastModified,
		&i.Values,
	)
	return i, err
}

const deployInstructionsCreate = `-- name: DeployInstructionsCreate :one
INSERT INTO deploy_instructions (
  environment_id,
  feature_name,
  feature_version,
  hash,
  values
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id
`

type DeployInstructionsCreateParams struct {
	EnvironmentID  uuid.UUID
	FeatureName    string
	FeatureVersion string
	Hash           string
	Values         []byte
}

func (q *Queries) DeployInstructionsCreate(ctx context.Context, arg DeployInstructionsCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deployInstructionsCreate,
		arg.EnvironmentID,
		arg.FeatureName,
		arg.FeatureVersion,
		arg.Hash,
		arg.Values,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deployInstructionsForFeature = `-- name: DeployInstructionsForFeature :many
SELECT id, environment_id, feature_name, feature_version, status, hash, created, last_modified, values FROM deploy_instructions
WHERE feature_name = $1
AND environment_id = $2
ORDER BY created DESC
LIMIT 10 OFFSET $3
`

type DeployInstructionsForFeatureParams struct {
	FeatureName   string
	EnvironmentID uuid.UUID
	Offset        int32
}

func (q *Queries) DeployInstructionsForFeature(ctx context.Context, arg DeployInstructionsForFeatureParams) ([]DeployInstruction, error) {
	rows, err := q.db.Query(ctx, deployInstructionsForFeature, arg.FeatureName, arg.EnvironmentID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployInstruction{}
	for rows.Next() {
		var i DeployInstruction
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.FeatureName,
			&i.FeatureVersion,
			&i.Status,
			&i.Hash,
			&i.Created,
			&i.LastModified,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployInstructionsLatestForEnvironment = `-- name: DeployInstructionsLatestForEnvironment :many
SELECT id, environment_id, feature_name, feature_version, status, hash, created, last_modified, values FROM deploy_instructions
WHERE id IN (
  SELECT DISTINCT ON (feature_name) id
  FROM deploy_instructions di
  WHERE di.environment_id = $1
  ORDER BY feature_name, created DESC
)
`

func (q *Queries) DeployInstructionsLatestForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]DeployInstruction, error) {
	rows, err := q.db.Query(ctx, deployInstructionsLatestForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployInstruction{}
	for rows.Next() {
		var i DeployInstruction
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.FeatureName,
			&i.FeatureVersion,
			&i.Status,
			&i.Hash,
			&i.Created,
			&i.LastModified,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deployInstructionsLatestForFeature = `-- name: DeployInstructionsLatestForFeature :one
SELECT id, environment_id, feature_name, feature_version, status, hash, created, last_modified, values FROM deploy_instructions
WHERE feature_name = $1
AND environment_id = $2
ORDER BY created DESC
LIMIT 1
`

type DeployInstructionsLatestForFeatureParams struct {
	FeatureName   string
	EnvironmentID uuid.UUID
}

func (q *Queries) DeployInstructionsLatestForFeature(ctx context.Context, arg DeployInstructionsLatestForFeatureParams) (DeployInstruction, error) {
	row := q.db.QueryRow(ctx, deployInstructionsLatestForFeature, arg.FeatureName, arg.EnvironmentID)
	var i DeployInstruction
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.FeatureName,
		&i.FeatureVersion,
		&i.Status,
		&i.Hash,
		&i.Created,
		&i.LastModified,
		&i.Values,
	)
	return i, err
}

const deployInstructionsPrevious = `-- name: DeployInstructionsPrevious :one
WITH current AS (
  SELECT di.id, di.environment_id, di.feature_name, di.feature_version, di.status, di.hash, di.created, di.last_modified, di.values
  FROM deploy_instructions di
  WHERE di.id = $1
)
SELECT id, environment_id, feature_name, feature_version, status, hash, created, last_modified, values FROM deploy_instructions
WHERE feature_name = (SELECT feature_name FROM current)
AND environment_id = (SELECT environment_id FROM current)
AND created < (SELECT created FROM current)
ORDER BY created DESC
LIMIT 1
`

func (q *Queries) DeployInstructionsPrevious(ctx context.Context, id uuid.UUID) (DeployInstruction, error) {
	row := q.db.QueryRow(ctx, deployInstructionsPrevious, id)
	var i DeployInstruction
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.FeatureName,
		&i.FeatureVersion,
		&i.Status,
		&i.Hash,
		&i.Created,
		&i.LastModified,
		&i.Values,
	)
	return i, err
}

const deployInstructionsUpdateStatus = `-- name: DeployInstructionsUpdateStatus :exec
UPDATE deploy_instructions
SET status = $1
WHERE id = $2
`

type DeployInstructionsUpdateStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) DeployInstructionsUpdateStatus(ctx context.Context, arg DeployInstructionsUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, deployInstructionsUpdateStatus, arg.Status, arg.ID)
	return err
}
