// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: errorview.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
)

const errorView = `-- name: ErrorView :many
SELECT 'featureError' as "type", environment_id, environment.tenant_id, feature
FROM status
JOIN environments environment ON environment.id = status.environment_id
WHERE status = 'failed'
AND (
  status.environment_id = $1
  OR environment.tenant_id = $2
)

UNION

SELECT 'naisdError', environment.id, environment.tenant_id, NULL
FROM health_statuses hs
RIGHT JOIN environments environment ON environment.id = hs.environment_id
WHERE (
  hs.reported_at IS NULL
  OR hs.reported_at < NOW() - INTERVAL '10 minutes'
)
AND (
  status.environment_id = $1
  OR environment.tenant_id = $2
)
`

type ErrorViewParams struct {
	EnvironmentID uuid.UUID
	TenantID      uuid.UUID
}

type ErrorViewRow struct {
	Type          interface{}
	EnvironmentID uuid.UUID
	TenantID      uuid.UUID
	Feature       string
}

func (q *Queries) ErrorView(ctx context.Context, arg ErrorViewParams) ([]ErrorViewRow, error) {
	rows, err := q.db.Query(ctx, errorView, arg.EnvironmentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorViewRow{}
	for rows.Next() {
		var i ErrorViewRow
		if err := rows.Scan(
			&i.Type,
			&i.EnvironmentID,
			&i.TenantID,
			&i.Feature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
