// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: features.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const featureByName = `-- name: FeatureByName :one
SELECT
  fd.name,
  fd.version,
  fd.chart,
  fd.description,
  fd.source,
  fd.kinds::text[] AS kinds,
  fd.dependencies,
  fd.values,
  fd.default_values,
  fd.timeout,
  features.created,
  features.last_modified
FROM features
JOIN feature_data fd ON features.name = fd.name AND features.version = fd.version
WHERE fd.name = $1
`

type FeatureByNameRow struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	Created       pgtype.Timestamptz
	LastModified  pgtype.Timestamptz
}

func (q *Queries) FeatureByName(ctx context.Context, name string) (FeatureByNameRow, error) {
	row := q.db.QueryRow(ctx, featureByName, name)
	var i FeatureByNameRow
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Chart,
		&i.Description,
		&i.Source,
		&i.Kinds,
		&i.Dependencies,
		&i.Values,
		&i.DefaultValues,
		&i.Timeout,
		&i.Created,
		&i.LastModified,
	)
	return i, err
}

const featureGetForEnv = `-- name: FeatureGetForEnv :many
SELECT fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details, fd.moved, features.created, features.last_modified
FROM features
JOIN feature_data fd ON features.name = fd.name AND features.version = fd.version
WHERE $1::text = ANY(kinds::text[])
ORDER BY features.name
`

type FeatureGetForEnvRow struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
	Moved         []byte
	Created       pgtype.Timestamptz
	LastModified  pgtype.Timestamptz
}

func (q *Queries) FeatureGetForEnv(ctx context.Context, environmentKind string) ([]FeatureGetForEnvRow, error) {
	rows, err := q.db.Query(ctx, featureGetForEnv, environmentKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureGetForEnvRow{}
	for rows.Next() {
		var i FeatureGetForEnvRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.DefaultValues,
			&i.Timeout,
			&i.TplDetails,
			&i.Moved,
			&i.Created,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const featureVersionUpdate = `-- name: FeatureVersionUpdate :exec
INSERT INTO features
  (
    name,
    version
  )
VALUES
  (
    $1,
    $2
  )
ON CONFLICT (name) DO
  UPDATE SET version = EXCLUDED.version
`

type FeatureVersionUpdateParams struct {
	Name    string
	Version string
}

func (q *Queries) FeatureVersionUpdate(ctx context.Context, arg FeatureVersionUpdateParams) error {
	_, err := q.db.Exec(ctx, featureVersionUpdate, arg.Name, arg.Version)
	return err
}

const features = `-- name: Features :many
WITH combined AS (
  SELECT null AS id, name, version, created, last_modified
  FROM features

  UNION
  (
    SELECT DISTINCT ON(feature_name)
      id,
      feature_name AS name,
      version,
      make_timestamptz(1969, 4, 20, 0, 0, 0) AS created,
      make_timestamptz(1969, 4, 20, 0, 0, 0) AS last_modified
    FROM rollouts
    WHERE status = 'pending'
    ORDER BY feature_name, "version" DESC
  )
), filtered AS (
  SELECT DISTINCT ON (name) name AS name, version, created, last_modified
  FROM combined
  ORDER BY
    -- order by id to ensure rollout has precedence over feature
    name, id
)
SELECT
  fd.name,
  fd.version,
  fd.chart,
  fd.description,
  fd.source,
  fd.kinds::text[] AS kinds,
  fd.dependencies,
  fd.values,
  fd.default_values,
  fd.timeout,
  combined.created,
  combined.last_modified
FROM combined
JOIN feature_data fd ON combined.name = fd.name AND combined.version = fd.version
ORDER BY combined.name
`

type FeaturesRow struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	Created       pgtype.Timestamptz
	LastModified  pgtype.Timestamptz
}

func (q *Queries) Features(ctx context.Context) ([]FeaturesRow, error) {
	rows, err := q.db.Query(ctx, features)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturesRow{}
	for rows.Next() {
		var i FeaturesRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.DefaultValues,
			&i.Timeout,
			&i.Created,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const featuresForKind = `-- name: FeaturesForKind :many
SELECT
  fd.name,
  fd.version,
  fd.chart,
  fd.description,
  fd.source,
  fd.kinds::text[] AS kinds,
  fd.dependencies,
  fd.values,
  fd.default_values,
  fd.timeout,
  features.created,
  features.last_modified
FROM features
JOIN feature_data fd ON features.name = fd.name AND features.version = fd.version
WHERE $1::text = ANY(kinds::text[])
ORDER BY features.name
`

type FeaturesForKindRow struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	Created       pgtype.Timestamptz
	LastModified  pgtype.Timestamptz
}

func (q *Queries) FeaturesForKind(ctx context.Context, environmentKind string) ([]FeaturesForKindRow, error) {
	rows, err := q.db.Query(ctx, featuresForKind, environmentKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturesForKindRow{}
	for rows.Next() {
		var i FeaturesForKindRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.DefaultValues,
			&i.Timeout,
			&i.Created,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
