// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: feature_data.sql

package gensql

import (
	"context"

	"github.com/jackc/pgtype"
)

const featureDataCreate = `-- name: FeatureDataCreate :one
INSERT INTO feature_data (
    name, 
    version, 
    chart, 
    description, 
    source, 
    kinds, 
    dependencies, 
    values, 
    default_values
) VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7, 
    $8, 
    $9) RETURNING name, version, chart, description, source, kinds, dependencies, values, default_values
`

type FeatureDataCreateParams struct {
	FeatureName   string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []EnvironmentKind
	Dependencies  pgtype.JSONB
	Values        pgtype.JSONB
	DefaultValues pgtype.JSONB
}

func (q *Queries) FeatureDataCreate(ctx context.Context, arg FeatureDataCreateParams) (FeatureDatum, error) {
	row := q.db.QueryRow(ctx, featureDataCreate,
		arg.FeatureName,
		arg.Version,
		arg.Chart,
		arg.Description,
		arg.Source,
		arg.Kinds,
		arg.Dependencies,
		arg.Values,
		arg.DefaultValues,
	)
	var i FeatureDatum
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Chart,
		&i.Description,
		&i.Source,
		&i.Kinds,
		&i.Dependencies,
		&i.Values,
		&i.DefaultValues,
	)
	return i, err
}
