// Code generated by sqlc. DO NOT EDIT.
// source: feature_states.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
)

const featureStateGet = `-- name: FeatureStateGet :one
SELECT environment_id, feature, enabled, created, last_modified
FROM feature_states
WHERE feature = $1 AND environment_id = $2
`

type FeatureStateGetParams struct {
	Feature       string
	EnvironmentID uuid.UUID
}

func (q *Queries) FeatureStateGet(ctx context.Context, arg FeatureStateGetParams) (FeatureState, error) {
	row := q.db.QueryRowContext(ctx, featureStateGet, arg.Feature, arg.EnvironmentID)
	var i FeatureState
	err := row.Scan(
		&i.EnvironmentID,
		&i.Feature,
		&i.Enabled,
		&i.Created,
		&i.LastModified,
	)
	return i, err
}

const featureStateUpdateOrCreate = `-- name: FeatureStateUpdateOrCreate :one
INSERT INTO feature_states
(environment_id, feature, enabled)
VALUES
    ($1, $2, $3)
ON CONFLICT (environment_id, feature) DO UPDATE
    SET
        enabled = EXCLUDED.enabled
RETURNING environment_id, feature, enabled, created, last_modified
`

type FeatureStateUpdateOrCreateParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Enabled       bool
}

func (q *Queries) FeatureStateUpdateOrCreate(ctx context.Context, arg FeatureStateUpdateOrCreateParams) (FeatureState, error) {
	row := q.db.QueryRowContext(ctx, featureStateUpdateOrCreate, arg.EnvironmentID, arg.Feature, arg.Enabled)
	var i FeatureState
	err := row.Scan(
		&i.EnvironmentID,
		&i.Feature,
		&i.Enabled,
		&i.Created,
		&i.LastModified,
	)
	return i, err
}

const featureStatesGet = `-- name: FeatureStatesGet :many
SELECT environment_id, feature, enabled, created, last_modified
FROM feature_states
WHERE environment_id = $1
`

func (q *Queries) FeatureStatesGet(ctx context.Context, environmentID uuid.UUID) ([]FeatureState, error) {
	rows, err := q.db.QueryContext(ctx, featureStatesGet, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureState{}
	for rows.Next() {
		var i FeatureState
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Feature,
			&i.Enabled,
			&i.Created,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
