// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: feature_data.sql

package gensql

import (
	"context"

	"github.com/jackc/pgtype"
)

const featureDataCreate = `-- name: FeatureDataCreate :exec
INSERT INTO feature_data (
    name,
    version,
    chart,
    description,
    source,
    kinds,
    dependencies,
    values,
    default_values,
    timeout
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    ($6::text[])::environment_kind[],
    $7,
    $8,
    $9,
    $10
)
`

type FeatureDataCreateParams struct {
	FeatureName   string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  pgtype.JSONB
	Values        pgtype.JSONB
	DefaultValues pgtype.JSONB
	Timeout       int64
}

func (q *Queries) FeatureDataCreate(ctx context.Context, arg FeatureDataCreateParams) error {
	_, err := q.db.Exec(ctx, featureDataCreate,
		arg.FeatureName,
		arg.Version,
		arg.Chart,
		arg.Description,
		arg.Source,
		arg.Kinds,
		arg.Dependencies,
		arg.Values,
		arg.DefaultValues,
		arg.Timeout,
	)
	return err
}
