// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: features_by_env.sql

package gensql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const featuresForEnvironment = `-- name: FeaturesForEnvironment :many
WITH "all" AS (
  SELECT id, name, chart, environment_kinds, version, created, last_modified, 0 as rollout
  FROM features

  UNION ALL

  SELECT id, feature_name, chart, environment_kinds, version, created, null, 1 as rollout
  FROM rollouts
), "env" AS (
  SELECT kind, ci
  FROM environments
  WHERE environments.id = $1
), "result" AS (
  SELECT id, name, chart, environment_kinds, version, created, last_modified, rollout, kind, ci
  FROM "all"
  JOIN env ON env.kind = ANY("all".environment_kinds)
), "filtered" AS (
  SELECT id, name, chart, environment_kinds, version, created, last_modified, rollout, kind, ci, RANK() OVER (
      PARTITION BY "name"
      ORDER BY
      CASE WHEN ci THEN -rollout ELSE rollout END ASC,
        "name" ASC
    )
  FROM "result"
)

SELECT id, name, chart, version, created, last_modified, rollout::bool
FROM filtered
WHERE rank = 1
`

type FeaturesForEnvironmentRow struct {
	ID           uuid.UUID
	Name         string
	Chart        string
	Version      string
	Created      time.Time
	LastModified time.Time
	Rollout      bool
}

func (q *Queries) FeaturesForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]FeaturesForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, featuresForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturesForEnvironmentRow{}
	for rows.Next() {
		var i FeaturesForEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Chart,
			&i.Version,
			&i.Created,
			&i.LastModified,
			&i.Rollout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
