// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: kubernetes_node_status.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const kubernetesNodeCreateOrUpdate = `-- name: KubernetesNodeCreateOrUpdate :exec
INSERT INTO kubernetes_node_statuses
	(
        environment_id,
        name,
        kernel_version,
        os_image,
        container_runtime_version,
        kubelet_version,
        kube_proxy_version,
        operating_system,
        architecture,
        conditions,
        allocatable,
        capacity,
        internal_ip
    )
VALUES
	(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    )
ON CONFLICT (environment_id, name) DO UPDATE
	SET
    kernel_version = EXCLUDED.kernel_version,
    os_image = EXCLUDED.os_image,
    container_runtime_version = EXCLUDED.container_runtime_version,
    kubelet_version = EXCLUDED.kubelet_version,
    kube_proxy_version = EXCLUDED.kube_proxy_version,
    operating_system = EXCLUDED.operating_system,
    architecture = EXCLUDED.architecture,
    conditions = EXCLUDED.conditions,
    allocatable = EXCLUDED.allocatable,
    capacity = EXCLUDED.capacity,
    internal_ip = EXCLUDED.internal_ip
`

type KubernetesNodeCreateOrUpdateParams struct {
	EnvironmentID           uuid.UUID
	Name                    string
	KernelVersion           string
	OsImage                 string
	ContainerRuntimeVersion string
	KubeletVersion          string
	KubeProxyVersion        string
	OperatingSystem         string
	Architecture            string
	Conditions              pgtype.JSONB
	Allocatable             pgtype.JSONB
	Capacity                pgtype.JSONB
	InternalIp              string
}

func (q *Queries) KubernetesNodeCreateOrUpdate(ctx context.Context, arg KubernetesNodeCreateOrUpdateParams) error {
	_, err := q.db.Exec(ctx, kubernetesNodeCreateOrUpdate,
		arg.EnvironmentID,
		arg.Name,
		arg.KernelVersion,
		arg.OsImage,
		arg.ContainerRuntimeVersion,
		arg.KubeletVersion,
		arg.KubeProxyVersion,
		arg.OperatingSystem,
		arg.Architecture,
		arg.Conditions,
		arg.Allocatable,
		arg.Capacity,
		arg.InternalIp,
	)
	return err
}

const kubernetesNodeDeleteObsolete = `-- name: KubernetesNodeDeleteObsolete :exec
DELETE FROM kubernetes_node_statuses WHERE environment_id = $1 AND last_modified < NOW() - INTERVAL '1 minute'
`

func (q *Queries) KubernetesNodeDeleteObsolete(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, kubernetesNodeDeleteObsolete, environmentID)
	return err
}

const kubernetesNodeStatuses = `-- name: KubernetesNodeStatuses :many
SELECT environment_id, name, kernel_version, os_image, container_runtime_version, kubelet_version, kube_proxy_version, operating_system, architecture, conditions, allocatable, capacity, created, last_modified, internal_ip FROM kubernetes_node_statuses
WHERE environment_id = $1
`

func (q *Queries) KubernetesNodeStatuses(ctx context.Context, environmentID uuid.UUID) ([]KubernetesNodeStatus, error) {
	rows, err := q.db.Query(ctx, kubernetesNodeStatuses, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KubernetesNodeStatus{}
	for rows.Next() {
		var i KubernetesNodeStatus
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Name,
			&i.KernelVersion,
			&i.OsImage,
			&i.ContainerRuntimeVersion,
			&i.KubeletVersion,
			&i.KubeProxyVersion,
			&i.OperatingSystem,
			&i.Architecture,
			&i.Conditions,
			&i.Allocatable,
			&i.Capacity,
			&i.Created,
			&i.LastModified,
			&i.InternalIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
