// Code generated by sqlc. DO NOT EDIT.

package gensql

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Configuration struct {
	ID            uuid.UUID
	EnvironmentID uuid.NullUUID
	Feature       string
	Key           string
	Value         json.RawMessage
	Description   sql.NullString
	Secret        bool
	Deleted       sql.NullBool
	Created       time.Time
}

type Environment struct {
	ID           uuid.UUID
	PartnerID    uuid.UUID
	Name         string
	Description  sql.NullString
	Created      time.Time
	LastModified time.Time
}

type Partner struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Created      time.Time
	LastModified time.Time
}

type Status struct {
	EnvironmentID uuid.UUID
	Feature       string
	Version       string
	Status        string
	Created       time.Time
	LastModified  time.Time
}
