// Code generated by sqlc. DO NOT EDIT.

package gensql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfigCreate(ctx context.Context, arg ConfigCreateParams) (Configuration, error)
	ConfigForEnv(ctx context.Context, arg ConfigForEnvParams) ([]ConfigForEnvRow, error)
	ConfigGet(ctx context.Context, feature string) (Configuration, error)
	EnvironmentCreate(ctx context.Context, arg EnvironmentCreateParams) (Environment, error)
	EnvironmentGet(ctx context.Context, id uuid.UUID) (Environment, error)
	EnvironmentIDByNames(ctx context.Context, arg EnvironmentIDByNamesParams) (uuid.UUID, error)
	EnvironmentsGet(ctx context.Context, partnerID uuid.UUID) ([]Environment, error)
	PartnerCreate(ctx context.Context, arg PartnerCreateParams) (Partner, error)
	PartnerGet(ctx context.Context, id uuid.UUID) (Partner, error)
	PartnersGet(ctx context.Context) ([]Partner, error)
	ReconcileData(ctx context.Context) ([]ReconcileDataRow, error)
	StatusCreateOrUpdate(ctx context.Context, arg StatusCreateOrUpdateParams) error
	StatusForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Status, error)
}

var _ Querier = (*Queries)(nil)
