// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: rollout.sql

package gensql

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const rolloutByName = `-- name: RolloutByName :one
SELECT
  rollouts.id,
  fd.name,
  fd.version,
  fd.chart,
  fd.description,
  fd.source,
  fd.kinds::text[] AS kinds,
  fd.dependencies,
  fd.values,
  fd.timeout,
  fd.default_values,
  rollouts.created
FROM rollouts
JOIN feature_data fd ON rollouts.feature_name = fd.name AND rollouts.version = fd.version
WHERE fd.name = $1
`

type RolloutByNameRow struct {
	ID            uuid.UUID
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  pgtype.JSONB
	Values        pgtype.JSONB
	Timeout       sql.NullInt64
	DefaultValues pgtype.JSONB
	Created       time.Time
}

func (q *Queries) RolloutByName(ctx context.Context, name string) (RolloutByNameRow, error) {
	row := q.db.QueryRow(ctx, rolloutByName, name)
	var i RolloutByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Chart,
		&i.Description,
		&i.Source,
		&i.Kinds,
		&i.Dependencies,
		&i.Values,
		&i.Timeout,
		&i.DefaultValues,
		&i.Created,
	)
	return i, err
}

const rolloutComplete = `-- name: RolloutComplete :exec
UPDATE rollouts SET completed = NOW() WHERE feature_name = $1 and completed IS NULL
`

func (q *Queries) RolloutComplete(ctx context.Context, featureName string) error {
	_, err := q.db.Exec(ctx, rolloutComplete, featureName)
	return err
}

const rolloutCreate = `-- name: RolloutCreate :one
INSERT INTO rollouts (feature_name, version) VALUES ($1, $2) RETURNING id, feature_name, version, status, created, completed
`

type RolloutCreateParams struct {
	FeatureName string
	Version     string
}

func (q *Queries) RolloutCreate(ctx context.Context, arg RolloutCreateParams) (Rollout, error) {
	row := q.db.QueryRow(ctx, rolloutCreate, arg.FeatureName, arg.Version)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Status,
		&i.Created,
		&i.Completed,
	)
	return i, err
}

const rolloutDelete = `-- name: RolloutDelete :exec
DELETE FROM rollouts WHERE feature_name = $1
`

func (q *Queries) RolloutDelete(ctx context.Context, featureName string) error {
	_, err := q.db.Exec(ctx, rolloutDelete, featureName)
	return err
}

const rolloutEventCreate = `-- name: RolloutEventCreate :exec
INSERT INTO rollout_events (rollout_id, failure, message) VALUES ($1, $2::boolean, $3::string) RETURNING id, rollout_id, failure, message, created
`

type RolloutEventCreateParams struct {
	RolloutID uuid.UUID
	Failure   bool
	Message   string
}

func (q *Queries) RolloutEventCreate(ctx context.Context, arg RolloutEventCreateParams) error {
	_, err := q.db.Exec(ctx, rolloutEventCreate, arg.RolloutID, arg.Failure, arg.Message)
	return err
}

const rolloutStatus = `-- name: RolloutStatus :one
SELECT status FROM rollouts WHERE feature_name = $1 and completed IS NULL
`

func (q *Queries) RolloutStatus(ctx context.Context, featureName string) (string, error) {
	row := q.db.QueryRow(ctx, rolloutStatus, featureName)
	var status string
	err := row.Scan(&status)
	return status, err
}

const rolloutUpdateStatus = `-- name: RolloutUpdateStatus :exec
UPDATE rollouts SET status = $1 WHERE feature_name = $2 and completed IS NOT NULL
`

type RolloutUpdateStatusParams struct {
	Status      string
	FeatureName string
}

func (q *Queries) RolloutUpdateStatus(ctx context.Context, arg RolloutUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, rolloutUpdateStatus, arg.Status, arg.FeatureName)
	return err
}

const rolloutsForKind = `-- name: RolloutsForKind :many
SELECT
  rollouts.id,
  fd.name,
  fd.version,
  fd.chart,
  fd.description,
  fd.source,
  fd.kinds::text[] AS kinds,
  fd.dependencies,
  fd.values,
  fd.timeout,
  fd.default_values,
  rollouts.created
FROM rollouts
JOIN feature_data fd ON rollouts.feature_name = fd.name AND rollouts.version = fd.version
WHERE $1::text = ANY(environment_kinds)
ORDER BY rollouts.features_name
`

type RolloutsForKindRow struct {
	ID            uuid.UUID
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  pgtype.JSONB
	Values        pgtype.JSONB
	Timeout       sql.NullInt64
	DefaultValues pgtype.JSONB
	Created       time.Time
}

func (q *Queries) RolloutsForKind(ctx context.Context, environmentKind string) ([]RolloutsForKindRow, error) {
	rows, err := q.db.Query(ctx, rolloutsForKind, environmentKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolloutsForKindRow{}
	for rows.Next() {
		var i RolloutsForKindRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.Timeout,
			&i.DefaultValues,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
