// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: tenant.sql

package gensql

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const tenantCI = `-- name: TenantCI :one
SELECT id, name, description, created, last_modified, ci FROM tenants WHERE ci = true
`

func (q *Queries) TenantCI(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, tenantCI)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const tenantCreate = `-- name: TenantCreate :one
INSERT INTO tenants (name, description) VALUES ($1, $2) RETURNING id, name, description, created, last_modified, ci
`

type TenantCreateParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) TenantCreate(ctx context.Context, arg TenantCreateParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, tenantCreate, arg.Name, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const tenantEnvironments = `-- name: TenantEnvironments :many
SELECT e.id, e.tenant_id, e.name, e.kind, e.description, e.created, e.last_modified, e.ci, p.name AS tenant_name
FROM environments e
JOIN tenants p ON e.tenant_id = p.id
ORDER BY p.name, e.name
`

type TenantEnvironmentsRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	Kind         EnvironmentKind
	Description  sql.NullString
	Created      time.Time
	LastModified time.Time
	Ci           bool
	TenantName   string
}

func (q *Queries) TenantEnvironments(ctx context.Context) ([]TenantEnvironmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, tenantEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantEnvironmentsRow{}
	for rows.Next() {
		var i TenantEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.Created,
			&i.LastModified,
			&i.Ci,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantGet = `-- name: TenantGet :one
SELECT id, name, description, created, last_modified, ci
FROM tenants
WHERE id = $1
`

func (q *Queries) TenantGet(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, tenantGet, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const tenantGetByName = `-- name: TenantGetByName :one
SELECT id, name, description, created, last_modified, ci
FROM tenants
WHERE name = $1
`

func (q *Queries) TenantGetByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, tenantGetByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const tenantsGet = `-- name: TenantsGet :many
SELECT id, name, description, created, last_modified, ci
FROM tenants
ORDER BY created DESC, name ASC
`

func (q *Queries) TenantsGet(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, tenantsGet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Created,
			&i.LastModified,
			&i.Ci,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
