package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/pkg/graph/graphgen"
	"github.com/nais/fasit/pkg/graph/model"
)

// Tenant is the resolver for the tenant field.
func (r *costResolver) Tenant(ctx context.Context, obj *model.Cost) (*model.Tenant, error) {
	return r.Repo.TenantGet(ctx, obj.TenantID)
}

// Env is the resolver for the env field.
func (r *costResolver) Env(ctx context.Context, obj *model.Cost) (*model.Environment, error) {
	if obj.EnvID == uuid.Nil {
		return nil, nil
	}
	return r.Repo.EnvironmentGet(ctx, obj.EnvID)
}

// Cost is the resolver for the cost field.
func (r *queryResolver) Cost(ctx context.Context, filter *model.CostFilter) ([]*model.Cost, error) {
	start := time.Now().Add(-24 * 7 * time.Hour)
	end := time.Now()

	byTenant := true
	tenant := uuid.Nil

	if filter != nil {
		if filter.StartDate != nil {
			start = *filter.StartDate
		}
		if filter.EndDate != nil {
			end = *filter.EndDate
		}

		if filter.GroupBy != nil && *filter.GroupBy == model.CostFilterGroupByEnv {
			byTenant = false
		}

		if filter.Tenant != nil && *filter.Tenant != uuid.Nil {
			tenant = *filter.Tenant
		}
	}

	if byTenant {
		return r.Repo.CostByTenant(ctx, tenant, start, end)
	}

	panic("not implemented")
}

// Cost returns graphgen.CostResolver implementation.
func (r *Resolver) Cost() graphgen.CostResolver { return &costResolver{r} }

type costResolver struct{ *Resolver }
