package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/nais/fasit/pkg/graph/graphgen"
	"github.com/nais/fasit/pkg/graph/model"
)

// Operations is the resolver for the operations field.
func (r *clusterUpgradeStatusResolver) Operations(ctx context.Context, obj *model.ClusterUpgradeStatus) ([]*model.EnvironmentOperation, error) {
	return r.Repo.ClusterOperationsGetByUpgradeID(ctx, obj.ID)
}

// Environment is the resolver for the environment field.
func (r *clusterUpgradeStatusResolver) Environment(ctx context.Context, obj *model.ClusterUpgradeStatus) (*model.Environment, error) {
	return r.Repo.EnvironmentGet(ctx, obj.EnvironmentID)
}

// FeatureStates is the resolver for the featureStates field.
func (r *environmentResolver) FeatureStates(ctx context.Context, obj *model.Environment) ([]*model.FeatureState, error) {
	return r.Repo.FeatureStatesGet(ctx, obj.ID)
}

// GcpProjectID is the resolver for the gcpProjectID field.
func (r *environmentResolver) GcpProjectID(ctx context.Context, obj *model.Environment) (*string, error) {
	ev, err := r.Repo.EnvironmentValueGet(ctx, obj.ID, "project_id", false)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}

	if ev == nil {
		return nil, nil
	}

	var id string
	if err := json.Unmarshal(ev.Value, &id); err != nil {
		return nil, err
	}

	if id == "" {
		return nil, nil
	}

	return &id, nil
}

// Health is the resolver for the health field.
func (r *environmentResolver) Health(ctx context.Context, obj *model.Environment) (*model.Health, error) {
	health, err := r.Repo.HealthGet(ctx, obj.ID)
	if err != nil {
		return &model.Health{
			EnvironmentID: obj.ID,
			ReportedAt:    time.Date(1969, 6, 9, 6, 9, 6, 9, time.UTC),
		}, nil
	}
	return health, nil
}

// Releases is the resolver for the releases field.
func (r *environmentResolver) Releases(ctx context.Context, obj *model.Environment) ([]*model.Release, error) {
	return r.Repo.ReleaseStatusesGet(ctx, obj.ID)
}

// Nodes is the resolver for the nodes field.
func (r *environmentResolver) Nodes(ctx context.Context, obj *model.Environment) ([]*model.KubernetesNode, error) {
	return r.Repo.KubernetesNodesForEnv(ctx, obj.ID)
}

// Values is the resolver for the values field.
func (r *environmentResolver) Values(ctx context.Context, obj *model.Environment) ([]*model.EnvironmentValue, error) {
	return r.Repo.EnvironmentValuesForEnvironment(ctx, obj.ID, false)
}

// Tenant is the resolver for the tenant field.
func (r *environmentResolver) Tenant(ctx context.Context, obj *model.Environment) (*model.Tenant, error) {
	return r.Repo.TenantGet(ctx, obj.TenantID)
}

// Warnings is the resolver for the warnings field.
func (r *environmentResolver) Warnings(ctx context.Context, obj *model.Environment) ([]model.Warning, error) {
	return r.Repo.Warnings(ctx, &obj.ID, nil)
}

// AuditLog is the resolver for the auditLog field.
func (r *environmentResolver) AuditLog(ctx context.Context, obj *model.Environment, featureName *string) ([]*model.AuditLog, error) {
	fn := ""
	if featureName != nil {
		fn = *featureName
	}

	return r.Repo.AuditForEnvironment(ctx, obj.ID, fn)
}

// Features is the resolver for the features field.
func (r *environmentResolver) Features(ctx context.Context, obj *model.Environment) ([]*model.Feature, error) {
	fs, err := r.Repo.FeaturesForKind(ctx, obj.Kind, obj.CI)
	if err != nil {
		return nil, err
	}

	for _, f := range fs {
		f.GraphVars.EnvironmentID = obj.ID
	}

	return fs, nil
}

// Feature is the resolver for the feature field.
func (r *environmentResolver) Feature(ctx context.Context, obj *model.Environment, name string) (*model.Feature, error) {
	f, err := r.Repo.FeatureByNameForEnv(ctx, name, obj.ID)
	if err != nil {
		return nil, err
	}

	// copy
	b, err := json.Marshal(f)
	if err != nil {
		return nil, err
	}

	ret := &model.Feature{}
	if err := json.Unmarshal(b, ret); err != nil {
		return nil, err
	}

	ret.GraphVars.EnvironmentID = obj.ID

	return ret, nil
}

// ClusterUpgradeStatus is the resolver for the clusterUpgradeStatus field.
func (r *environmentResolver) ClusterUpgradeStatus(ctx context.Context, obj *model.Environment) (*model.ClusterUpgradeStatus, error) {
	cu, err := r.Repo.ClusterUpgradeGet(ctx, obj.TenantID, obj.ID)
	if err != nil {
		return nil, err
	}

	if cu == nil {
		return nil, nil
	}

	ret := &model.ClusterUpgradeStatus{
		ID:            cu.ID,
		UpgradeStatus: cu.UpgradeStatus,
		Version:       cu.Version,
		LastModified:  cu.LastModified,
		StartTime:     cu.StartTime,
		EnvironmentID: cu.EnvironmentID,
	}

	return ret, nil
}

// Versions is the resolver for the versions field.
func (r *environmentResolver) Versions(ctx context.Context, obj *model.Environment) (*model.EnvironmentVersions, error) {
	projectId, err := r.Environment().GcpProjectID(ctx, obj)
	if err != nil {
		return nil, err
	}

	if projectId == nil {
		return nil, fmt.Errorf("projectId is nil")
	}

	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	if env.Kind == model.EnvironmentKindOnprem {
		return nil, nil
	}

	channel, err := r.UpgraderClient.GetReleaseChannel(ctx, *projectId, obj)
	if err != nil {
		return nil, err
	}
	currentMasterVersion, err := r.UpgraderClient.GetCurrentMasterVersion(ctx, *projectId, obj)
	if err != nil {
		return nil, err
	}
	availableVersions, err := r.UpgraderClient.GetAvailableVersions(ctx, *projectId, obj, channel)
	if err != nil {
		return nil, err
	}

	nodePools, err := r.UpgraderClient.GetNodePools(ctx, *projectId, obj)
	if err != nil {
		return nil, err
	}

	var nodePoolVersions []*model.NodePool

	for _, np := range nodePools {
		nodePoolVersions = append(nodePoolVersions, &model.NodePool{
			Name:    np.Name,
			Version: np.Version,
		})
	}

	return &model.EnvironmentVersions{
		Channel:           channel,
		Apiserver:         currentMasterVersion,
		AvailableVersions: availableVersions,
		NodePools:         nodePoolVersions,
	}, nil
}

// ClusterAuditReports is the resolver for the clusterAuditReports field.
func (r *environmentResolver) ClusterAuditReports(ctx context.Context, obj *model.Environment) ([]*model.ClusterAuditReport, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetConfigAuditReports(env.Name)
	if err != nil {
		return nil, err
	}

	ret := []*model.ClusterAuditReport{}
	for _, rs := range reports {
		checks := []*model.CheckResults{}
		for _, c := range rs.Report.Checks {
			check := &model.CheckResults{
				Title:       c.Title,
				Description: c.Description,
				Severity:    string(c.Severity),
				Category:    c.Category,
				Remediation: c.Remediation,
				Success:     c.Success,
			}
			if c.Scope != nil {
				check.ScopeValue = c.Scope.Value
				check.ScopeType = c.Scope.Type
			}
			checks = append(checks, check)
		}

		ret = append(ret, &model.ClusterAuditReport{
			Name:      rs.Name,
			Namespace: rs.Namespace,
			Updated:   rs.Report.UpdateTimestamp.Time.UTC(),
			Summary: &model.ReportSummary{
				Critical: rs.Report.Summary.CriticalCount,
				High:     rs.Report.Summary.HighCount,
				Medium:   rs.Report.Summary.MediumCount,
				Low:      rs.Report.Summary.LowCount,
			},
			Checks: checks,
		})
	}

	return ret, nil
}

// ClusterAuditTotalSummary is the resolver for the clusterAuditTotalSummary field.
func (r *environmentResolver) ClusterAuditTotalSummary(ctx context.Context, obj *model.Environment) (*model.ReportSummary, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetConfigAuditReports(env.Name)
	if err != nil {
		return nil, err
	}

	total := r.reporterClient.ConfigAuditReportsSummaryTotal(reports)

	return &model.ReportSummary{
		Critical: total.CriticalCount,
		High:     total.HighCount,
		Medium:   total.MediumCount,
		Low:      total.LowCount,
	}, nil
}

// ClusterComplianceReports is the resolver for the clusterComplianceReports field.
func (r *environmentResolver) ClusterComplianceReports(ctx context.Context, obj *model.Environment) ([]*model.ClusterComplianceReport, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetClusterComplianceReports(env.Name)
	if err != nil {
		return nil, err
	}

	ret := []*model.ClusterComplianceReport{}
	for _, rs := range reports {
		ccr := &model.ClusterComplianceReport{
			Name:      rs.Name,
			Namespace: rs.Namespace,
			Updated:   rs.Status.UpdateTimestamp.Time.UTC(),
			FailCount: rs.Status.Summary.FailCount,
			PassCount: rs.Status.Summary.PassCount,
		}

		if rs.Status.SummaryReport != nil {
			ccr.Summary = &model.ClusterComplianceReportSummaryReport{
				Title: rs.Status.SummaryReport.Title,
			}

			for _, c := range rs.Status.SummaryReport.SummaryControls {
				checkResult := &model.CheckResults{
					Title:    c.Name,
					Severity: c.Severity,
				}
				if c.TotalFail != nil {
					checkResult.TotalFail = *c.TotalFail
				}
				for _, control := range rs.Spec.Complaince.Controls {
					if control.ID == c.ID {
						checkResult.Description = control.Description
					}
				}
				ccr.Summary.ClusterComplianceCheckResults = append(ccr.Summary.ClusterComplianceCheckResults, checkResult)
			}
		}
		ret = append(ret, ccr)
	}
	return ret, nil
}

// ClusterComplianceTotalSummary is the resolver for the clusterComplianceTotalSummary field.
func (r *environmentResolver) ClusterComplianceTotalSummary(ctx context.Context, obj *model.Environment) (*model.ClusterComplianceTotalSummaryReport, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetClusterComplianceReports(env.Name)
	if err != nil {
		return nil, err
	}

	total := r.reporterClient.ClusterComplianceReportsSummaryTotal(reports)

	return &model.ClusterComplianceTotalSummaryReport{
		PassCount: total.PassCount,
		FailCount: total.FailCount,
	}, nil
}

// RbacAssessmentReports is the resolver for the RbacAssessmentReports field.
func (r *environmentResolver) RbacAssessmentReports(ctx context.Context, obj *model.Environment) ([]*model.RbacAssessmentReport, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetClusterRbacReports(env.Name)
	if err != nil {
		return nil, err
	}

	ret := []*model.RbacAssessmentReport{}
	for _, rs := range reports {
		crr := &model.RbacAssessmentReport{
			Name:      rs.Name,
			Namespace: rs.Namespace,
			TotalSummary: &model.ReportSummary{
				Critical: rs.Report.Summary.CriticalCount,
				High:     rs.Report.Summary.HighCount,
				Medium:   rs.Report.Summary.MediumCount,
				Low:      rs.Report.Summary.LowCount,
			},
		}
		for _, c := range rs.Report.Checks {
			crr.SummaryReport = append(crr.SummaryReport, &model.CheckResults{
				Title:       c.Title,
				Description: c.Description,
				Severity:    string(c.Severity),
				Success:     c.Success,
				Remediation: c.Remediation,
				Messages:    c.Messages,
			})
		}
		ret = append(ret, crr)
	}
	return ret, nil
}

// RbacTotalSummary is the resolver for the rbacTotalSummary field.
func (r *environmentResolver) RbacTotalSummary(ctx context.Context, obj *model.Environment) (*model.ReportSummary, error) {
	env, err := r.Repo.EnvironmentGet(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.reporterClient.GetClusterRbacReports(env.Name)
	if err != nil {
		return nil, err
	}

	total := r.reporterClient.RbacAssessmentSummaryTotal(reports)

	return &model.ReportSummary{
		Critical: total.CriticalCount,
		High:     total.HighCount,
		Medium:   total.MediumCount,
		Low:      total.LowCount,
	}, nil
}

// EnvironmentCreate is the resolver for the environmentCreate field.
func (r *mutationResolver) EnvironmentCreate(ctx context.Context, environment model.EnvironmentCreate) (*model.Environment, error) {
	return r.Repo.EnvironmentCreate(ctx, &environment)
}

// EnvironmentUpdate is the resolver for the environmentUpdate field.
func (r *mutationResolver) EnvironmentUpdate(ctx context.Context, id uuid.UUID, input model.EnvironmentUpdate) (*model.Environment, error) {
	return r.Repo.EnvironmentUpdate(ctx, id, &input)
}

// EnvironmentSetReconcile is the resolver for the environmentSetReconcile field.
func (r *mutationResolver) EnvironmentSetReconcile(ctx context.Context, id uuid.UUID, reconcile bool) (*model.Environment, error) {
	return r.Repo.EnvironmentSetReconcile(ctx, id, reconcile)
}

// EnvironmentUpgrade is the resolver for the environmentUpgrade field.
func (r *mutationResolver) EnvironmentUpgrade(ctx context.Context, upgrade *model.EnvironmentUpgrade) (*model.Environment, error) {
	env, err := r.Repo.EnvironmentGet(ctx, upgrade.EnvID)
	if err != nil {
		return nil, err
	}

	if env.Kind == model.EnvironmentKindOnprem {
		return nil, fmt.Errorf("environment %s is onprem", env.Name)
	}

	_, err = r.Repo.CreateClusterUpgrade(ctx, env.TenantID, upgrade.EnvID, upgrade.Version)
	if err != nil {
		return nil, err
	}

	return env, nil
}

// Feature is the resolver for the feature field.
func (r *releaseResolver) Feature(ctx context.Context, obj *model.Release) (*model.Feature, error) {
	f, err := r.Repo.FeatureByNameForEnv(ctx, obj.Name, obj.GraphVars.EnvironmentID)
	if err != nil {
		r.Log.WithError(err).Debug("error getting feature for release, returning nil")
	}

	if f == nil {
		return nil, nil
	}

	f.GraphVars.EnvironmentID = obj.GraphVars.EnvironmentID

	return f, nil
}

// ClusterUpgradeStatus returns graphgen.ClusterUpgradeStatusResolver implementation.
func (r *Resolver) ClusterUpgradeStatus() graphgen.ClusterUpgradeStatusResolver {
	return &clusterUpgradeStatusResolver{r}
}

// Environment returns graphgen.EnvironmentResolver implementation.
func (r *Resolver) Environment() graphgen.EnvironmentResolver { return &environmentResolver{r} }

// Release returns graphgen.ReleaseResolver implementation.
func (r *Resolver) Release() graphgen.ReleaseResolver { return &releaseResolver{r} }

type (
	clusterUpgradeStatusResolver struct{ *Resolver }
	environmentResolver          struct{ *Resolver }
	releaseResolver              struct{ *Resolver }
)
