package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/nais/fasit/pkg/graph/graphgen"
	"github.com/nais/fasit/pkg/graph/model"
)

// Rollouts is the resolver for the rollouts field.
func (r *queryResolver) Rollouts(ctx context.Context, feature string) ([]*model.Rollout, error) {
	return r.Repo.RolloutsForFeature(ctx, feature)
}

// Rollout is the resolver for the rollout field.
func (r *queryResolver) Rollout(ctx context.Context, feature string, version string) (*model.Rollout, error) {
	return r.Repo.RolloutByNameAndVersion(ctx, feature, version)
}

// Events is the resolver for the events field.
func (r *rolloutResolver) Events(ctx context.Context, obj *model.Rollout) ([]*model.RolloutEvent, error) {
	return r.Repo.RolloutEvents(ctx, obj.ID)
}

// Rollout returns graphgen.RolloutResolver implementation.
func (r *Resolver) Rollout() graphgen.RolloutResolver { return &rolloutResolver{r} }

type rolloutResolver struct{ *Resolver }
