package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/nais/fasit/pkg/graph/graphgen"
	"github.com/nais/fasit/pkg/graph/model"
)

// Feature is the resolver for the feature field.
func (r *featureWarningResolver) Feature(ctx context.Context, obj *model.FeatureWarning) (*model.Feature, error) {
	return r.Repo.FeatureByNameForEnv(ctx, obj.FeatureName, obj.EnvironmentID)
}

// Environment is the resolver for the environment field.
func (r *featureWarningResolver) Environment(ctx context.Context, obj *model.FeatureWarning) (*model.Environment, error) {
	return r.Repo.EnvironmentGet(ctx, obj.EnvironmentID)
}

// Environment is the resolver for the environment field.
func (r *naisdWarningResolver) Environment(ctx context.Context, obj *model.NaisdWarning) (*model.Environment, error) {
	return r.Repo.EnvironmentGet(ctx, obj.EnvironmentID)
}

// FeatureWarning returns graphgen.FeatureWarningResolver implementation.
func (r *Resolver) FeatureWarning() graphgen.FeatureWarningResolver {
	return &featureWarningResolver{r}
}

// NaisdWarning returns graphgen.NaisdWarningResolver implementation.
func (r *Resolver) NaisdWarning() graphgen.NaisdWarningResolver { return &naisdWarningResolver{r} }

type (
	featureWarningResolver struct{ *Resolver }
	naisdWarningResolver   struct{ *Resolver }
)
