// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nais/fasit/internal/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAutoInstallsRepo creates a new instance of AutoInstallsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoInstallsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoInstallsRepo {
	mock := &AutoInstallsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AutoInstallsRepo is an autogenerated mock type for the AutoInstallsRepo type
type AutoInstallsRepo struct {
	mock.Mock
}

type AutoInstallsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoInstallsRepo) EXPECT() *AutoInstallsRepo_Expecter {
	return &AutoInstallsRepo_Expecter{mock: &_m.Mock}
}

// AutoInstallsForKind provides a mock function for the type AutoInstallsRepo
func (_mock *AutoInstallsRepo) AutoInstallsForKind(ctx context.Context, kind model.EnvironmentKind) ([]string, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for AutoInstallsForKind")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) ([]string, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) []string); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.EnvironmentKind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoInstallsRepo_AutoInstallsForKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoInstallsForKind'
type AutoInstallsRepo_AutoInstallsForKind_Call struct {
	*mock.Call
}

// AutoInstallsForKind is a helper method to define mock.On call
//   - ctx context.Context
//   - kind model.EnvironmentKind
func (_e *AutoInstallsRepo_Expecter) AutoInstallsForKind(ctx interface{}, kind interface{}) *AutoInstallsRepo_AutoInstallsForKind_Call {
	return &AutoInstallsRepo_AutoInstallsForKind_Call{Call: _e.mock.On("AutoInstallsForKind", ctx, kind)}
}

func (_c *AutoInstallsRepo_AutoInstallsForKind_Call) Run(run func(ctx context.Context, kind model.EnvironmentKind)) *AutoInstallsRepo_AutoInstallsForKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.EnvironmentKind
		if args[1] != nil {
			arg1 = args[1].(model.EnvironmentKind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AutoInstallsRepo_AutoInstallsForKind_Call) Return(strings []string, err error) *AutoInstallsRepo_AutoInstallsForKind_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *AutoInstallsRepo_AutoInstallsForKind_Call) RunAndReturn(run func(ctx context.Context, kind model.EnvironmentKind) ([]string, error)) *AutoInstallsRepo_AutoInstallsForKind_Call {
	_c.Call.Return(run)
	return _c
}
