// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"cloud.google.com/go/container/apiv1/containerpb"
	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/gensql"
	"github.com/nais/fasit/internal/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// NewClusterUpgraderRepo creates a new instance of ClusterUpgraderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClusterUpgraderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClusterUpgraderRepo {
	mock := &ClusterUpgraderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClusterUpgraderRepo is an autogenerated mock type for the ClusterUpgraderRepo type
type ClusterUpgraderRepo struct {
	mock.Mock
}

type ClusterUpgraderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ClusterUpgraderRepo) EXPECT() *ClusterUpgraderRepo_Expecter {
	return &ClusterUpgraderRepo_Expecter{mock: &_m.Mock}
}

// ClusterOperationsGetByID provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) ClusterOperationsGetByID(ctx context.Context, id uuid.UUID) (*model.EnvironmentOperation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClusterOperationsGetByID")
	}

	var r0 *model.EnvironmentOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.EnvironmentOperation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.EnvironmentOperation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EnvironmentOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_ClusterOperationsGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterOperationsGetByID'
type ClusterUpgraderRepo_ClusterOperationsGetByID_Call struct {
	*mock.Call
}

// ClusterOperationsGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) ClusterOperationsGetByID(ctx interface{}, id interface{}) *ClusterUpgraderRepo_ClusterOperationsGetByID_Call {
	return &ClusterUpgraderRepo_ClusterOperationsGetByID_Call{Call: _e.mock.On("ClusterOperationsGetByID", ctx, id)}
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClusterUpgraderRepo_ClusterOperationsGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByID_Call) Return(environmentOperation *model.EnvironmentOperation, err error) *ClusterUpgraderRepo_ClusterOperationsGetByID_Call {
	_c.Call.Return(environmentOperation, err)
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.EnvironmentOperation, error)) *ClusterUpgraderRepo_ClusterOperationsGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterOperationsGetByUpgradeID provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) ClusterOperationsGetByUpgradeID(ctx context.Context, upgradeID uuid.UUID) ([]*model.EnvironmentOperation, error) {
	ret := _mock.Called(ctx, upgradeID)

	if len(ret) == 0 {
		panic("no return value specified for ClusterOperationsGetByUpgradeID")
	}

	var r0 []*model.EnvironmentOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.EnvironmentOperation, error)); ok {
		return returnFunc(ctx, upgradeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.EnvironmentOperation); ok {
		r0 = returnFunc(ctx, upgradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EnvironmentOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, upgradeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterOperationsGetByUpgradeID'
type ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call struct {
	*mock.Call
}

// ClusterOperationsGetByUpgradeID is a helper method to define mock.On call
//   - ctx context.Context
//   - upgradeID uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) ClusterOperationsGetByUpgradeID(ctx interface{}, upgradeID interface{}) *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call {
	return &ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call{Call: _e.mock.On("ClusterOperationsGetByUpgradeID", ctx, upgradeID)}
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call) Run(run func(ctx context.Context, upgradeID uuid.UUID)) *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call) Return(environmentOperations []*model.EnvironmentOperation, err error) *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call {
	_c.Call.Return(environmentOperations, err)
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call) RunAndReturn(run func(ctx context.Context, upgradeID uuid.UUID) ([]*model.EnvironmentOperation, error)) *ClusterUpgraderRepo_ClusterOperationsGetByUpgradeID_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterUpgradeGet provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) ClusterUpgradeGet(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) (*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, tenantID, envID)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpgradeGet")
	}

	var r0 *model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, tenantID, envID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, tenantID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, envID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_ClusterUpgradeGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterUpgradeGet'
type ClusterUpgraderRepo_ClusterUpgradeGet_Call struct {
	*mock.Call
}

// ClusterUpgradeGet is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) ClusterUpgradeGet(ctx interface{}, tenantID interface{}, envID interface{}) *ClusterUpgraderRepo_ClusterUpgradeGet_Call {
	return &ClusterUpgraderRepo_ClusterUpgradeGet_Call{Call: _e.mock.On("ClusterUpgradeGet", ctx, tenantID, envID)}
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGet_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID)) *ClusterUpgraderRepo_ClusterUpgradeGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGet_Call) Return(clusterUpgradeStatus *model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_ClusterUpgradeGet_Call {
	_c.Call.Return(clusterUpgradeStatus, err)
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGet_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) (*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_ClusterUpgradeGet_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterUpgradeGetByID provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) ClusterUpgradeGetByID(ctx context.Context, id uuid.UUID) (*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpgradeGetByID")
	}

	var r0 *model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_ClusterUpgradeGetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterUpgradeGetByID'
type ClusterUpgraderRepo_ClusterUpgradeGetByID_Call struct {
	*mock.Call
}

// ClusterUpgradeGetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) ClusterUpgradeGetByID(ctx interface{}, id interface{}) *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call {
	return &ClusterUpgraderRepo_ClusterUpgradeGetByID_Call{Call: _e.mock.On("ClusterUpgradeGetByID", ctx, id)}
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call) Return(clusterUpgradeStatus *model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call {
	_c.Call.Return(clusterUpgradeStatus, err)
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_ClusterUpgradeGetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterUpgradeHistoryGet provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) ClusterUpgradeHistoryGet(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) ([]*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, tenantID, envID)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpgradeHistoryGet")
	}

	var r0 []*model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, tenantID, envID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []*model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, tenantID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, envID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterUpgradeHistoryGet'
type ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call struct {
	*mock.Call
}

// ClusterUpgradeHistoryGet is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) ClusterUpgradeHistoryGet(ctx interface{}, tenantID interface{}, envID interface{}) *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call {
	return &ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call{Call: _e.mock.On("ClusterUpgradeHistoryGet", ctx, tenantID, envID)}
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID)) *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call) Return(clusterUpgradeStatuss []*model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call {
	_c.Call.Return(clusterUpgradeStatuss, err)
	return _c
}

func (_c *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) ([]*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_ClusterUpgradeHistoryGet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClusterUpgrade provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) CreateClusterUpgrade(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, version string) (*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, tenantID, envID, version)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterUpgrade")
	}

	var r0 *model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, tenantID, envID, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, tenantID, envID, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tenantID, envID, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_CreateClusterUpgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterUpgrade'
type ClusterUpgraderRepo_CreateClusterUpgrade_Call struct {
	*mock.Call
}

// CreateClusterUpgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
//   - version string
func (_e *ClusterUpgraderRepo_Expecter) CreateClusterUpgrade(ctx interface{}, tenantID interface{}, envID interface{}, version interface{}) *ClusterUpgraderRepo_CreateClusterUpgrade_Call {
	return &ClusterUpgraderRepo_CreateClusterUpgrade_Call{Call: _e.mock.On("CreateClusterUpgrade", ctx, tenantID, envID, version)}
}

func (_c *ClusterUpgraderRepo_CreateClusterUpgrade_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, version string)) *ClusterUpgraderRepo_CreateClusterUpgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_CreateClusterUpgrade_Call) Return(clusterUpgradeStatus *model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_CreateClusterUpgrade_Call {
	_c.Call.Return(clusterUpgradeStatus, err)
	return _c
}

func (_c *ClusterUpgraderRepo_CreateClusterUpgrade_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, version string) (*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_CreateClusterUpgrade_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateClusterOperation provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) CreateOrUpdateClusterOperation(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, versionID uuid.UUID, op *containerpb.Operation) (*model.EnvironmentOperation, error) {
	ret := _mock.Called(ctx, tenantID, envID, versionID, op)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateClusterOperation")
	}

	var r0 *model.EnvironmentOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *containerpb.Operation) (*model.EnvironmentOperation, error)); ok {
		return returnFunc(ctx, tenantID, envID, versionID, op)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *containerpb.Operation) *model.EnvironmentOperation); ok {
		r0 = returnFunc(ctx, tenantID, envID, versionID, op)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EnvironmentOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *containerpb.Operation) error); ok {
		r1 = returnFunc(ctx, tenantID, envID, versionID, op)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateClusterOperation'
type ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call struct {
	*mock.Call
}

// CreateOrUpdateClusterOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
//   - versionID uuid.UUID
//   - op *containerpb.Operation
func (_e *ClusterUpgraderRepo_Expecter) CreateOrUpdateClusterOperation(ctx interface{}, tenantID interface{}, envID interface{}, versionID interface{}, op interface{}) *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call {
	return &ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call{Call: _e.mock.On("CreateOrUpdateClusterOperation", ctx, tenantID, envID, versionID, op)}
}

func (_c *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, versionID uuid.UUID, op *containerpb.Operation)) *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 *containerpb.Operation
		if args[4] != nil {
			arg4 = args[4].(*containerpb.Operation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call) Return(environmentOperation *model.EnvironmentOperation, err error) *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call {
	_c.Call.Return(environmentOperation, err)
	return _c
}

func (_c *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, versionID uuid.UUID, op *containerpb.Operation) (*model.EnvironmentOperation, error)) *ClusterUpgraderRepo_CreateOrUpdateClusterOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunningClusterOperation provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) GetRunningClusterOperation(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) (*model.EnvironmentOperation, error) {
	ret := _mock.Called(ctx, tenantID, envID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunningClusterOperation")
	}

	var r0 *model.EnvironmentOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.EnvironmentOperation, error)); ok {
		return returnFunc(ctx, tenantID, envID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.EnvironmentOperation); ok {
		r0 = returnFunc(ctx, tenantID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EnvironmentOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, envID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_GetRunningClusterOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunningClusterOperation'
type ClusterUpgraderRepo_GetRunningClusterOperation_Call struct {
	*mock.Call
}

// GetRunningClusterOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
func (_e *ClusterUpgraderRepo_Expecter) GetRunningClusterOperation(ctx interface{}, tenantID interface{}, envID interface{}) *ClusterUpgraderRepo_GetRunningClusterOperation_Call {
	return &ClusterUpgraderRepo_GetRunningClusterOperation_Call{Call: _e.mock.On("GetRunningClusterOperation", ctx, tenantID, envID)}
}

func (_c *ClusterUpgraderRepo_GetRunningClusterOperation_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID)) *ClusterUpgraderRepo_GetRunningClusterOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_GetRunningClusterOperation_Call) Return(environmentOperation *model.EnvironmentOperation, err error) *ClusterUpgraderRepo_GetRunningClusterOperation_Call {
	_c.Call.Return(environmentOperation, err)
	return _c
}

func (_c *ClusterUpgraderRepo_GetRunningClusterOperation_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID) (*model.EnvironmentOperation, error)) *ClusterUpgraderRepo_GetRunningClusterOperation_Call {
	_c.Call.Return(run)
	return _c
}

// SetClusterUpgradesSlackMessage provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) SetClusterUpgradesSlackMessage(ctx context.Context, id uuid.UUID, slackMessageTS string, channelID string) (*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, id, slackMessageTS, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetClusterUpgradesSlackMessage")
	}

	var r0 *model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, id, slackMessageTS, channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, id, slackMessageTS, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, id, slackMessageTS, channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClusterUpgradesSlackMessage'
type ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call struct {
	*mock.Call
}

// SetClusterUpgradesSlackMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - slackMessageTS string
//   - channelID string
func (_e *ClusterUpgraderRepo_Expecter) SetClusterUpgradesSlackMessage(ctx interface{}, id interface{}, slackMessageTS interface{}, channelID interface{}) *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call {
	return &ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call{Call: _e.mock.On("SetClusterUpgradesSlackMessage", ctx, id, slackMessageTS, channelID)}
}

func (_c *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call) Run(run func(ctx context.Context, id uuid.UUID, slackMessageTS string, channelID string)) *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call) Return(clusterUpgradeStatus *model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call {
	_c.Call.Return(clusterUpgradeStatus, err)
	return _c
}

func (_c *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, slackMessageTS string, channelID string) (*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_SetClusterUpgradesSlackMessage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterUpgradeStatus provides a mock function for the type ClusterUpgraderRepo
func (_mock *ClusterUpgraderRepo) UpdateClusterUpgradeStatus(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, status gensql.ClusterUpgradesStatus, version string) (*model.ClusterUpgradeStatus, error) {
	ret := _mock.Called(ctx, tenantID, envID, status, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterUpgradeStatus")
	}

	var r0 *model.ClusterUpgradeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, gensql.ClusterUpgradesStatus, string) (*model.ClusterUpgradeStatus, error)); ok {
		return returnFunc(ctx, tenantID, envID, status, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, gensql.ClusterUpgradesStatus, string) *model.ClusterUpgradeStatus); ok {
		r0 = returnFunc(ctx, tenantID, envID, status, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterUpgradeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, gensql.ClusterUpgradesStatus, string) error); ok {
		r1 = returnFunc(ctx, tenantID, envID, status, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterUpgradeStatus'
type ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call struct {
	*mock.Call
}

// UpdateClusterUpgradeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - envID uuid.UUID
//   - status gensql.ClusterUpgradesStatus
//   - version string
func (_e *ClusterUpgraderRepo_Expecter) UpdateClusterUpgradeStatus(ctx interface{}, tenantID interface{}, envID interface{}, status interface{}, version interface{}) *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call {
	return &ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call{Call: _e.mock.On("UpdateClusterUpgradeStatus", ctx, tenantID, envID, status, version)}
}

func (_c *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, status gensql.ClusterUpgradesStatus, version string)) *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 gensql.ClusterUpgradesStatus
		if args[3] != nil {
			arg3 = args[3].(gensql.ClusterUpgradesStatus)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call) Return(clusterUpgradeStatus *model.ClusterUpgradeStatus, err error) *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call {
	_c.Call.Return(clusterUpgradeStatus, err)
	return _c
}

func (_c *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, envID uuid.UUID, status gensql.ClusterUpgradesStatus, version string) (*model.ClusterUpgradeStatus, error)) *ClusterUpgraderRepo_UpdateClusterUpgradeStatus_Call {
	_c.Call.Return(run)
	return _c
}
