// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nais/fasit/internal/feature"
	"github.com/nais/fasit/internal/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// NewFeatureDataRepo creates a new instance of FeatureDataRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeatureDataRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeatureDataRepo {
	mock := &FeatureDataRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FeatureDataRepo is an autogenerated mock type for the FeatureDataRepo type
type FeatureDataRepo struct {
	mock.Mock
}

type FeatureDataRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *FeatureDataRepo) EXPECT() *FeatureDataRepo_Expecter {
	return &FeatureDataRepo_Expecter{mock: &_m.Mock}
}

// FeatureDataCreate provides a mock function for the type FeatureDataRepo
func (_mock *FeatureDataRepo) FeatureDataCreate(context1 context.Context, feature1 model.Feature, featureTemplateDetails *feature.FeatureTemplateDetails) error {
	ret := _mock.Called(context1, feature1, featureTemplateDetails)

	if len(ret) == 0 {
		panic("no return value specified for FeatureDataCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Feature, *feature.FeatureTemplateDetails) error); ok {
		r0 = returnFunc(context1, feature1, featureTemplateDetails)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FeatureDataRepo_FeatureDataCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FeatureDataCreate'
type FeatureDataRepo_FeatureDataCreate_Call struct {
	*mock.Call
}

// FeatureDataCreate is a helper method to define mock.On call
//   - context1 context.Context
//   - feature1 model.Feature
//   - featureTemplateDetails *feature.FeatureTemplateDetails
func (_e *FeatureDataRepo_Expecter) FeatureDataCreate(context1 interface{}, feature1 interface{}, featureTemplateDetails interface{}) *FeatureDataRepo_FeatureDataCreate_Call {
	return &FeatureDataRepo_FeatureDataCreate_Call{Call: _e.mock.On("FeatureDataCreate", context1, feature1, featureTemplateDetails)}
}

func (_c *FeatureDataRepo_FeatureDataCreate_Call) Run(run func(context1 context.Context, feature1 model.Feature, featureTemplateDetails *feature.FeatureTemplateDetails)) *FeatureDataRepo_FeatureDataCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Feature
		if args[1] != nil {
			arg1 = args[1].(model.Feature)
		}
		var arg2 *feature.FeatureTemplateDetails
		if args[2] != nil {
			arg2 = args[2].(*feature.FeatureTemplateDetails)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FeatureDataRepo_FeatureDataCreate_Call) Return(err error) *FeatureDataRepo_FeatureDataCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FeatureDataRepo_FeatureDataCreate_Call) RunAndReturn(run func(context1 context.Context, feature1 model.Feature, featureTemplateDetails *feature.FeatureTemplateDetails) error) *FeatureDataRepo_FeatureDataCreate_Call {
	_c.Call.Return(run)
	return _c
}
