// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/nais/fasit/internal/database/gensql"
	"github.com/nais/fasit/internal/database/types"
	mock "github.com/stretchr/testify/mock"
)

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

type Querier_Expecter struct {
	mock *mock.Mock
}

func (_m *Querier) EXPECT() *Querier_Expecter {
	return &Querier_Expecter{mock: &_m.Mock}
}

// DeployInstructionsForFeature provides a mock function for the type Querier
func (_mock *Querier) DeployInstructionsForFeature(ctx context.Context, arg gensql.DeployInstructionsForFeatureParams) ([]gensql.DeployInstruction, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeployInstructionsForFeature")
	}

	var r0 []gensql.DeployInstruction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsForFeatureParams) ([]gensql.DeployInstruction, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsForFeatureParams) []gensql.DeployInstruction); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.DeployInstruction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.DeployInstructionsForFeatureParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_DeployInstructionsForFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployInstructionsForFeature'
type Querier_DeployInstructionsForFeature_Call struct {
	*mock.Call
}

// DeployInstructionsForFeature is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.DeployInstructionsForFeatureParams
func (_e *Querier_Expecter) DeployInstructionsForFeature(ctx interface{}, arg interface{}) *Querier_DeployInstructionsForFeature_Call {
	return &Querier_DeployInstructionsForFeature_Call{Call: _e.mock.On("DeployInstructionsForFeature", ctx, arg)}
}

func (_c *Querier_DeployInstructionsForFeature_Call) Run(run func(ctx context.Context, arg gensql.DeployInstructionsForFeatureParams)) *Querier_DeployInstructionsForFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.DeployInstructionsForFeatureParams
		if args[1] != nil {
			arg1 = args[1].(gensql.DeployInstructionsForFeatureParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_DeployInstructionsForFeature_Call) Return(deployInstructions []gensql.DeployInstruction, err error) *Querier_DeployInstructionsForFeature_Call {
	_c.Call.Return(deployInstructions, err)
	return _c
}

func (_c *Querier_DeployInstructionsForFeature_Call) RunAndReturn(run func(ctx context.Context, arg gensql.DeployInstructionsForFeatureParams) ([]gensql.DeployInstruction, error)) *Querier_DeployInstructionsForFeature_Call {
	_c.Call.Return(run)
	return _c
}

// DeployInstructionsLatestDeployedForFeature provides a mock function for the type Querier
func (_mock *Querier) DeployInstructionsLatestDeployedForFeature(ctx context.Context, arg gensql.DeployInstructionsLatestDeployedForFeatureParams) (gensql.DeployInstruction, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeployInstructionsLatestDeployedForFeature")
	}

	var r0 gensql.DeployInstruction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsLatestDeployedForFeatureParams) (gensql.DeployInstruction, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsLatestDeployedForFeatureParams) gensql.DeployInstruction); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.DeployInstruction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.DeployInstructionsLatestDeployedForFeatureParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_DeployInstructionsLatestDeployedForFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployInstructionsLatestDeployedForFeature'
type Querier_DeployInstructionsLatestDeployedForFeature_Call struct {
	*mock.Call
}

// DeployInstructionsLatestDeployedForFeature is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.DeployInstructionsLatestDeployedForFeatureParams
func (_e *Querier_Expecter) DeployInstructionsLatestDeployedForFeature(ctx interface{}, arg interface{}) *Querier_DeployInstructionsLatestDeployedForFeature_Call {
	return &Querier_DeployInstructionsLatestDeployedForFeature_Call{Call: _e.mock.On("DeployInstructionsLatestDeployedForFeature", ctx, arg)}
}

func (_c *Querier_DeployInstructionsLatestDeployedForFeature_Call) Run(run func(ctx context.Context, arg gensql.DeployInstructionsLatestDeployedForFeatureParams)) *Querier_DeployInstructionsLatestDeployedForFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.DeployInstructionsLatestDeployedForFeatureParams
		if args[1] != nil {
			arg1 = args[1].(gensql.DeployInstructionsLatestDeployedForFeatureParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_DeployInstructionsLatestDeployedForFeature_Call) Return(deployInstruction gensql.DeployInstruction, err error) *Querier_DeployInstructionsLatestDeployedForFeature_Call {
	_c.Call.Return(deployInstruction, err)
	return _c
}

func (_c *Querier_DeployInstructionsLatestDeployedForFeature_Call) RunAndReturn(run func(ctx context.Context, arg gensql.DeployInstructionsLatestDeployedForFeatureParams) (gensql.DeployInstruction, error)) *Querier_DeployInstructionsLatestDeployedForFeature_Call {
	_c.Call.Return(run)
	return _c
}

// DeployInstructionsLatestForFeature provides a mock function for the type Querier
func (_mock *Querier) DeployInstructionsLatestForFeature(ctx context.Context, arg gensql.DeployInstructionsLatestForFeatureParams) (gensql.DeployInstruction, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeployInstructionsLatestForFeature")
	}

	var r0 gensql.DeployInstruction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsLatestForFeatureParams) (gensql.DeployInstruction, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsLatestForFeatureParams) gensql.DeployInstruction); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.DeployInstruction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.DeployInstructionsLatestForFeatureParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_DeployInstructionsLatestForFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployInstructionsLatestForFeature'
type Querier_DeployInstructionsLatestForFeature_Call struct {
	*mock.Call
}

// DeployInstructionsLatestForFeature is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.DeployInstructionsLatestForFeatureParams
func (_e *Querier_Expecter) DeployInstructionsLatestForFeature(ctx interface{}, arg interface{}) *Querier_DeployInstructionsLatestForFeature_Call {
	return &Querier_DeployInstructionsLatestForFeature_Call{Call: _e.mock.On("DeployInstructionsLatestForFeature", ctx, arg)}
}

func (_c *Querier_DeployInstructionsLatestForFeature_Call) Run(run func(ctx context.Context, arg gensql.DeployInstructionsLatestForFeatureParams)) *Querier_DeployInstructionsLatestForFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.DeployInstructionsLatestForFeatureParams
		if args[1] != nil {
			arg1 = args[1].(gensql.DeployInstructionsLatestForFeatureParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_DeployInstructionsLatestForFeature_Call) Return(deployInstruction gensql.DeployInstruction, err error) *Querier_DeployInstructionsLatestForFeature_Call {
	_c.Call.Return(deployInstruction, err)
	return _c
}

func (_c *Querier_DeployInstructionsLatestForFeature_Call) RunAndReturn(run func(ctx context.Context, arg gensql.DeployInstructionsLatestForFeatureParams) (gensql.DeployInstruction, error)) *Querier_DeployInstructionsLatestForFeature_Call {
	_c.Call.Return(run)
	return _c
}

// DeployInstructionsPrevious provides a mock function for the type Querier
func (_mock *Querier) DeployInstructionsPrevious(ctx context.Context, id uuid.UUID) (gensql.DeployInstruction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeployInstructionsPrevious")
	}

	var r0 gensql.DeployInstruction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (gensql.DeployInstruction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.DeployInstruction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(gensql.DeployInstruction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_DeployInstructionsPrevious_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployInstructionsPrevious'
type Querier_DeployInstructionsPrevious_Call struct {
	*mock.Call
}

// DeployInstructionsPrevious is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Querier_Expecter) DeployInstructionsPrevious(ctx interface{}, id interface{}) *Querier_DeployInstructionsPrevious_Call {
	return &Querier_DeployInstructionsPrevious_Call{Call: _e.mock.On("DeployInstructionsPrevious", ctx, id)}
}

func (_c *Querier_DeployInstructionsPrevious_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Querier_DeployInstructionsPrevious_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_DeployInstructionsPrevious_Call) Return(deployInstruction gensql.DeployInstruction, err error) *Querier_DeployInstructionsPrevious_Call {
	_c.Call.Return(deployInstruction, err)
	return _c
}

func (_c *Querier_DeployInstructionsPrevious_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (gensql.DeployInstruction, error)) *Querier_DeployInstructionsPrevious_Call {
	_c.Call.Return(run)
	return _c
}

// DeployInstructionsUpdateStatus provides a mock function for the type Querier
func (_mock *Querier) DeployInstructionsUpdateStatus(ctx context.Context, arg gensql.DeployInstructionsUpdateStatusParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeployInstructionsUpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.DeployInstructionsUpdateStatusParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_DeployInstructionsUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployInstructionsUpdateStatus'
type Querier_DeployInstructionsUpdateStatus_Call struct {
	*mock.Call
}

// DeployInstructionsUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.DeployInstructionsUpdateStatusParams
func (_e *Querier_Expecter) DeployInstructionsUpdateStatus(ctx interface{}, arg interface{}) *Querier_DeployInstructionsUpdateStatus_Call {
	return &Querier_DeployInstructionsUpdateStatus_Call{Call: _e.mock.On("DeployInstructionsUpdateStatus", ctx, arg)}
}

func (_c *Querier_DeployInstructionsUpdateStatus_Call) Run(run func(ctx context.Context, arg gensql.DeployInstructionsUpdateStatusParams)) *Querier_DeployInstructionsUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.DeployInstructionsUpdateStatusParams
		if args[1] != nil {
			arg1 = args[1].(gensql.DeployInstructionsUpdateStatusParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_DeployInstructionsUpdateStatus_Call) Return(err error) *Querier_DeployInstructionsUpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_DeployInstructionsUpdateStatus_Call) RunAndReturn(run func(ctx context.Context, arg gensql.DeployInstructionsUpdateStatusParams) error) *Querier_DeployInstructionsUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentByNames provides a mock function for the type Querier
func (_mock *Querier) EnvironmentByNames(ctx context.Context, arg gensql.EnvironmentByNamesParams) (gensql.Environment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentByNames")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentByNamesParams) (gensql.Environment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentByNamesParams) gensql.Environment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentByNamesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentByNames'
type Querier_EnvironmentByNames_Call struct {
	*mock.Call
}

// EnvironmentByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentByNamesParams
func (_e *Querier_Expecter) EnvironmentByNames(ctx interface{}, arg interface{}) *Querier_EnvironmentByNames_Call {
	return &Querier_EnvironmentByNames_Call{Call: _e.mock.On("EnvironmentByNames", ctx, arg)}
}

func (_c *Querier_EnvironmentByNames_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentByNamesParams)) *Querier_EnvironmentByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentByNamesParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentByNamesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentByNames_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentByNames_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentByNames_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentByNamesParams) (gensql.Environment, error)) *Querier_EnvironmentByNames_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentCI provides a mock function for the type Querier
func (_mock *Querier) EnvironmentCI(ctx context.Context, kind types.EnvironmentKind) (gensql.Environment, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentCI")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.EnvironmentKind) (gensql.Environment, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.EnvironmentKind) gensql.Environment); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.EnvironmentKind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentCI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentCI'
type Querier_EnvironmentCI_Call struct {
	*mock.Call
}

// EnvironmentCI is a helper method to define mock.On call
//   - ctx context.Context
//   - kind types.EnvironmentKind
func (_e *Querier_Expecter) EnvironmentCI(ctx interface{}, kind interface{}) *Querier_EnvironmentCI_Call {
	return &Querier_EnvironmentCI_Call{Call: _e.mock.On("EnvironmentCI", ctx, kind)}
}

func (_c *Querier_EnvironmentCI_Call) Run(run func(ctx context.Context, kind types.EnvironmentKind)) *Querier_EnvironmentCI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.EnvironmentKind
		if args[1] != nil {
			arg1 = args[1].(types.EnvironmentKind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentCI_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentCI_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentCI_Call) RunAndReturn(run func(ctx context.Context, kind types.EnvironmentKind) (gensql.Environment, error)) *Querier_EnvironmentCI_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentCreate provides a mock function for the type Querier
func (_mock *Querier) EnvironmentCreate(ctx context.Context, arg gensql.EnvironmentCreateParams) (gensql.Environment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentCreate")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentCreateParams) (gensql.Environment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentCreateParams) gensql.Environment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentCreateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentCreate'
type Querier_EnvironmentCreate_Call struct {
	*mock.Call
}

// EnvironmentCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentCreateParams
func (_e *Querier_Expecter) EnvironmentCreate(ctx interface{}, arg interface{}) *Querier_EnvironmentCreate_Call {
	return &Querier_EnvironmentCreate_Call{Call: _e.mock.On("EnvironmentCreate", ctx, arg)}
}

func (_c *Querier_EnvironmentCreate_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentCreateParams)) *Querier_EnvironmentCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentCreateParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentCreateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentCreate_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentCreate_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentCreate_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentCreateParams) (gensql.Environment, error)) *Querier_EnvironmentCreate_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentGet provides a mock function for the type Querier
func (_mock *Querier) EnvironmentGet(ctx context.Context, id uuid.UUID) (gensql.Environment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentGet")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (gensql.Environment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.Environment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentGet'
type Querier_EnvironmentGet_Call struct {
	*mock.Call
}

// EnvironmentGet is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Querier_Expecter) EnvironmentGet(ctx interface{}, id interface{}) *Querier_EnvironmentGet_Call {
	return &Querier_EnvironmentGet_Call{Call: _e.mock.On("EnvironmentGet", ctx, id)}
}

func (_c *Querier_EnvironmentGet_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Querier_EnvironmentGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentGet_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentGet_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentGet_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (gensql.Environment, error)) *Querier_EnvironmentGet_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentGetByName provides a mock function for the type Querier
func (_mock *Querier) EnvironmentGetByName(ctx context.Context, arg gensql.EnvironmentGetByNameParams) (gensql.Environment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentGetByName")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentGetByNameParams) (gensql.Environment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentGetByNameParams) gensql.Environment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentGetByNameParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentGetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentGetByName'
type Querier_EnvironmentGetByName_Call struct {
	*mock.Call
}

// EnvironmentGetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentGetByNameParams
func (_e *Querier_Expecter) EnvironmentGetByName(ctx interface{}, arg interface{}) *Querier_EnvironmentGetByName_Call {
	return &Querier_EnvironmentGetByName_Call{Call: _e.mock.On("EnvironmentGetByName", ctx, arg)}
}

func (_c *Querier_EnvironmentGetByName_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentGetByNameParams)) *Querier_EnvironmentGetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentGetByNameParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentGetByNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentGetByName_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentGetByName_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentGetByName_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentGetByNameParams) (gensql.Environment, error)) *Querier_EnvironmentGetByName_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentGetLabels provides a mock function for the type Querier
func (_mock *Querier) EnvironmentGetLabels(ctx context.Context, id uuid.UUID) (types.EnvironmentLabels, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentGetLabels")
	}

	var r0 types.EnvironmentLabels
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (types.EnvironmentLabels, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) types.EnvironmentLabels); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.EnvironmentLabels)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentGetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentGetLabels'
type Querier_EnvironmentGetLabels_Call struct {
	*mock.Call
}

// EnvironmentGetLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Querier_Expecter) EnvironmentGetLabels(ctx interface{}, id interface{}) *Querier_EnvironmentGetLabels_Call {
	return &Querier_EnvironmentGetLabels_Call{Call: _e.mock.On("EnvironmentGetLabels", ctx, id)}
}

func (_c *Querier_EnvironmentGetLabels_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Querier_EnvironmentGetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentGetLabels_Call) Return(environmentLabels types.EnvironmentLabels, err error) *Querier_EnvironmentGetLabels_Call {
	_c.Call.Return(environmentLabels, err)
	return _c
}

func (_c *Querier_EnvironmentGetLabels_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (types.EnvironmentLabels, error)) *Querier_EnvironmentGetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentIDByNames provides a mock function for the type Querier
func (_mock *Querier) EnvironmentIDByNames(ctx context.Context, arg gensql.EnvironmentIDByNamesParams) (uuid.UUID, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentIDByNames")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentIDByNamesParams) (uuid.UUID, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentIDByNamesParams) uuid.UUID); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentIDByNamesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentIDByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentIDByNames'
type Querier_EnvironmentIDByNames_Call struct {
	*mock.Call
}

// EnvironmentIDByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentIDByNamesParams
func (_e *Querier_Expecter) EnvironmentIDByNames(ctx interface{}, arg interface{}) *Querier_EnvironmentIDByNames_Call {
	return &Querier_EnvironmentIDByNames_Call{Call: _e.mock.On("EnvironmentIDByNames", ctx, arg)}
}

func (_c *Querier_EnvironmentIDByNames_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentIDByNamesParams)) *Querier_EnvironmentIDByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentIDByNamesParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentIDByNamesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentIDByNames_Call) Return(uUID uuid.UUID, err error) *Querier_EnvironmentIDByNames_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Querier_EnvironmentIDByNames_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentIDByNamesParams) (uuid.UUID, error)) *Querier_EnvironmentIDByNames_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentSetLabels provides a mock function for the type Querier
func (_mock *Querier) EnvironmentSetLabels(ctx context.Context, arg gensql.EnvironmentSetLabelsParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentSetLabels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentSetLabelsParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_EnvironmentSetLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentSetLabels'
type Querier_EnvironmentSetLabels_Call struct {
	*mock.Call
}

// EnvironmentSetLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentSetLabelsParams
func (_e *Querier_Expecter) EnvironmentSetLabels(ctx interface{}, arg interface{}) *Querier_EnvironmentSetLabels_Call {
	return &Querier_EnvironmentSetLabels_Call{Call: _e.mock.On("EnvironmentSetLabels", ctx, arg)}
}

func (_c *Querier_EnvironmentSetLabels_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentSetLabelsParams)) *Querier_EnvironmentSetLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentSetLabelsParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentSetLabelsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentSetLabels_Call) Return(err error) *Querier_EnvironmentSetLabels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_EnvironmentSetLabels_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentSetLabelsParams) error) *Querier_EnvironmentSetLabels_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentSetReconcile provides a mock function for the type Querier
func (_mock *Querier) EnvironmentSetReconcile(ctx context.Context, arg gensql.EnvironmentSetReconcileParams) (gensql.Environment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentSetReconcile")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentSetReconcileParams) (gensql.Environment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentSetReconcileParams) gensql.Environment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentSetReconcileParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentSetReconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentSetReconcile'
type Querier_EnvironmentSetReconcile_Call struct {
	*mock.Call
}

// EnvironmentSetReconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentSetReconcileParams
func (_e *Querier_Expecter) EnvironmentSetReconcile(ctx interface{}, arg interface{}) *Querier_EnvironmentSetReconcile_Call {
	return &Querier_EnvironmentSetReconcile_Call{Call: _e.mock.On("EnvironmentSetReconcile", ctx, arg)}
}

func (_c *Querier_EnvironmentSetReconcile_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentSetReconcileParams)) *Querier_EnvironmentSetReconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentSetReconcileParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentSetReconcileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentSetReconcile_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentSetReconcile_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentSetReconcile_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentSetReconcileParams) (gensql.Environment, error)) *Querier_EnvironmentSetReconcile_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentUpdate provides a mock function for the type Querier
func (_mock *Querier) EnvironmentUpdate(ctx context.Context, arg gensql.EnvironmentUpdateParams) (gensql.Environment, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentUpdate")
	}

	var r0 gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentUpdateParams) (gensql.Environment, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentUpdateParams) gensql.Environment); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentUpdateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentUpdate'
type Querier_EnvironmentUpdate_Call struct {
	*mock.Call
}

// EnvironmentUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentUpdateParams
func (_e *Querier_Expecter) EnvironmentUpdate(ctx interface{}, arg interface{}) *Querier_EnvironmentUpdate_Call {
	return &Querier_EnvironmentUpdate_Call{Call: _e.mock.On("EnvironmentUpdate", ctx, arg)}
}

func (_c *Querier_EnvironmentUpdate_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentUpdateParams)) *Querier_EnvironmentUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentUpdateParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentUpdateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentUpdate_Call) Return(environment gensql.Environment, err error) *Querier_EnvironmentUpdate_Call {
	_c.Call.Return(environment, err)
	return _c
}

func (_c *Querier_EnvironmentUpdate_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentUpdateParams) (gensql.Environment, error)) *Querier_EnvironmentUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentValueDelete provides a mock function for the type Querier
func (_mock *Querier) EnvironmentValueDelete(ctx context.Context, arg gensql.EnvironmentValueDeleteParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentValueDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValueDeleteParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_EnvironmentValueDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentValueDelete'
type Querier_EnvironmentValueDelete_Call struct {
	*mock.Call
}

// EnvironmentValueDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentValueDeleteParams
func (_e *Querier_Expecter) EnvironmentValueDelete(ctx interface{}, arg interface{}) *Querier_EnvironmentValueDelete_Call {
	return &Querier_EnvironmentValueDelete_Call{Call: _e.mock.On("EnvironmentValueDelete", ctx, arg)}
}

func (_c *Querier_EnvironmentValueDelete_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentValueDeleteParams)) *Querier_EnvironmentValueDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentValueDeleteParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentValueDeleteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentValueDelete_Call) Return(err error) *Querier_EnvironmentValueDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_EnvironmentValueDelete_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentValueDeleteParams) error) *Querier_EnvironmentValueDelete_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentValueGet provides a mock function for the type Querier
func (_mock *Querier) EnvironmentValueGet(ctx context.Context, arg gensql.EnvironmentValueGetParams) (gensql.EnvironmentValueGetRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentValueGet")
	}

	var r0 gensql.EnvironmentValueGetRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValueGetParams) (gensql.EnvironmentValueGetRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValueGetParams) gensql.EnvironmentValueGetRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.EnvironmentValueGetRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentValueGetParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentValueGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentValueGet'
type Querier_EnvironmentValueGet_Call struct {
	*mock.Call
}

// EnvironmentValueGet is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentValueGetParams
func (_e *Querier_Expecter) EnvironmentValueGet(ctx interface{}, arg interface{}) *Querier_EnvironmentValueGet_Call {
	return &Querier_EnvironmentValueGet_Call{Call: _e.mock.On("EnvironmentValueGet", ctx, arg)}
}

func (_c *Querier_EnvironmentValueGet_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentValueGetParams)) *Querier_EnvironmentValueGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentValueGetParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentValueGetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentValueGet_Call) Return(environmentValueGetRow gensql.EnvironmentValueGetRow, err error) *Querier_EnvironmentValueGet_Call {
	_c.Call.Return(environmentValueGetRow, err)
	return _c
}

func (_c *Querier_EnvironmentValueGet_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentValueGetParams) (gensql.EnvironmentValueGetRow, error)) *Querier_EnvironmentValueGet_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentValueStore provides a mock function for the type Querier
func (_mock *Querier) EnvironmentValueStore(ctx context.Context, arg gensql.EnvironmentValueStoreParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentValueStore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValueStoreParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_EnvironmentValueStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentValueStore'
type Querier_EnvironmentValueStore_Call struct {
	*mock.Call
}

// EnvironmentValueStore is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentValueStoreParams
func (_e *Querier_Expecter) EnvironmentValueStore(ctx interface{}, arg interface{}) *Querier_EnvironmentValueStore_Call {
	return &Querier_EnvironmentValueStore_Call{Call: _e.mock.On("EnvironmentValueStore", ctx, arg)}
}

func (_c *Querier_EnvironmentValueStore_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentValueStoreParams)) *Querier_EnvironmentValueStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentValueStoreParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentValueStoreParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentValueStore_Call) Return(err error) *Querier_EnvironmentValueStore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_EnvironmentValueStore_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentValueStoreParams) error) *Querier_EnvironmentValueStore_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentValuesAcrossEnvs provides a mock function for the type Querier
func (_mock *Querier) EnvironmentValuesAcrossEnvs(ctx context.Context, key string) ([]gensql.EnvironmentValuesAcrossEnvsRow, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentValuesAcrossEnvs")
	}

	var r0 []gensql.EnvironmentValuesAcrossEnvsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]gensql.EnvironmentValuesAcrossEnvsRow, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []gensql.EnvironmentValuesAcrossEnvsRow); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.EnvironmentValuesAcrossEnvsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentValuesAcrossEnvs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentValuesAcrossEnvs'
type Querier_EnvironmentValuesAcrossEnvs_Call struct {
	*mock.Call
}

// EnvironmentValuesAcrossEnvs is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Querier_Expecter) EnvironmentValuesAcrossEnvs(ctx interface{}, key interface{}) *Querier_EnvironmentValuesAcrossEnvs_Call {
	return &Querier_EnvironmentValuesAcrossEnvs_Call{Call: _e.mock.On("EnvironmentValuesAcrossEnvs", ctx, key)}
}

func (_c *Querier_EnvironmentValuesAcrossEnvs_Call) Run(run func(ctx context.Context, key string)) *Querier_EnvironmentValuesAcrossEnvs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentValuesAcrossEnvs_Call) Return(environmentValuesAcrossEnvsRows []gensql.EnvironmentValuesAcrossEnvsRow, err error) *Querier_EnvironmentValuesAcrossEnvs_Call {
	_c.Call.Return(environmentValuesAcrossEnvsRows, err)
	return _c
}

func (_c *Querier_EnvironmentValuesAcrossEnvs_Call) RunAndReturn(run func(ctx context.Context, key string) ([]gensql.EnvironmentValuesAcrossEnvsRow, error)) *Querier_EnvironmentValuesAcrossEnvs_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentValuesForEnvironment provides a mock function for the type Querier
func (_mock *Querier) EnvironmentValuesForEnvironment(ctx context.Context, arg gensql.EnvironmentValuesForEnvironmentParams) ([]gensql.EnvironmentValuesForEnvironmentRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentValuesForEnvironment")
	}

	var r0 []gensql.EnvironmentValuesForEnvironmentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValuesForEnvironmentParams) ([]gensql.EnvironmentValuesForEnvironmentRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentValuesForEnvironmentParams) []gensql.EnvironmentValuesForEnvironmentRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.EnvironmentValuesForEnvironmentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentValuesForEnvironmentParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentValuesForEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentValuesForEnvironment'
type Querier_EnvironmentValuesForEnvironment_Call struct {
	*mock.Call
}

// EnvironmentValuesForEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.EnvironmentValuesForEnvironmentParams
func (_e *Querier_Expecter) EnvironmentValuesForEnvironment(ctx interface{}, arg interface{}) *Querier_EnvironmentValuesForEnvironment_Call {
	return &Querier_EnvironmentValuesForEnvironment_Call{Call: _e.mock.On("EnvironmentValuesForEnvironment", ctx, arg)}
}

func (_c *Querier_EnvironmentValuesForEnvironment_Call) Run(run func(ctx context.Context, arg gensql.EnvironmentValuesForEnvironmentParams)) *Querier_EnvironmentValuesForEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.EnvironmentValuesForEnvironmentParams
		if args[1] != nil {
			arg1 = args[1].(gensql.EnvironmentValuesForEnvironmentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentValuesForEnvironment_Call) Return(environmentValuesForEnvironmentRows []gensql.EnvironmentValuesForEnvironmentRow, err error) *Querier_EnvironmentValuesForEnvironment_Call {
	_c.Call.Return(environmentValuesForEnvironmentRows, err)
	return _c
}

func (_c *Querier_EnvironmentValuesForEnvironment_Call) RunAndReturn(run func(ctx context.Context, arg gensql.EnvironmentValuesForEnvironmentParams) ([]gensql.EnvironmentValuesForEnvironmentRow, error)) *Querier_EnvironmentValuesForEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// EnvironmentsGet provides a mock function for the type Querier
func (_mock *Querier) EnvironmentsGet(ctx context.Context, tenantID uuid.UUID) ([]gensql.Environment, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentsGet")
	}

	var r0 []gensql.Environment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]gensql.Environment, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.Environment); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.Environment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_EnvironmentsGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentsGet'
type Querier_EnvironmentsGet_Call struct {
	*mock.Call
}

// EnvironmentsGet is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *Querier_Expecter) EnvironmentsGet(ctx interface{}, tenantID interface{}) *Querier_EnvironmentsGet_Call {
	return &Querier_EnvironmentsGet_Call{Call: _e.mock.On("EnvironmentsGet", ctx, tenantID)}
}

func (_c *Querier_EnvironmentsGet_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *Querier_EnvironmentsGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_EnvironmentsGet_Call) Return(environments []gensql.Environment, err error) *Querier_EnvironmentsGet_Call {
	_c.Call.Return(environments, err)
	return _c
}

func (_c *Querier_EnvironmentsGet_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) ([]gensql.Environment, error)) *Querier_EnvironmentsGet_Call {
	_c.Call.Return(run)
	return _c
}

// MappingValuesForTenant provides a mock function for the type Querier
func (_mock *Querier) MappingValuesForTenant(ctx context.Context, arg gensql.MappingValuesForTenantParams) ([]gensql.MappingValuesForTenantRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MappingValuesForTenant")
	}

	var r0 []gensql.MappingValuesForTenantRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.MappingValuesForTenantParams) ([]gensql.MappingValuesForTenantRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.MappingValuesForTenantParams) []gensql.MappingValuesForTenantRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.MappingValuesForTenantRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.MappingValuesForTenantParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_MappingValuesForTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MappingValuesForTenant'
type Querier_MappingValuesForTenant_Call struct {
	*mock.Call
}

// MappingValuesForTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.MappingValuesForTenantParams
func (_e *Querier_Expecter) MappingValuesForTenant(ctx interface{}, arg interface{}) *Querier_MappingValuesForTenant_Call {
	return &Querier_MappingValuesForTenant_Call{Call: _e.mock.On("MappingValuesForTenant", ctx, arg)}
}

func (_c *Querier_MappingValuesForTenant_Call) Run(run func(ctx context.Context, arg gensql.MappingValuesForTenantParams)) *Querier_MappingValuesForTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.MappingValuesForTenantParams
		if args[1] != nil {
			arg1 = args[1].(gensql.MappingValuesForTenantParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_MappingValuesForTenant_Call) Return(mappingValuesForTenantRows []gensql.MappingValuesForTenantRow, err error) *Querier_MappingValuesForTenant_Call {
	_c.Call.Return(mappingValuesForTenantRows, err)
	return _c
}

func (_c *Querier_MappingValuesForTenant_Call) RunAndReturn(run func(ctx context.Context, arg gensql.MappingValuesForTenantParams) ([]gensql.MappingValuesForTenantRow, error)) *Querier_MappingValuesForTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NamesFromDeployInstruction provides a mock function for the type Querier
func (_mock *Querier) NamesFromDeployInstruction(ctx context.Context, id uuid.UUID) (gensql.NamesFromDeployInstructionRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for NamesFromDeployInstruction")
	}

	var r0 gensql.NamesFromDeployInstructionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (gensql.NamesFromDeployInstructionRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.NamesFromDeployInstructionRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(gensql.NamesFromDeployInstructionRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_NamesFromDeployInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamesFromDeployInstruction'
type Querier_NamesFromDeployInstruction_Call struct {
	*mock.Call
}

// NamesFromDeployInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Querier_Expecter) NamesFromDeployInstruction(ctx interface{}, id interface{}) *Querier_NamesFromDeployInstruction_Call {
	return &Querier_NamesFromDeployInstruction_Call{Call: _e.mock.On("NamesFromDeployInstruction", ctx, id)}
}

func (_c *Querier_NamesFromDeployInstruction_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Querier_NamesFromDeployInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_NamesFromDeployInstruction_Call) Return(namesFromDeployInstructionRow gensql.NamesFromDeployInstructionRow, err error) *Querier_NamesFromDeployInstruction_Call {
	_c.Call.Return(namesFromDeployInstructionRow, err)
	return _c
}

func (_c *Querier_NamesFromDeployInstruction_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (gensql.NamesFromDeployInstructionRow, error)) *Querier_NamesFromDeployInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseStatusCreateOrUpdate provides a mock function for the type Querier
func (_mock *Querier) ReleaseStatusCreateOrUpdate(ctx context.Context, arg gensql.ReleaseStatusCreateOrUpdateParams) (gensql.ReleaseStatus, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStatusCreateOrUpdate")
	}

	var r0 gensql.ReleaseStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.ReleaseStatusCreateOrUpdateParams) (gensql.ReleaseStatus, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gensql.ReleaseStatusCreateOrUpdateParams) gensql.ReleaseStatus); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.ReleaseStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gensql.ReleaseStatusCreateOrUpdateParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_ReleaseStatusCreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStatusCreateOrUpdate'
type Querier_ReleaseStatusCreateOrUpdate_Call struct {
	*mock.Call
}

// ReleaseStatusCreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - arg gensql.ReleaseStatusCreateOrUpdateParams
func (_e *Querier_Expecter) ReleaseStatusCreateOrUpdate(ctx interface{}, arg interface{}) *Querier_ReleaseStatusCreateOrUpdate_Call {
	return &Querier_ReleaseStatusCreateOrUpdate_Call{Call: _e.mock.On("ReleaseStatusCreateOrUpdate", ctx, arg)}
}

func (_c *Querier_ReleaseStatusCreateOrUpdate_Call) Run(run func(ctx context.Context, arg gensql.ReleaseStatusCreateOrUpdateParams)) *Querier_ReleaseStatusCreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gensql.ReleaseStatusCreateOrUpdateParams
		if args[1] != nil {
			arg1 = args[1].(gensql.ReleaseStatusCreateOrUpdateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_ReleaseStatusCreateOrUpdate_Call) Return(releaseStatus gensql.ReleaseStatus, err error) *Querier_ReleaseStatusCreateOrUpdate_Call {
	_c.Call.Return(releaseStatus, err)
	return _c
}

func (_c *Querier_ReleaseStatusCreateOrUpdate_Call) RunAndReturn(run func(ctx context.Context, arg gensql.ReleaseStatusCreateOrUpdateParams) (gensql.ReleaseStatus, error)) *Querier_ReleaseStatusCreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseStatusDeleteByEnvironment provides a mock function for the type Querier
func (_mock *Querier) ReleaseStatusDeleteByEnvironment(ctx context.Context, environmentID uuid.UUID) error {
	ret := _mock.Called(ctx, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStatusDeleteByEnvironment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, environmentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Querier_ReleaseStatusDeleteByEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStatusDeleteByEnvironment'
type Querier_ReleaseStatusDeleteByEnvironment_Call struct {
	*mock.Call
}

// ReleaseStatusDeleteByEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID uuid.UUID
func (_e *Querier_Expecter) ReleaseStatusDeleteByEnvironment(ctx interface{}, environmentID interface{}) *Querier_ReleaseStatusDeleteByEnvironment_Call {
	return &Querier_ReleaseStatusDeleteByEnvironment_Call{Call: _e.mock.On("ReleaseStatusDeleteByEnvironment", ctx, environmentID)}
}

func (_c *Querier_ReleaseStatusDeleteByEnvironment_Call) Run(run func(ctx context.Context, environmentID uuid.UUID)) *Querier_ReleaseStatusDeleteByEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_ReleaseStatusDeleteByEnvironment_Call) Return(err error) *Querier_ReleaseStatusDeleteByEnvironment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Querier_ReleaseStatusDeleteByEnvironment_Call) RunAndReturn(run func(ctx context.Context, environmentID uuid.UUID) error) *Querier_ReleaseStatusDeleteByEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseStatusesGet provides a mock function for the type Querier
func (_mock *Querier) ReleaseStatusesGet(ctx context.Context, environmentID uuid.UUID) ([]gensql.ReleaseStatus, error) {
	ret := _mock.Called(ctx, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStatusesGet")
	}

	var r0 []gensql.ReleaseStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]gensql.ReleaseStatus, error)); ok {
		return returnFunc(ctx, environmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.ReleaseStatus); ok {
		r0 = returnFunc(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.ReleaseStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Querier_ReleaseStatusesGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStatusesGet'
type Querier_ReleaseStatusesGet_Call struct {
	*mock.Call
}

// ReleaseStatusesGet is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentID uuid.UUID
func (_e *Querier_Expecter) ReleaseStatusesGet(ctx interface{}, environmentID interface{}) *Querier_ReleaseStatusesGet_Call {
	return &Querier_ReleaseStatusesGet_Call{Call: _e.mock.On("ReleaseStatusesGet", ctx, environmentID)}
}

func (_c *Querier_ReleaseStatusesGet_Call) Run(run func(ctx context.Context, environmentID uuid.UUID)) *Querier_ReleaseStatusesGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Querier_ReleaseStatusesGet_Call) Return(releaseStatuss []gensql.ReleaseStatus, err error) *Querier_ReleaseStatusesGet_Call {
	_c.Call.Return(releaseStatuss, err)
	return _c
}

func (_c *Querier_ReleaseStatusesGet_Call) RunAndReturn(run func(ctx context.Context, environmentID uuid.UUID) ([]gensql.ReleaseStatus, error)) *Querier_ReleaseStatusesGet_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type Querier
func (_mock *Querier) WithTx(tx pgx.Tx) *gensql.Queries {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 *gensql.Queries
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx) *gensql.Queries); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gensql.Queries)
		}
	}
	return r0
}

// Querier_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Querier_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *Querier_Expecter) WithTx(tx interface{}) *Querier_WithTx_Call {
	return &Querier_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *Querier_WithTx_Call) Run(run func(tx pgx.Tx)) *Querier_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Querier_WithTx_Call) Return(queries *gensql.Queries) *Querier_WithTx_Call {
	_c.Call.Return(queries)
	return _c
}

func (_c *Querier_WithTx_Call) RunAndReturn(run func(tx pgx.Tx) *gensql.Queries) *Querier_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
