apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "naisd.fullname" . }}
  labels:
    {{- include "naisd.labels" . | nindent 4 }}
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "naisd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "naisd.selectorLabels" . | nindent 8 }}
        tenant: {{ .Values.tenantName }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 1800
      serviceAccountName: {{ include "naisd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAIS_SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          {{ if .Values.no_proxy }}
            - name: NO_PROXY
              value: {{ .Values.no_proxy }}
          {{ end }}
          {{ if .Values.https_proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.https_proxy }}
          {{ end }}
          {{ if .Values.google.useServiceAccountKey }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/google/key.json
          {{ end }}
          args:
            - --production
            - --tenant-name
            - {{ .Values.tenantName }}
            - --env
            - {{ .Values.env }}
            - --env-project-id
            - {{ .Values.envProjectId }}
            - --nais-project-id
            - {{ .Values.naisProjectId }}
            - --deploy-subscription
            - {{ .Values.deploySubscription }}
            - --management={{ .Values.management }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http

          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /.kube
            name: kubeconfig
          {{ if .Values.google.useServiceAccountKey }}
          - mountPath: /var/run/secrets/google
            name: google-service-account
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
      - name: tmp
        emptyDir: {}
      - name: kubeconfig
        emptyDir: {}
      {{ if .Values.google.useServiceAccountKey }}
      - name: google-service-account
        secret:
          secretName: {{ .Release.Name }}-google-sa-key
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
