CREATE TABLE `Values` (
	ValueID BYTES(16),
	PartnerID BYTES(16),
	EnvID BYTES(16),
	Feature STRING(40) NOT NULL,
	KEY STRING(128) NOT NULL,
	Value JSON NOT NULL,
	Description STRING(1024),
	Secret BOOL NOT NULL,
	Deleted BOOL NOT NULL,
	Created TIMESTAMP NOT NULL,
	LastModified TIMESTAMP NOT NULL
) PRIMARY KEY (PartnerID, EnvID, ValueID),
INTERLEAVE IN PARENT Envs ON DELETE CASCADE
