CREATE TABLE Envs (
	EnvID BYTES(16),
	PartnerID BYTES(16),
	Name STRING(40) NOT NULL,
	Description STRING(1024),
	Created TIMESTAMP NOT NULL,
	LastModified TIMESTAMP NOT NULL,
) PRIMARY KEY (PartnerID, EnvID),
INTERLEAVE IN PARENT Partners ON DELETE CASCADE
