version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@nais/core-dependabot-reviewers"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@nais/core-dependabot-reviewers"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "@nais/core-dependabot-reviewers"
    ignore:
      # We need to ignore oras-go until helm is upgraded
      - dependency-name: "oras.land/oras-go"
        versions:
          - "v2"
    groups:
      gomod:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io*"
      k8s:
        patterns:
          - "k8s.io*"
