version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gomod:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io*"
      k8s:
        patterns:
          - "k8s.io*"
