pkgname: mocks
dir: "{{ .InterfaceDir }}/mocks"
filename: "{{ .InterfaceName | snakecase }}.go"
structname: "{{ .InterfaceName }}"
template: testify
packages:
  github.com/nais/fasit/internal/database:
    config:
      all: true
      dir: internal/database/mocks
  github.com/nais/fasit/internal/cluster:
    interfaces:
      ClusterManager:
        config:
          dir: internal/cluster/mocks
