FROM node:18-alpine AS node-with-deps

WORKDIR /usr/app

COPY frontend/package*.json .

# Revert this once react-tag-autocomplete supports React 18
RUN npm install --legacy-peer-deps --quiet
#RUN npm install --quiet

FROM node-with-deps

COPY frontend .

ENV NODE_ENV production
ENV NEXT_PUBLIC_ENV production
ENV NEXT_PUBLIC_BACKEND http://fasit/api

RUN npm run build

CMD npm run start
