version: '3.1'

services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: fasit
  #   command: ["postgres", "-c", "log_statement=all"]
  #   ports:
  #     - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: always
    ports:
      - 9010:9010
      - 9020:9020

  pubsub:
    image: google/cloud-sdk
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
