ARG GO_VERSION=1.26

FROM golang:${GO_VERSION} AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . /workspace

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -o naisd ./cmd/naisd

FROM alpine
WORKDIR /

RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community helm

COPY --from=builder /workspace/naisd .
USER 65532:65532

ENTRYPOINT ["/naisd"]
