services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fasit
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
  pubsub:
    image: google/cloud-sdk
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:8085
    ports:
      - 8086:8085
volumes:
  db-data:
