ARG GO_VERSION=1.26

FROM golang:${GO_VERSION} AS builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . /workspace

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -o oidcproxy ./cmd/oidcproxy

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /

COPY --from=builder /workspace/oidcproxy /usr/local/bin/oidcproxy

ENTRYPOINT ["/usr/local/bin/oidcproxy"]
