FROM cgr.dev/chainguard/go:1.20 as builder

WORKDIR /workspace
COPY go.* ./
RUN go version
RUN go mod download

COPY . /workspace

# Build
RUN CGO_ENABLED=0 go build -a -o fasit ./cmd/fasit

FROM cgr.dev/chainguard/static
WORKDIR /

COPY --from=builder /workspace/fasit .
USER 65532:65532

ENTRYPOINT ["/fasit"]
