FROM node:16-alpine AS node-with-deps

WORKDIR /usr/app

COPY frontend/package*.json .

RUN npm install --legacy-peer-deps --quiet

FROM node-with-deps

COPY frontend .

ENV NODE_ENV production
ENV NEXT_PUBLIC_ENV production
ENV NEXT_PUBLIC_BACKEND http://fasit/api

RUN npm run build

CMD npm run start
