ARG GO_VERSION=1.24

FROM golang:${GO_VERSION} as builder

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . /workspace

# Build
RUN CGO_ENABLED=0 go build -a -o naisd ./cmd/naisd

FROM alpine
WORKDIR /

RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community helm

COPY --from=builder /workspace/naisd .
USER 65532:65532

ENTRYPOINT ["/naisd"]
