FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY ./frontend .

# Revert this once react-tag-autocomplete supports React 18
RUN npm install --legacy-peer-deps --quiet
RUN npm run build

FROM cgr.dev/chainguard/node:19

ENV NODE_ENV production
ENV NEXT_PUBLIC_ENV production
ENV NEXT_PUBLIC_BACKEND http://fasit/api

WORKDIR /app
COPY --from=builder --chown=node:node /usr/src/app/.next/standalone ./
COPY --from=builder --chown=node:node /usr/src/app/public ./public/
COPY --from=builder --chown=node:node /usr/src/app/.next/static ./.next/static

EXPOSE 3000

CMD ["server.js"]
