ARG GO_VERSION=1.24

FROM golang:${GO_VERSION} as builder

WORKDIR /workspace
COPY go.* ./
RUN go version
RUN go mod download

COPY . /workspace

# Build
RUN CGO_ENABLED=0 go build -a -o fasit ./cmd/fasit

FROM gcr.io/distroless/base:nonroot
WORKDIR /

COPY --from=builder /workspace/fasit .
USER 65532:65532

ENTRYPOINT ["/fasit"]
