// Code generated by sqlc. DO NOT EDIT.
// source: environments.sql

package environmentsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

const get = `-- name: Get :one
SELECT
	id, tenant_id, name, kind, description, created, last_modified, ci, reconcile, auto_upgrade, upgrade_delay_days, maintenance_window, labels
FROM
	environments
WHERE
	id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
		&i.Reconcile,
		&i.AutoUpgrade,
		&i.UpgradeDelayDays,
		&i.MaintenanceWindow,
		&i.Labels,
	)
	return i, err
}

const getLabels = `-- name: GetLabels :one
SELECT
	labels
FROM
	environments
WHERE
	id = $1
`

func (q *Queries) GetLabels(ctx context.Context, id uuid.UUID) (types.EnvironmentLabels, error) {
	row := q.db.QueryRow(ctx, getLabels, id)
	var labels types.EnvironmentLabels
	err := row.Scan(&labels)
	return labels, err
}

const listCIEnvironmentsForTarget = `-- name: ListCIEnvironmentsForTarget :many
SELECT DISTINCT
	e_ci.id, e_ci.tenant_id, e_ci.name, e_ci.kind, e_ci.description, e_ci.created, e_ci.last_modified, e_ci.ci, e_ci.reconcile, e_ci.auto_upgrade, e_ci.upgrade_delay_days, e_ci.maintenance_window, e_ci.labels,
	t.name AS tenant_name
FROM
	environments e_ci
	JOIN tenants t ON e_ci.tenant_id = t.id
WHERE
	e_ci.ci = TRUE
	AND EXISTS (
		SELECT
			1
		FROM
			environments e_non_ci
		WHERE
			e_non_ci.ci = FALSE
			AND e_non_ci.labels @> $1
			AND e_non_ci.kind = e_ci.kind)
ORDER BY
	e_ci.name ASC
`

type ListCIEnvironmentsForTargetRow struct {
	Environment Environment
	TenantName  string
}

func (q *Queries) ListCIEnvironmentsForTarget(ctx context.Context, target types.EnvironmentLabels) ([]ListCIEnvironmentsForTargetRow, error) {
	rows, err := q.db.Query(ctx, listCIEnvironmentsForTarget, target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCIEnvironmentsForTargetRow{}
	for rows.Next() {
		var i ListCIEnvironmentsForTargetRow
		if err := rows.Scan(
			&i.Environment.ID,
			&i.Environment.TenantID,
			&i.Environment.Name,
			&i.Environment.Kind,
			&i.Environment.Description,
			&i.Environment.Created,
			&i.Environment.LastModified,
			&i.Environment.Ci,
			&i.Environment.Reconcile,
			&i.Environment.AutoUpgrade,
			&i.Environment.UpgradeDelayDays,
			&i.Environment.MaintenanceWindow,
			&i.Environment.Labels,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
