// Code generated by sqlc. DO NOT EDIT.
// source: environment_values.sql

package environmentsql

import (
	"context"

	"github.com/google/uuid"
)

const setEnvironmentValue = `-- name: SetEnvironmentValue :exec
INSERT INTO environment_values(
	"environment_id",
	"key",
	"value",
	"secret")
VALUES (
	$1,
	$2,
	$3,
	$4)
ON CONFLICT (
	"environment_id",
	"key")
	DO UPDATE SET
		"value" = $3,
		"secret" = $4
`

type SetEnvironmentValueParams struct {
	Envid  uuid.UUID
	Key    string
	Value  []byte
	Secret bool
}

func (q *Queries) SetEnvironmentValue(ctx context.Context, arg SetEnvironmentValueParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentValue,
		arg.Envid,
		arg.Key,
		arg.Value,
		arg.Secret,
	)
	return err
}
