// Code generated by sqlc. DO NOT EDIT.

package environmentsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type Querier interface {
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteEnvironmentValue(ctx context.Context, arg DeleteEnvironmentValueParams) error
	GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error)
	GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error)
	GetEnvironmentLabels(ctx context.Context, id uuid.UUID) (types.EnvironmentLabels, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	ListEnvironmentValuesForEnvironment(ctx context.Context, arg ListEnvironmentValuesForEnvironmentParams) ([]ListEnvironmentValuesForEnvironmentRow, error)
	ListEnvironments(ctx context.Context, tenantID uuid.UUID) ([]Environment, error)
	ListTenantEnvironments(ctx context.Context, all bool) ([]ListTenantEnvironmentsRow, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	SetEnvironmentLabels(ctx context.Context, arg SetEnvironmentLabelsParams) error
	SetEnvironmentValue(ctx context.Context, arg SetEnvironmentValueParams) error
}

var _ Querier = (*Queries)(nil)
