// Code generated by sqlc. DO NOT EDIT.

package environmentsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (Environment, error)
	Get(ctx context.Context, id uuid.UUID) (Environment, error)
	GetLabels(ctx context.Context, id uuid.UUID) (types.EnvironmentLabels, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetTenants(ctx context.Context) ([]Tenant, error)
	SetEnvironmentValue(ctx context.Context, arg SetEnvironmentValueParams) error
	SetLabels(ctx context.Context, arg SetLabelsParams) error
	TenantCreate(ctx context.Context, arg TenantCreateParams) (Tenant, error)
	TenantEnvironments(ctx context.Context, all bool) ([]TenantEnvironmentsRow, error)
	Warnings(ctx context.Context, arg WarningsParams) ([]WarningsRow, error)
}

var _ Querier = (*Queries)(nil)
