[settings]
pin = true

[tools]
go = "1.25.5"
protoc = "33.0"
protoc-gen-go = "1.36.10"
protoc-gen-go-grpc = "1.5.1"
helm = "3.19.0"
buf = "1.59.0"
"github:CppCXY/EmmyLuaCodeStyle" = "1.5.6"
jq = "1.8.1"
yq = "4.50.1"
"http:pgformatter"= { version = "5.9", "].tag_name" = "", url = "https://github.com/darold/pgFormatter/archive/refs/tags/v{version}.tar.gz", strip_components = "1", version_list_url = "https://api.github.com/repos/darold/pgFormatter/releases", version_json_path = ".[].tag_name" }
