// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package restapisql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeployment = `-- name: GetDeployment :one
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	deployments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.id = $1
`

type GetDeploymentRow struct {
	Deployment   Deployment
	FeatureDatum FeatureDatum
}

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (GetDeploymentRow, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i GetDeploymentRow
	err := row.Scan(
		&i.Deployment.ID,
		&i.Deployment.FeatureName,
		&i.Deployment.Version,
		&i.Deployment.Target,
		&i.Deployment.Created,
		&i.Deployment.GhRef,
		&i.Deployment.Description,
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
	)
	return i, err
}

const listDeploymentStatuses = `-- name: ListDeploymentStatuses :many
WITH statuses AS (
	SELECT
		deployment_id,
		environment_id,
		status,
		message,
		last_modified,
		created
	FROM
		deployment_statuses
	WHERE
		deployment_id = $1
),
disabled AS (
	SELECT
		d.id AS deployment_id,
		e.id AS environment_id,
		'DISABLED' AS status,
		'feature is disabled in this environment' AS message,
		df.disabled_at AS last_modified,
		df.disabled_at AS created
	FROM
		environments e
		JOIN disabled_features df ON df.environment_id = e.id
		JOIN deployments d ON df.feature = d.feature_name
	WHERE
		e.labels @> d.target -- @> operator checks if the JSONB on the left contains the JSONB on the right
		AND d.id = $1
),
computed AS (
	SELECT
		deployment_id, environment_id, status, message, last_modified, created
	FROM
		statuses
	UNION
	SELECT
		deployment_id, environment_id, status, message, last_modified, created
	FROM
		disabled
)
SELECT
	deployment_id, environment_id, status, message, last_modified, created
FROM
	computed
ORDER BY
	last_modified DESC,
	environment_id ASC
`

type ListDeploymentStatusesRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	Status        string
	Message       string
	LastModified  pgtype.Timestamptz
	Created       pgtype.Timestamptz
}

func (q *Queries) ListDeploymentStatuses(ctx context.Context, deploymentID uuid.UUID) ([]ListDeploymentStatusesRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentStatuses, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentStatusesRow{}
	for rows.Next() {
		var i ListDeploymentStatusesRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.EnvironmentID,
			&i.Status,
			&i.Message,
			&i.LastModified,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
