// Code generated by sqlc. DO NOT EDIT.
// source: deployment.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nais/fasit/internal/environment"
)

const deployInstructionsGetDeployedFeatures = `-- name: DeployInstructionsGetDeployedFeatures :many
SELECT DISTINCT ON (feature_name)
	feature_name
FROM
	deploy_instructions
WHERE
	feature_name = ANY ($1::TEXT[])
	AND status = 'deployed'
	AND environment_id = $2
ORDER BY
	feature_name
`

type DeployInstructionsGetDeployedFeaturesParams struct {
	FeatureNames  []string
	EnvironmentID uuid.UUID
}

func (q *Queries) DeployInstructionsGetDeployedFeatures(ctx context.Context, arg DeployInstructionsGetDeployedFeaturesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deployInstructionsGetDeployedFeatures, arg.FeatureNames, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var feature_name string
		if err := rows.Scan(&feature_name); err != nil {
			return nil, err
		}
		items = append(items, feature_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentCreate = `-- name: DeploymentCreate :one
INSERT INTO deployments(
	feature_name,
	version,
	target,
	gh_ref)
VALUES (
	$1,
	$2,
	$3,
	$4)
RETURNING
	id, feature_name, version, target, created, gh_ref
`

type DeploymentCreateParams struct {
	FeatureName string
	Version     string
	Target      environment.Labels
	GhRef       []byte
}

func (q *Queries) DeploymentCreate(ctx context.Context, arg DeploymentCreateParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentCreate,
		arg.FeatureName,
		arg.Version,
		arg.Target,
		arg.GhRef,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Target,
		&i.Created,
		&i.GhRef,
	)
	return i, err
}

const deploymentDelete = `-- name: DeploymentDelete :exec
DELETE FROM deployments
WHERE id = $1
`

func (q *Queries) DeploymentDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deploymentDelete, id)
	return err
}

const deploymentGet = `-- name: DeploymentGet :one
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref,
	fd.name,
	fd.version,
	fd.chart,
	fd.description,
	fd.source,
	fd.kinds::TEXT[] AS kinds,
	fd.dependencies,
	fd.values,
	fd.default_values,
	fd.timeout
FROM
	deployments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.id = $1
`

type DeploymentGetRow struct {
	Deployment    Deployment
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
}

func (q *Queries) DeploymentGet(ctx context.Context, id uuid.UUID) (DeploymentGetRow, error) {
	row := q.db.QueryRow(ctx, deploymentGet, id)
	var i DeploymentGetRow
	err := row.Scan(
		&i.Deployment.ID,
		&i.Deployment.FeatureName,
		&i.Deployment.Version,
		&i.Deployment.Target,
		&i.Deployment.Created,
		&i.Deployment.GhRef,
		&i.Name,
		&i.Version,
		&i.Chart,
		&i.Description,
		&i.Source,
		&i.Kinds,
		&i.Dependencies,
		&i.Values,
		&i.DefaultValues,
		&i.Timeout,
	)
	return i, err
}

const deploymentStatusCreateOrUpdate = `-- name: DeploymentStatusCreateOrUpdate :exec
INSERT INTO deployment_statuses(
	deployment_id,
	environment_id,
	status,
	message)
VALUES (
	$1,
	$2,
	$3,
	$4)
ON CONFLICT (
	deployment_id,
	environment_id)
	DO UPDATE SET
		status = EXCLUDED.status,
		message = EXCLUDED.message
`

type DeploymentStatusCreateOrUpdateParams struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	Status        string
	Message       string
}

func (q *Queries) DeploymentStatusCreateOrUpdate(ctx context.Context, arg DeploymentStatusCreateOrUpdateParams) error {
	_, err := q.db.Exec(ctx, deploymentStatusCreateOrUpdate,
		arg.DeploymentID,
		arg.EnvironmentID,
		arg.Status,
		arg.Message,
	)
	return err
}

const deploymentStatusGet = `-- name: DeploymentStatusGet :many
SELECT
	deployment_id, environment_id, status, message, last_modified, created
FROM
	deployment_statuses
WHERE
	deployment_id = $1
ORDER BY
	environment_id ASC
`

func (q *Queries) DeploymentStatusGet(ctx context.Context, deploymentID uuid.UUID) ([]DeploymentStatus, error) {
	rows, err := q.db.Query(ctx, deploymentStatusGet, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentStatus{}
	for rows.Next() {
		var i DeploymentStatus
		if err := rows.Scan(
			&i.DeploymentID,
			&i.EnvironmentID,
			&i.Status,
			&i.Message,
			&i.LastModified,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentsGet = `-- name: DeploymentsGet :many
SELECT
	id, feature_name, version, target, created, gh_ref
FROM
	deployments
ORDER BY
	created ASC
`

func (q *Queries) DeploymentsGet(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, deploymentsGet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.FeatureName,
			&i.Version,
			&i.Target,
			&i.Created,
			&i.GhRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deploymentsGetByFeature = `-- name: DeploymentsGetByFeature :many
SELECT
	id, feature_name, version, target, created, gh_ref
FROM
	deployments
WHERE
	feature_name = $1
ORDER BY
	created ASC
`

func (q *Queries) DeploymentsGetByFeature(ctx context.Context, featureName string) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, deploymentsGetByFeature, featureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.FeatureName,
			&i.Version,
			&i.Target,
			&i.Created,
			&i.GhRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const featureDeploymentsForEnvironment = `-- name: FeatureDeploymentsForEnvironment :many
SELECT DISTINCT ON (d.feature_name, d.target)
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref,
	fd.name,
	fd.version,
	fd.chart,
	fd.description,
	fd.source,
	fd.kinds::TEXT[] AS kinds,
	fd.dependencies,
	fd.values,
	fd.default_values,
	fd.timeout,
	ds.status,
	ds.message AS status_message,
	ds.last_modified AS status_last_modified,
	ds.created AS status_created
FROM
	deployments d
	JOIN environments e ON e.id = $1
		AND e.labels @> d.target -- @> operator checks if the JSONB on the left contains the JSONB on the right
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
	LEFT JOIN deployment_statuses ds ON ds.deployment_id = d.id
		AND ds.environment_id = $1
	ORDER BY
		d.feature_name,
		d.target,
		d.created DESC
`

type FeatureDeploymentsForEnvironmentRow struct {
	Deployment         Deployment
	Name               string
	Version            string
	Chart              string
	Description        string
	Source             string
	Kinds              []string
	Dependencies       []byte
	Values             []byte
	DefaultValues      []byte
	Timeout            int64
	Status             pgtype.Text
	StatusMessage      pgtype.Text
	StatusLastModified pgtype.Timestamptz
	StatusCreated      pgtype.Timestamptz
}

func (q *Queries) FeatureDeploymentsForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]FeatureDeploymentsForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, featureDeploymentsForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureDeploymentsForEnvironmentRow{}
	for rows.Next() {
		var i FeatureDeploymentsForEnvironmentRow
		if err := rows.Scan(
			&i.Deployment.ID,
			&i.Deployment.FeatureName,
			&i.Deployment.Version,
			&i.Deployment.Target,
			&i.Deployment.Created,
			&i.Deployment.GhRef,
			&i.Name,
			&i.Version,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.DefaultValues,
			&i.Timeout,
			&i.Status,
			&i.StatusMessage,
			&i.StatusLastModified,
			&i.StatusCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const featureEnabled = `-- name: FeatureEnabled :one
SELECT
	NOT EXISTS (
		SELECT
			environment_id, feature, enabled, created, last_modified, enabled_at
		FROM
			feature_states fs
		WHERE
			fs.feature = $1
			AND fs.environment_id = $2
			AND fs.enabled = FALSE)
`

type FeatureEnabledParams struct {
	FeatureName   string
	EnvironmentID uuid.UUID
}

func (q *Queries) FeatureEnabled(ctx context.Context, arg FeatureEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, featureEnabled, arg.FeatureName, arg.EnvironmentID)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}
