// Code generated by sqlc. DO NOT EDIT.
// source: rollout.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const rolloutAssignDeployInstruction = `-- name: RolloutAssignDeployInstruction :exec
UPDATE
	rollouts
SET
	deploy_instructions = ARRAY_APPEND(deploy_instructions, $1)
WHERE
	feature_name = $2
	AND version = $3
	AND status = 'pending'
`

type RolloutAssignDeployInstructionParams struct {
	DeployInstructionID interface{}
	FeatureName         string
	Version             string
}

func (q *Queries) RolloutAssignDeployInstruction(ctx context.Context, arg RolloutAssignDeployInstructionParams) error {
	_, err := q.db.Exec(ctx, rolloutAssignDeployInstruction, arg.DeployInstructionID, arg.FeatureName, arg.Version)
	return err
}

const rolloutByID = `-- name: RolloutByID :one
SELECT
	id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
FROM
	rollouts
WHERE
	id = $1
`

func (q *Queries) RolloutByID(ctx context.Context, id uuid.UUID) (Rollout, error) {
	row := q.db.QueryRow(ctx, rolloutByID, id)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Status,
		&i.Created,
		&i.Completed,
		&i.GhRef,
		&i.DeployInstructions,
	)
	return i, err
}

const rolloutByNameAndVersion = `-- name: RolloutByNameAndVersion :one
SELECT
	id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
FROM
	rollouts
WHERE
	feature_name = $1
	AND version = $2
`

type RolloutByNameAndVersionParams struct {
	FeatureName string
	Version     string
}

func (q *Queries) RolloutByNameAndVersion(ctx context.Context, arg RolloutByNameAndVersionParams) (Rollout, error) {
	row := q.db.QueryRow(ctx, rolloutByNameAndVersion, arg.FeatureName, arg.Version)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Status,
		&i.Created,
		&i.Completed,
		&i.GhRef,
		&i.DeployInstructions,
	)
	return i, err
}

const rolloutCalculateDone = `-- name: RolloutCalculateDone :one
WITH rollout AS (
	SELECT
		id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
	FROM
		rollouts
	WHERE
		rollouts.id = $1
),
dis AS (
	SELECT
		di.id, di.environment_id, di.feature_name, di.feature_version, di.status, di.hash, di.created, di.last_modified, di.values, di.deployment_id
	FROM
		deploy_instructions di
		INNER JOIN rollout ON di.feature_name = rollout.feature_name
			AND di.feature_version = rollout.version
	WHERE
		di.status IN ('deployed', 'failed')
),
cienvs AS (
	SELECT
		id
	FROM
		environments
	WHERE
		ci = TRUE
),
feature_states AS (
	SELECT
		COUNT(1)
	FROM
		feature_states
	WHERE
		feature =(
			SELECT
				feature_name
			FROM
				rollout)
			AND environment_id IN (
				SELECT
					id
				FROM
					cienvs)
				AND enabled = TRUE
)
	SELECT
		(
			SELECT
				COUNT(1)
			FROM
				dis) =(
		SELECT
			count
		FROM
			feature_states) AS done
`

func (q *Queries) RolloutCalculateDone(ctx context.Context, rolloutID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, rolloutCalculateDone, rolloutID)
	var done bool
	err := row.Scan(&done)
	return done, err
}

const rolloutComplete = `-- name: RolloutComplete :exec
UPDATE
	rollouts
SET
	completed = NOW()
WHERE
	feature_name = $1
	AND completed IS NULL
`

func (q *Queries) RolloutComplete(ctx context.Context, featureName string) error {
	_, err := q.db.Exec(ctx, rolloutComplete, featureName)
	return err
}

const rolloutCreate = `-- name: RolloutCreate :one
INSERT INTO rollouts(
	feature_name,
	version,
	gh_ref)
VALUES (
	$1,
	$2,
	$3)
RETURNING
	id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
`

type RolloutCreateParams struct {
	FeatureName string
	Version     string
	GhRef       []byte
}

func (q *Queries) RolloutCreate(ctx context.Context, arg RolloutCreateParams) (Rollout, error) {
	row := q.db.QueryRow(ctx, rolloutCreate, arg.FeatureName, arg.Version, arg.GhRef)
	var i Rollout
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Status,
		&i.Created,
		&i.Completed,
		&i.GhRef,
		&i.DeployInstructions,
	)
	return i, err
}

const rolloutDelete = `-- name: RolloutDelete :exec
DELETE FROM rollouts
WHERE feature_name = $1
`

func (q *Queries) RolloutDelete(ctx context.Context, featureName string) error {
	_, err := q.db.Exec(ctx, rolloutDelete, featureName)
	return err
}

const rolloutEventCreate = `-- name: RolloutEventCreate :exec
INSERT INTO rollout_events(
	rollout_id,
	failure,
	message,
	data)
VALUES (
	$1,
	$2::BOOLEAN,
	$3,
	$4)
`

type RolloutEventCreateParams struct {
	RolloutID uuid.UUID
	Failure   bool
	Message   string
	Data      []byte
}

func (q *Queries) RolloutEventCreate(ctx context.Context, arg RolloutEventCreateParams) error {
	_, err := q.db.Exec(ctx, rolloutEventCreate,
		arg.RolloutID,
		arg.Failure,
		arg.Message,
		arg.Data,
	)
	return err
}

const rolloutEventForRollout = `-- name: RolloutEventForRollout :many
SELECT
	id, rollout_id, failure, message, data, created
FROM
	rollout_events
WHERE
	rollout_id = $1
ORDER BY
	created ASC
`

func (q *Queries) RolloutEventForRollout(ctx context.Context, rolloutID uuid.UUID) ([]RolloutEvent, error) {
	rows, err := q.db.Query(ctx, rolloutEventForRollout, rolloutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolloutEvent{}
	for rows.Next() {
		var i RolloutEvent
		if err := rows.Scan(
			&i.ID,
			&i.RolloutID,
			&i.Failure,
			&i.Message,
			&i.Data,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolloutMarkFailed = `-- name: RolloutMarkFailed :execrows
UPDATE
	rollouts
SET
	status = 'failed',
	completed = NOW()
WHERE
	id = $1
	AND status NOT IN ('deployed', 'failed')
`

func (q *Queries) RolloutMarkFailed(ctx context.Context, rolloutID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rolloutMarkFailed, rolloutID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rolloutStatus = `-- name: RolloutStatus :one
SELECT
	status
FROM
	rollouts
WHERE
	feature_name = $1
	AND completed IS NULL
`

func (q *Queries) RolloutStatus(ctx context.Context, featureName string) (string, error) {
	row := q.db.QueryRow(ctx, rolloutStatus, featureName)
	var status string
	err := row.Scan(&status)
	return status, err
}

const rolloutUpdateStatus = `-- name: RolloutUpdateStatus :exec
UPDATE
	rollouts
SET
	status = $1
WHERE
	feature_name = $2
	AND completed IS NULL
`

type RolloutUpdateStatusParams struct {
	Status      string
	FeatureName string
}

func (q *Queries) RolloutUpdateStatus(ctx context.Context, arg RolloutUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, rolloutUpdateStatus, arg.Status, arg.FeatureName)
	return err
}

const rollouts = `-- name: Rollouts :many
SELECT
	id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
FROM
	rollouts
ORDER BY
	created DESC
LIMIT $1
`

func (q *Queries) Rollouts(ctx context.Context, limit int32) ([]Rollout, error) {
	rows, err := q.db.Query(ctx, rollouts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rollout{}
	for rows.Next() {
		var i Rollout
		if err := rows.Scan(
			&i.ID,
			&i.FeatureName,
			&i.Version,
			&i.Status,
			&i.Created,
			&i.Completed,
			&i.GhRef,
			&i.DeployInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolloutsForFeature = `-- name: RolloutsForFeature :many
SELECT
	id, feature_name, version, status, created, completed, gh_ref, deploy_instructions
FROM
	rollouts
WHERE
	feature_name = $1
ORDER BY
	created DESC
LIMIT 30
`

func (q *Queries) RolloutsForFeature(ctx context.Context, featureName string) ([]Rollout, error) {
	rows, err := q.db.Query(ctx, rolloutsForFeature, featureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rollout{}
	for rows.Next() {
		var i Rollout
		if err := rows.Scan(
			&i.ID,
			&i.FeatureName,
			&i.Version,
			&i.Status,
			&i.Created,
			&i.Completed,
			&i.GhRef,
			&i.DeployInstructions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolloutsForKind = `-- name: RolloutsForKind :many
WITH success AS (
	SELECT DISTINCT ON (rollouts.feature_name)
		id,
		feature_name
	FROM
		rollouts
		JOIN feature_data fd ON rollouts.feature_name = fd.name
			AND rollouts.version = fd.version
	WHERE
		$1::environment_kind = ANY (kinds)
		AND (rollouts.status IN ('pending', 'in_progress', 'deployed'))
	ORDER BY
		rollouts.feature_name,
		rollouts.created DESC
),
failed AS (
	SELECT DISTINCT ON (rollouts.feature_name)
		rollouts.id
	FROM
		rollouts
		LEFT OUTER JOIN success ON success.feature_name = rollouts.feature_name
	JOIN feature_data fd ON rollouts.feature_name = fd.name
		AND rollouts.version = fd.version
	WHERE
		success.id IS NULL
		AND $1::environment_kind = ANY (kinds)
		AND (rollouts.status IN ('failed'))
	ORDER BY
		rollouts.feature_name,
		rollouts.created DESC
),
all_rollouts AS (
	SELECT
		id
	FROM
		success
	UNION
	SELECT
		id
	FROM
		failed
)
SELECT
	rollouts.id,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details, fd.rename,
	rollouts.created,
	EXISTS (
		SELECT
			1
		FROM
			deployments d
		WHERE
			d.feature_name = fd.name) AS hasDeployments
	FROM
		rollouts
		JOIN all_rollouts ar ON ar.id = rollouts.id
		JOIN feature_data fd ON rollouts.feature_name = fd.name
			AND rollouts.version = fd.version
		ORDER BY
			rollouts.feature_name ASC
`

type RolloutsForKindRow struct {
	ID             uuid.UUID
	FeatureDatum   FeatureDatum
	Created        pgtype.Timestamptz
	Hasdeployments bool
}

func (q *Queries) RolloutsForKind(ctx context.Context, environmentKind EnvironmentKind) ([]RolloutsForKindRow, error) {
	rows, err := q.db.Query(ctx, rolloutsForKind, environmentKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolloutsForKindRow{}
	for rows.Next() {
		var i RolloutsForKindRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
			&i.FeatureDatum.Rename,
			&i.Created,
			&i.Hasdeployments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
