// Code generated by sqlc. DO NOT EDIT.
// source: tenant.sql

package gensql

import (
	"context"

	"github.com/google/uuid"
)

const tenantGet = `-- name: TenantGet :one
SELECT
	id, name, description, created, last_modified, ci, upgrade_delay_days
FROM
	tenants
WHERE
	id = $1
`

func (q *Queries) TenantGet(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantGet, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
		&i.UpgradeDelayDays,
	)
	return i, err
}

const tenantGetByName = `-- name: TenantGetByName :one
SELECT
	id, name, description, created, last_modified, ci, upgrade_delay_days
FROM
	tenants
WHERE
	name = $1
`

func (q *Queries) TenantGetByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantGetByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
		&i.UpgradeDelayDays,
	)
	return i, err
}

const tenantSetUpgradeDelayDays = `-- name: TenantSetUpgradeDelayDays :one
UPDATE
	tenants
SET
	upgrade_delay_days = $1
WHERE
	id = $2
RETURNING
	id, name, description, created, last_modified, ci, upgrade_delay_days
`

type TenantSetUpgradeDelayDaysParams struct {
	UpgradeDelayDays int32
	ID               uuid.UUID
}

func (q *Queries) TenantSetUpgradeDelayDays(ctx context.Context, arg TenantSetUpgradeDelayDaysParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, tenantSetUpgradeDelayDays, arg.UpgradeDelayDays, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
		&i.UpgradeDelayDays,
	)
	return i, err
}

const tenantsGet = `-- name: TenantsGet :many
SELECT
	id, name, description, created, last_modified, ci, upgrade_delay_days
FROM
	tenants
ORDER BY
	created DESC,
	name ASC
`

func (q *Queries) TenantsGet(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, tenantsGet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Created,
			&i.LastModified,
			&i.Ci,
			&i.UpgradeDelayDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
