name: "Install prereqs"
description: "install gcloud/helm"

runs:
  using: composite
  steps:
    - name: install gcloud
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg curl python3
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install google-cloud-cli
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
    - name: install helm
      shell: bash
      run: |
        type helm && exit 0
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
