environmentKinds:
  - tenant
  - management
  - onprem
values:
  tenantName:
    displayName: Tenant name
    computed:
      template: "{{.Tenant.Name}}"
  env:
    displayName: Environment name
    computed:
      template: "{{.Env.name}}"
  envProjectId:
    displayName: Env project id
    computed:
      template: "{{.Env.project_id}}"
  iapAudience:
    displayName: IAP audience (OAuth client ID)
    computed:
      template: "{{.Fasit.IAPAudience}}"
  https_proxy:
    displayName: HTTPS proxy
    config:
      type: string
    ignoreKind:
      - tenant
      - management
  no_proxy:
    displayName: No proxy
    config:
      type: string
    ignoreKind:
      - tenant
      - management
  image.tag:
    displayName: Image tag
    config:
      type: string
