apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fasit.fullname" . }}
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "fasit.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fasit.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fasit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - command:
            - /cloud_sql_proxy
            - -term_timeout=30s
            - -instances=nais-io:europe-north1:fasit=tcp:5432
          image: gcr.io/cloudsql-docker/gce-proxy:1.29.0-alpine
          imagePullPolicy: IfNotPresent
          name: cloudsql-proxy
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 32Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            runAsUser: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

        - name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --project-id
            - nais-io
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: fasit
      volumes:
      - name: tmp
        emptyDir: {}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
