apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nais-system
  name: {{ include "fasit.fullname" . }}-backend-ingress
  labels:
    app: fasit
spec:
  ingressClassName: nais-ingress
  rules:
    - host: fasit.nais.io
      http:
        paths:
          - backend:
              service:
                name: {{ include "fasit.fullname" . }}
                port:
                  number: 8080
            path: /query
            pathType: Prefix
