apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "fasit.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "fasit.selectorLabels" . | nindent 6}}
  podMetricsEndpoints:
  - port: http
