apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fasit.fullname" . }}
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
stringData:
  GH_PEM: /var/run/secrets/nais.io/gh/gh.pem
  SLACK_CHANNEL_FEATURE_ALERTS: {{ .Values.slackChannelFeatureAlerts | quote }}
  SLACK_API_TOKEN: {{ .Values.slackToken }}
