apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fasit.fullname" . }}
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
stringData:
  FASIT_DBCONN_STRING: {{ .Values.dbConnString }}
  GH_PEM: /var/run/secrets/nais.io/gh/gh.pem
  CLUSTER_UPGRADE_SLACK_CHANNEL: {{ .Values.clusterUpgradeSlackChannel }}
  SLACK_API_TOKEN: {{ .Values.slackToken }}
