apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
  name: {{ include "fasit.fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 4444
    protocol: TCP
    targetPort: grpc
  selector:
    {{- include "fasit.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.0.0.42
