apiVersion: v1
kind: Service
metadata:
  labels:
    team: nais
  name: fasit
  namespace: nais-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: fasit
  sessionAffinity: None
  type: ClusterIP
