{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fasit.serviceAccountName" . }}
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: fasit-user@{{ .Values.envProjectId }}.iam.gserviceaccount.com
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
