apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fasit.labels" . | nindent 4 }}
  name: {{ include "fasit.fullname" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "fasit.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
