// Code generated by sqlc. DO NOT EDIT.
// source: audit.sql

package auditsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO audits(
	actor,
	action,
	description,
	object_type,
	object_id,
	environment_id,
	metadata)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7)
`

type CreateParams struct {
	Actor         string
	Action        string
	Description   string
	ObjectType    string
	ObjectID      string
	EnvironmentID *uuid.UUID
	Metadata      []byte
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.Actor,
		arg.Action,
		arg.Description,
		arg.ObjectType,
		arg.ObjectID,
		arg.EnvironmentID,
		arg.Metadata,
	)
	return err
}

const list = `-- name: List :many
SELECT
	a.id, a.actor, a.description, a.object_type, a.object_id, a.created_at, a.metadata, a.action, a.environment_id,
	e.name AS environment_name,
	t.name AS tenant_name
FROM
	audits a
LEFT JOIN environments e ON e.id = a.environment_id
LEFT JOIN tenants t ON t.id = e.tenant_id
WHERE
	a.environment_id = $1::UUID
	AND (
		$2::TEXT = ''
		OR a.object_id = $2::TEXT
		OR STARTS_WITH(a.object_id, CONCAT($2::TEXT, '/'))
	)
ORDER BY
	a.created_at DESC
LIMIT $3
`

type ListParams struct {
	EnvironmentID uuid.UUID
	FeatureName   string
	PageSize      int32
}

type ListRow struct {
	ID              uuid.UUID
	Actor           string
	Description     string
	ObjectType      string
	ObjectID        string
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
	Action          string
	EnvironmentID   *uuid.UUID
	EnvironmentName *string
	TenantName      *string
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list, arg.EnvironmentID, arg.FeatureName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRow{}
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Description,
			&i.ObjectType,
			&i.ObjectID,
			&i.CreatedAt,
			&i.Metadata,
			&i.Action,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForEnvironment = `-- name: ListForEnvironment :many
SELECT
	a.id, a.actor, a.description, a.object_type, a.object_id, a.created_at, a.metadata, a.action, a.environment_id,
	e.name AS environment_name,
	t.name AS tenant_name
FROM
	audits a
LEFT JOIN environments e ON e.id = a.environment_id
LEFT JOIN tenants t ON t.id = e.tenant_id
WHERE
	a.environment_id = $1
ORDER BY
	a.created_at DESC
LIMIT $2
`

type ListForEnvironmentParams struct {
	EnvID    *uuid.UUID
	PageSize int32
}

type ListForEnvironmentRow struct {
	ID              uuid.UUID
	Actor           string
	Description     string
	ObjectType      string
	ObjectID        string
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
	Action          string
	EnvironmentID   *uuid.UUID
	EnvironmentName *string
	TenantName      *string
}

func (q *Queries) ListForEnvironment(ctx context.Context, arg ListForEnvironmentParams) ([]ListForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listForEnvironment, arg.EnvID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForEnvironmentRow{}
	for rows.Next() {
		var i ListForEnvironmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Description,
			&i.ObjectType,
			&i.ObjectID,
			&i.CreatedAt,
			&i.Metadata,
			&i.Action,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecent = `-- name: ListRecent :many
SELECT
	a.id, a.actor, a.description, a.object_type, a.object_id, a.created_at, a.metadata, a.action, a.environment_id,
	e.name AS environment_name,
	t.name AS tenant_name
FROM
	audits a
LEFT JOIN environments e ON e.id = a.environment_id
LEFT JOIN tenants t ON t.id = e.tenant_id
ORDER BY
	a.created_at DESC
LIMIT $1
`

type ListRecentRow struct {
	ID              uuid.UUID
	Actor           string
	Description     string
	ObjectType      string
	ObjectID        string
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
	Action          string
	EnvironmentID   *uuid.UUID
	EnvironmentName *string
	TenantName      *string
}

func (q *Queries) ListRecent(ctx context.Context, pageSize int32) ([]ListRecentRow, error) {
	rows, err := q.db.Query(ctx, listRecent, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentRow{}
	for rows.Next() {
		var i ListRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Description,
			&i.ObjectType,
			&i.ObjectID,
			&i.CreatedAt,
			&i.Metadata,
			&i.Action,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
