// Code generated by sqlc. DO NOT EDIT.

package auditsql

import (
	"context"
)

type Querier interface {
	AuditCreate(ctx context.Context, arg AuditCreateParams) error
	AuditForEnvironment(ctx context.Context, arg AuditForEnvironmentParams) ([]Audit, error)
}

var _ Querier = (*Queries)(nil)
