// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gensql "github.com/nais/fasit/pkg/database/gensql"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	testing "testing"

	uuid "github.com/google/uuid"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// ConfigDelete provides a mock function with given fields: ctx, id
func (_m *Querier) ConfigDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigEnvUpdateOrCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) ConfigEnvUpdateOrCreate(ctx context.Context, arg gensql.ConfigEnvUpdateOrCreateParams) (gensql.ConfigurationsEnvironment, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.ConfigurationsEnvironment
	if rf, ok := ret.Get(0).(func(context.Context, gensql.ConfigEnvUpdateOrCreateParams) gensql.ConfigurationsEnvironment); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.ConfigurationsEnvironment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.ConfigEnvUpdateOrCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGet provides a mock function with given fields: ctx, feature
func (_m *Querier) ConfigGet(ctx context.Context, feature string) ([]gensql.ConfigurationsGlobal, error) {
	ret := _m.Called(ctx, feature)

	var r0 []gensql.ConfigurationsGlobal
	if rf, ok := ret.Get(0).(func(context.Context, string) []gensql.ConfigurationsGlobal); ok {
		r0 = rf(ctx, feature)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.ConfigurationsGlobal)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, feature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGetForEnv provides a mock function with given fields: ctx, arg
func (_m *Querier) ConfigGetForEnv(ctx context.Context, arg gensql.ConfigGetForEnvParams) ([]gensql.ConfigurationsEnvironment, error) {
	ret := _m.Called(ctx, arg)

	var r0 []gensql.ConfigurationsEnvironment
	if rf, ok := ret.Get(0).(func(context.Context, gensql.ConfigGetForEnvParams) []gensql.ConfigurationsEnvironment); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.ConfigurationsEnvironment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.ConfigGetForEnvParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGlobalUpdateOrCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) ConfigGlobalUpdateOrCreate(ctx context.Context, arg gensql.ConfigGlobalUpdateOrCreateParams) (gensql.ConfigurationsGlobal, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.ConfigurationsGlobal
	if rf, ok := ret.Get(0).(func(context.Context, gensql.ConfigGlobalUpdateOrCreateParams) gensql.ConfigurationsGlobal); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.ConfigurationsGlobal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.ConfigGlobalUpdateOrCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) ConfigUpdate(ctx context.Context, arg gensql.ConfigUpdateParams) (gensql.ConfigurationsGlobal, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.ConfigurationsGlobal
	if rf, ok := ret.Get(0).(func(context.Context, gensql.ConfigUpdateParams) gensql.ConfigurationsGlobal); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.ConfigurationsGlobal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.ConfigUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvConfig provides a mock function with given fields: ctx, arg
func (_m *Querier) EnvConfig(ctx context.Context, arg gensql.EnvConfigParams) ([]gensql.EnvConfigRow, error) {
	ret := _m.Called(ctx, arg)

	var r0 []gensql.EnvConfigRow
	if rf, ok := ret.Get(0).(func(context.Context, gensql.EnvConfigParams) []gensql.EnvConfigRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.EnvConfigRow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.EnvConfigParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentByNames provides a mock function with given fields: ctx, arg
func (_m *Querier) EnvironmentByNames(ctx context.Context, arg gensql.EnvironmentByNamesParams) (gensql.Environment, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.Environment
	if rf, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentByNamesParams) gensql.Environment); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentByNamesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) EnvironmentCreate(ctx context.Context, arg gensql.EnvironmentCreateParams) (gensql.Environment, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.Environment
	if rf, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentCreateParams) gensql.Environment); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentGet provides a mock function with given fields: ctx, id
func (_m *Querier) EnvironmentGet(ctx context.Context, id uuid.UUID) (gensql.Environment, error) {
	ret := _m.Called(ctx, id)

	var r0 gensql.Environment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.Environment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentIDByNames provides a mock function with given fields: ctx, arg
func (_m *Querier) EnvironmentIDByNames(ctx context.Context, arg gensql.EnvironmentIDByNamesParams) (uuid.UUID, error) {
	ret := _m.Called(ctx, arg)

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentIDByNamesParams) uuid.UUID); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentIDByNamesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) EnvironmentUpdate(ctx context.Context, arg gensql.EnvironmentUpdateParams) (gensql.Environment, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.Environment
	if rf, ok := ret.Get(0).(func(context.Context, gensql.EnvironmentUpdateParams) gensql.Environment); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Environment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.EnvironmentUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentsGet provides a mock function with given fields: ctx, tenantID
func (_m *Querier) EnvironmentsGet(ctx context.Context, tenantID uuid.UUID) ([]gensql.Environment, error) {
	ret := _m.Called(ctx, tenantID)

	var r0 []gensql.Environment
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.Environment); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.Environment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureStateCreateOrUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) FeatureStateCreateOrUpdate(ctx context.Context, arg gensql.FeatureStateCreateOrUpdateParams) (gensql.FeatureState, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.FeatureState
	if rf, ok := ret.Get(0).(func(context.Context, gensql.FeatureStateCreateOrUpdateParams) gensql.FeatureState); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.FeatureState)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.FeatureStateCreateOrUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureStateGet provides a mock function with given fields: ctx, arg
func (_m *Querier) FeatureStateGet(ctx context.Context, arg gensql.FeatureStateGetParams) (gensql.FeatureState, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.FeatureState
	if rf, ok := ret.Get(0).(func(context.Context, gensql.FeatureStateGetParams) gensql.FeatureState); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.FeatureState)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.FeatureStateGetParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureStatesGet provides a mock function with given fields: ctx, environmentID
func (_m *Querier) FeatureStatesGet(ctx context.Context, environmentID uuid.UUID) ([]gensql.FeatureState, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 []gensql.FeatureState
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.FeatureState); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.FeatureState)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthStatusCreateOrUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) HealthStatusCreateOrUpdate(ctx context.Context, arg gensql.HealthStatusCreateOrUpdateParams) (gensql.HealthStatus, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context, gensql.HealthStatusCreateOrUpdateParams) gensql.HealthStatus); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.HealthStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.HealthStatusCreateOrUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthStatusGet provides a mock function with given fields: ctx, environmentID
func (_m *Querier) HealthStatusGet(ctx context.Context, environmentID uuid.UUID) (gensql.HealthStatus, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 gensql.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.HealthStatus); ok {
		r0 = rf(ctx, environmentID)
	} else {
		r0 = ret.Get(0).(gensql.HealthStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseStatusCreateOrUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) ReleaseStatusCreateOrUpdate(ctx context.Context, arg gensql.ReleaseStatusCreateOrUpdateParams) (gensql.ReleaseStatus, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.ReleaseStatus
	if rf, ok := ret.Get(0).(func(context.Context, gensql.ReleaseStatusCreateOrUpdateParams) gensql.ReleaseStatus); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.ReleaseStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.ReleaseStatusCreateOrUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseStatusesGet provides a mock function with given fields: ctx, environmentID
func (_m *Querier) ReleaseStatusesGet(ctx context.Context, environmentID uuid.UUID) ([]gensql.ReleaseStatus, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 []gensql.ReleaseStatus
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.ReleaseStatus); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.ReleaseStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatusCreateOrUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) StatusCreateOrUpdate(ctx context.Context, arg gensql.StatusCreateOrUpdateParams) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gensql.StatusCreateOrUpdateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatusForEnvironment provides a mock function with given fields: ctx, environmentID
func (_m *Querier) StatusForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]gensql.Status, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 []gensql.Status
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []gensql.Status); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatusForFeature provides a mock function with given fields: ctx, arg
func (_m *Querier) StatusForFeature(ctx context.Context, arg gensql.StatusForFeatureParams) (gensql.Status, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.Status
	if rf, ok := ret.Get(0).(func(context.Context, gensql.StatusForFeatureParams) gensql.Status); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Status)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.StatusForFeatureParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) TenantCreate(ctx context.Context, arg gensql.TenantCreateParams) (gensql.Tenant, error) {
	ret := _m.Called(ctx, arg)

	var r0 gensql.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, gensql.TenantCreateParams) gensql.Tenant); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(gensql.Tenant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, gensql.TenantCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantEnvironments provides a mock function with given fields: ctx
func (_m *Querier) TenantEnvironments(ctx context.Context) ([]gensql.TenantEnvironmentsRow, error) {
	ret := _m.Called(ctx)

	var r0 []gensql.TenantEnvironmentsRow
	if rf, ok := ret.Get(0).(func(context.Context) []gensql.TenantEnvironmentsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.TenantEnvironmentsRow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantGet provides a mock function with given fields: ctx, id
func (_m *Querier) TenantGet(ctx context.Context, id uuid.UUID) (gensql.Tenant, error) {
	ret := _m.Called(ctx, id)

	var r0 gensql.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) gensql.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(gensql.Tenant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantGetByName provides a mock function with given fields: ctx, name
func (_m *Querier) TenantGetByName(ctx context.Context, name string) (gensql.Tenant, error) {
	ret := _m.Called(ctx, name)

	var r0 gensql.Tenant
	if rf, ok := ret.Get(0).(func(context.Context, string) gensql.Tenant); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(gensql.Tenant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantsGet provides a mock function with given fields: ctx
func (_m *Querier) TenantsGet(ctx context.Context) ([]gensql.Tenant, error) {
	ret := _m.Called(ctx)

	var r0 []gensql.Tenant
	if rf, ok := ret.Get(0).(func(context.Context) []gensql.Tenant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *Querier) WithTx(tx *sql.Tx) *gensql.Queries {
	ret := _m.Called(tx)

	var r0 *gensql.Queries
	if rf, ok := ret.Get(0).(func(*sql.Tx) *gensql.Queries); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gensql.Queries)
		}
	}

	return r0
}

// NewQuerier creates a new instance of Querier. It also registers a cleanup function to assert the mocks expectations.
func NewQuerier(t testing.TB) *Querier {
	mock := &Querier{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
