// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/nais/fasit/pkg/database"
	feature "github.com/nais/fasit/pkg/feature"

	gensql "github.com/nais/fasit/pkg/database/gensql"

	json "encoding/json"

	message "github.com/nais/fasit/pkg/message"

	metric "go.opentelemetry.io/otel/metric"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nais/fasit/pkg/graph/model"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// AuditForEnvironment provides a mock function with given fields: ctx, id, featureName
func (_m *Repo) AuditForEnvironment(ctx context.Context, id uuid.UUID, featureName string) ([]*model.AuditLog, error) {
	ret := _m.Called(ctx, id, featureName)

	var r0 []*model.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]*model.AuditLog, error)); ok {
		return rf(ctx, id, featureName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []*model.AuditLog); ok {
		r0 = rf(ctx, id, featureName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, featureName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AutoInstallsForKind provides a mock function with given fields: ctx, kind
func (_m *Repo) AutoInstallsForKind(ctx context.Context, kind model.EnvironmentKind) ([]string, error) {
	ret := _m.Called(ctx, kind)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) ([]string, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) []string); ok {
		r0 = rf(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.EnvironmentKind) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *Repo) Close() {
	_m.Called()
}

// ConfigCreate provides a mock function with given fields: ctx, c
func (_m *Repo) ConfigCreate(ctx context.Context, c model.NewConfiguration) (*model.Configuration, error) {
	ret := _m.Called(ctx, c)

	var r0 *model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NewConfiguration) (*model.Configuration, error)); ok {
		return rf(ctx, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NewConfiguration) *model.Configuration); ok {
		r0 = rf(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NewConfiguration) error); ok {
		r1 = rf(ctx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigDelete provides a mock function with given fields: ctx, id
func (_m *Repo) ConfigDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigGet provides a mock function with given fields: ctx, _a1
func (_m *Repo) ConfigGet(ctx context.Context, _a1 string) ([]*model.Configuration, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []*model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Configuration, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Configuration); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGetByID provides a mock function with given fields: ctx, id
func (_m *Repo) ConfigGetByID(ctx context.Context, id uuid.UUID) (*model.Configuration, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Configuration, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Configuration); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGetForEnv provides a mock function with given fields: ctx, _a1, envID
func (_m *Repo) ConfigGetForEnv(ctx context.Context, _a1 string, envID uuid.UUID) ([]*model.Configuration, error) {
	ret := _m.Called(ctx, _a1, envID)

	var r0 []*model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]*model.Configuration, error)); ok {
		return rf(ctx, _a1, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []*model.Configuration); ok {
		r0 = rf(ctx, _a1, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigOverridesByFeature provides a mock function with given fields: ctx, featureName
func (_m *Repo) ConfigOverridesByFeature(ctx context.Context, featureName string) ([]*model.ConfigOverride, error) {
	ret := _m.Called(ctx, featureName)

	var r0 []*model.ConfigOverride
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.ConfigOverride, error)); ok {
		return rf(ctx, featureName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.ConfigOverride); ok {
		r0 = rf(ctx, featureName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ConfigOverride)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, featureName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigUpdate provides a mock function with given fields: ctx, id, c
func (_m *Repo) ConfigUpdate(ctx context.Context, id uuid.UUID, c model.UpdateConfiguration) (*model.Configuration, error) {
	ret := _m.Called(ctx, id, c)

	var r0 *model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateConfiguration) (*model.Configuration, error)); ok {
		return rf(ctx, id, c)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateConfiguration) *model.Configuration); ok {
		r0 = rf(ctx, id, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateConfiguration) error); ok {
		r1 = rf(ctx, id, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeployInstructionCreate provides a mock function with given fields: ctx, envID, featureName, featureVersion, hash
func (_m *Repo) DeployInstructionCreate(ctx context.Context, envID uuid.UUID, featureName string, featureVersion string, hash string) (uuid.UUID, error) {
	ret := _m.Called(ctx, envID, featureName, featureVersion, hash)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, envID, featureName, featureVersion, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) uuid.UUID); ok {
		r0 = rf(ctx, envID, featureName, featureVersion, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, envID, featureName, featureVersion, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeployInstructionGet provides a mock function with given fields: ctx, id
func (_m *Repo) DeployInstructionGet(ctx context.Context, id uuid.UUID) (*model.DeployInstruction, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.DeployInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.DeployInstruction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.DeployInstruction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeployInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeployInstructionUpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *Repo) DeployInstructionUpdateStatus(ctx context.Context, id uuid.UUID, status model.RolloutStatus) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.RolloutStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeployInstructionsForFeature provides a mock function with given fields: ctx, envID, featureName, offset
func (_m *Repo) DeployInstructionsForFeature(ctx context.Context, envID uuid.UUID, featureName string, offset int) ([]*model.DeployInstruction, error) {
	ret := _m.Called(ctx, envID, featureName, offset)

	var r0 []*model.DeployInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) ([]*model.DeployInstruction, error)); ok {
		return rf(ctx, envID, featureName, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) []*model.DeployInstruction); ok {
		r0 = rf(ctx, envID, featureName, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.DeployInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = rf(ctx, envID, featureName, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeployInstructionsLatestForEnvironment provides a mock function with given fields: ctx, envID
func (_m *Repo) DeployInstructionsLatestForEnvironment(ctx context.Context, envID uuid.UUID) ([]*model.DeployInstruction, error) {
	ret := _m.Called(ctx, envID)

	var r0 []*model.DeployInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.DeployInstruction, error)); ok {
		return rf(ctx, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.DeployInstruction); ok {
		r0 = rf(ctx, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.DeployInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeployInstructionsLatestForFeature provides a mock function with given fields: ctx, envID, featureName
func (_m *Repo) DeployInstructionsLatestForFeature(ctx context.Context, envID uuid.UUID, featureName string) (*model.DeployInstruction, error) {
	ret := _m.Called(ctx, envID, featureName)

	var r0 *model.DeployInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.DeployInstruction, error)); ok {
		return rf(ctx, envID, featureName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.DeployInstruction); ok {
		r0 = rf(ctx, envID, featureName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeployInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, envID, featureName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvConfig provides a mock function with given fields: ctx, _a1, envID
func (_m *Repo) EnvConfig(ctx context.Context, _a1 string, envID uuid.UUID) ([]*model.Configuration, error) {
	ret := _m.Called(ctx, _a1, envID)

	var r0 []*model.Configuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]*model.Configuration, error)); ok {
		return rf(ctx, _a1, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []*model.Configuration); ok {
		r0 = rf(ctx, _a1, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Configuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentByNames provides a mock function with given fields: ctx, tenantName, environmentName
func (_m *Repo) EnvironmentByNames(ctx context.Context, tenantName string, environmentName string) (*model.Environment, error) {
	ret := _m.Called(ctx, tenantName, environmentName)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Environment, error)); ok {
		return rf(ctx, tenantName, environmentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Environment); ok {
		r0 = rf(ctx, tenantName, environmentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantName, environmentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentCI provides a mock function with given fields: ctx, kind
func (_m *Repo) EnvironmentCI(ctx context.Context, kind model.EnvironmentKind) (*model.Environment, error) {
	ret := _m.Called(ctx, kind)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) (*model.Environment, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind) *model.Environment); ok {
		r0 = rf(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.EnvironmentKind) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentCreate provides a mock function with given fields: ctx, t
func (_m *Repo) EnvironmentCreate(ctx context.Context, t *model.EnvironmentCreate) (*model.Environment, error) {
	ret := _m.Called(ctx, t)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.EnvironmentCreate) (*model.Environment, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.EnvironmentCreate) *model.Environment); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.EnvironmentCreate) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentGet provides a mock function with given fields: ctx, id
func (_m *Repo) EnvironmentGet(ctx context.Context, id uuid.UUID) (*model.Environment, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Environment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Environment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentGetByName provides a mock function with given fields: ctx, tenantID, name
func (_m *Repo) EnvironmentGetByName(ctx context.Context, tenantID uuid.UUID, name string) (*model.Environment, error) {
	ret := _m.Called(ctx, tenantID, name)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.Environment, error)); ok {
		return rf(ctx, tenantID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.Environment); ok {
		r0 = rf(ctx, tenantID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, tenantID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentIDByNames provides a mock function with given fields: ctx, tenantName, environmentName
func (_m *Repo) EnvironmentIDByNames(ctx context.Context, tenantName string, environmentName string) (uuid.UUID, error) {
	ret := _m.Called(ctx, tenantName, environmentName)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return rf(ctx, tenantName, environmentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = rf(ctx, tenantName, environmentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantName, environmentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentSetReconcile provides a mock function with given fields: ctx, environmentID, reconcile
func (_m *Repo) EnvironmentSetReconcile(ctx context.Context, environmentID uuid.UUID, reconcile bool) (*model.Environment, error) {
	ret := _m.Called(ctx, environmentID, reconcile)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*model.Environment, error)); ok {
		return rf(ctx, environmentID, reconcile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *model.Environment); ok {
		r0 = rf(ctx, environmentID, reconcile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, environmentID, reconcile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentUpdate provides a mock function with given fields: ctx, environmentID, p
func (_m *Repo) EnvironmentUpdate(ctx context.Context, environmentID uuid.UUID, p *model.EnvironmentUpdate) (*model.Environment, error) {
	ret := _m.Called(ctx, environmentID, p)

	var r0 *model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.EnvironmentUpdate) (*model.Environment, error)); ok {
		return rf(ctx, environmentID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.EnvironmentUpdate) *model.Environment); ok {
		r0 = rf(ctx, environmentID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.EnvironmentUpdate) error); ok {
		r1 = rf(ctx, environmentID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentValueGet provides a mock function with given fields: ctx, environmentID, key, showSensitive
func (_m *Repo) EnvironmentValueGet(ctx context.Context, environmentID uuid.UUID, key string, showSensitive bool) (*model.EnvironmentValue, error) {
	ret := _m.Called(ctx, environmentID, key, showSensitive)

	var r0 *model.EnvironmentValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool) (*model.EnvironmentValue, error)); ok {
		return rf(ctx, environmentID, key, showSensitive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool) *model.EnvironmentValue); ok {
		r0 = rf(ctx, environmentID, key, showSensitive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EnvironmentValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, bool) error); ok {
		r1 = rf(ctx, environmentID, key, showSensitive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentValueStore provides a mock function with given fields: ctx, environmentID, key, value, secret
func (_m *Repo) EnvironmentValueStore(ctx context.Context, environmentID uuid.UUID, key string, value json.RawMessage, secret bool) error {
	ret := _m.Called(ctx, environmentID, key, value, secret)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, json.RawMessage, bool) error); ok {
		r0 = rf(ctx, environmentID, key, value, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnvironmentValuesAcrossEnvs provides a mock function with given fields: ctx, key
func (_m *Repo) EnvironmentValuesAcrossEnvs(ctx context.Context, key string) ([]gensql.EnvironmentValuesAcrossEnvsRow, error) {
	ret := _m.Called(ctx, key)

	var r0 []gensql.EnvironmentValuesAcrossEnvsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]gensql.EnvironmentValuesAcrossEnvsRow, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []gensql.EnvironmentValuesAcrossEnvsRow); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gensql.EnvironmentValuesAcrossEnvsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentValuesForEnvironment provides a mock function with given fields: ctx, envID, showSensitive
func (_m *Repo) EnvironmentValuesForEnvironment(ctx context.Context, envID uuid.UUID, showSensitive bool) ([]*model.EnvironmentValue, error) {
	ret := _m.Called(ctx, envID, showSensitive)

	var r0 []*model.EnvironmentValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) ([]*model.EnvironmentValue, error)); ok {
		return rf(ctx, envID, showSensitive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) []*model.EnvironmentValue); ok {
		r0 = rf(ctx, envID, showSensitive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EnvironmentValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, envID, showSensitive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EnvironmentsGet provides a mock function with given fields: ctx, tenantID
func (_m *Repo) EnvironmentsGet(ctx context.Context, tenantID uuid.UUID) ([]*model.Environment, error) {
	ret := _m.Called(ctx, tenantID)

	var r0 []*model.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Environment, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Environment); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureByName provides a mock function with given fields: ctx, name
func (_m *Repo) FeatureByName(ctx context.Context, name string) (*model.Feature, error) {
	ret := _m.Called(ctx, name)

	var r0 *model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Feature, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Feature); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureByNameForEnv provides a mock function with given fields: ctx, name, envID
func (_m *Repo) FeatureByNameForEnv(ctx context.Context, name string, envID uuid.UUID) (*model.Feature, error) {
	ret := _m.Called(ctx, name, envID)

	var r0 *model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*model.Feature, error)); ok {
		return rf(ctx, name, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *model.Feature); ok {
		r0 = rf(ctx, name, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureDataCreate provides a mock function with given fields: _a0, _a1
func (_m *Repo) FeatureDataCreate(_a0 context.Context, _a1 model.Feature) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Feature) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FeatureStateGet provides a mock function with given fields: ctx, envID, featureName
func (_m *Repo) FeatureStateGet(ctx context.Context, envID uuid.UUID, featureName string) (*model.FeatureState, error) {
	ret := _m.Called(ctx, envID, featureName)

	var r0 *model.FeatureState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.FeatureState, error)); ok {
		return rf(ctx, envID, featureName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.FeatureState); ok {
		r0 = rf(ctx, envID, featureName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeatureState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, envID, featureName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureStatesCreateOrUpdate provides a mock function with given fields: ctx, envID, _a2, enabled
func (_m *Repo) FeatureStatesCreateOrUpdate(ctx context.Context, envID uuid.UUID, _a2 *model.Feature, enabled bool) (*model.FeatureState, error) {
	ret := _m.Called(ctx, envID, _a2, enabled)

	var r0 *model.FeatureState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.Feature, bool) (*model.FeatureState, error)); ok {
		return rf(ctx, envID, _a2, enabled)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.Feature, bool) *model.FeatureState); ok {
		r0 = rf(ctx, envID, _a2, enabled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FeatureState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.Feature, bool) error); ok {
		r1 = rf(ctx, envID, _a2, enabled)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureStatesGet provides a mock function with given fields: ctx, envID
func (_m *Repo) FeatureStatesGet(ctx context.Context, envID uuid.UUID) ([]*model.FeatureState, error) {
	ret := _m.Called(ctx, envID)

	var r0 []*model.FeatureState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.FeatureState, error)); ok {
		return rf(ctx, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.FeatureState); ok {
		r0 = rf(ctx, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FeatureState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeatureVersionUpdate provides a mock function with given fields: ctx, name, version
func (_m *Repo) FeatureVersionUpdate(ctx context.Context, name string, version string) error {
	ret := _m.Called(ctx, name, version)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Features provides a mock function with given fields: ctx
func (_m *Repo) Features(ctx context.Context) ([]*model.Feature, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Feature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Feature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeaturesForKind provides a mock function with given fields: ctx, kind, ci
func (_m *Repo) FeaturesForKind(ctx context.Context, kind model.EnvironmentKind, ci bool) ([]*model.Feature, error) {
	ret := _m.Called(ctx, kind, ci)

	var r0 []*model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind, bool) ([]*model.Feature, error)); ok {
		return rf(ctx, kind, ci)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.EnvironmentKind, bool) []*model.Feature); ok {
		r0 = rf(ctx, kind, ci)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.EnvironmentKind, bool) error); ok {
		r1 = rf(ctx, kind, ci)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthGet provides a mock function with given fields: ctx, environmentID
func (_m *Repo) HealthGet(ctx context.Context, environmentID uuid.UUID) (*model.Health, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 *model.Health
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Health, error)); ok {
		return rf(ctx, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Health); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Health)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HealthStatusCreateOrUpdate provides a mock function with given fields: ctx, environmentID, h
func (_m *Repo) HealthStatusCreateOrUpdate(ctx context.Context, environmentID uuid.UUID, h *message.Health) error {
	ret := _m.Called(ctx, environmentID, h)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *message.Health) error); ok {
		r0 = rf(ctx, environmentID, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HelmValues provides a mock function with given fields: ctx, _a1, envID
func (_m *Repo) HelmValues(ctx context.Context, _a1 *model.Feature, envID uuid.UUID) (map[string]interface{}, error) {
	ret := _m.Called(ctx, _a1, envID)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Feature, uuid.UUID) (map[string]interface{}, error)); ok {
		return rf(ctx, _a1, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Feature, uuid.UUID) map[string]interface{}); ok {
		r0 = rf(ctx, _a1, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Feature, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KubernetesNodeSync provides a mock function with given fields: ctx, envID, kn
func (_m *Repo) KubernetesNodeSync(ctx context.Context, envID uuid.UUID, kn *message.KubernetesNodes) error {
	ret := _m.Called(ctx, envID, kn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *message.KubernetesNodes) error); ok {
		r0 = rf(ctx, envID, kn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KubernetesNodesForEnv provides a mock function with given fields: ctx, envID
func (_m *Repo) KubernetesNodesForEnv(ctx context.Context, envID uuid.UUID) ([]*model.KubernetesNode, error) {
	ret := _m.Called(ctx, envID)

	var r0 []*model.KubernetesNode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.KubernetesNode, error)); ok {
		return rf(ctx, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.KubernetesNode); ok {
		r0 = rf(ctx, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.KubernetesNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogCreate provides a mock function with given fields: ctx, deployInstructionID, lines
func (_m *Repo) LogCreate(ctx context.Context, deployInstructionID uuid.UUID, lines []message.LogLine) error {
	ret := _m.Called(ctx, deployInstructionID, lines)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []message.LogLine) error); ok {
		r0 = rf(ctx, deployInstructionID, lines)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogsByID provides a mock function with given fields: ctx, id
func (_m *Repo) LogsByID(ctx context.Context, id int) (*model.LogLine, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.LogLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.LogLine, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.LogLine); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LogLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogsGet provides a mock function with given fields: ctx, deployInstructionID
func (_m *Repo) LogsGet(ctx context.Context, deployInstructionID uuid.UUID) ([]*model.LogLine, error) {
	ret := _m.Called(ctx, deployInstructionID)

	var r0 []*model.LogLine
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.LogLine, error)); ok {
		return rf(ctx, deployInstructionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.LogLine); ok {
		r0 = rf(ctx, deployInstructionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LogLine)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, deployInstructionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MappingValuesForEnvironment provides a mock function with given fields: ctx, envID, showSensitive
func (_m *Repo) MappingValuesForEnvironment(ctx context.Context, envID uuid.UUID, showSensitive bool) (*feature.ComputedValues, model.EnvironmentKind, error) {
	ret := _m.Called(ctx, envID, showSensitive)

	var r0 *feature.ComputedValues
	var r1 model.EnvironmentKind
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*feature.ComputedValues, model.EnvironmentKind, error)); ok {
		return rf(ctx, envID, showSensitive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *feature.ComputedValues); ok {
		r0 = rf(ctx, envID, showSensitive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*feature.ComputedValues)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) model.EnvironmentKind); ok {
		r1 = rf(ctx, envID, showSensitive)
	} else {
		r1 = ret.Get(1).(model.EnvironmentKind)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, bool) error); ok {
		r2 = rf(ctx, envID, showSensitive)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Metrics provides a mock function with given fields: meter
func (_m *Repo) Metrics(meter metric.Meter) error {
	ret := _m.Called(meter)

	var r0 error
	if rf, ok := ret.Get(0).(func(metric.Meter) error); ok {
		r0 = rf(meter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseStatusCreateOrUpdate provides a mock function with given fields: ctx, environmentID, h
func (_m *Repo) ReleaseStatusCreateOrUpdate(ctx context.Context, environmentID uuid.UUID, h *message.Release) error {
	ret := _m.Called(ctx, environmentID, h)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *message.Release) error); ok {
		r0 = rf(ctx, environmentID, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseStatusDeleteByEnvironmentID provides a mock function with given fields: ctx, environmentID
func (_m *Repo) ReleaseStatusDeleteByEnvironmentID(ctx context.Context, environmentID uuid.UUID) error {
	ret := _m.Called(ctx, environmentID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, environmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseStatusesGet provides a mock function with given fields: ctx, environmentID
func (_m *Repo) ReleaseStatusesGet(ctx context.Context, environmentID uuid.UUID) ([]*model.Release, error) {
	ret := _m.Called(ctx, environmentID)

	var r0 []*model.Release
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Release, error)); ok {
		return rf(ctx, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Release); ok {
		r0 = rf(ctx, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Release)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutByName provides a mock function with given fields: ctx, name
func (_m *Repo) RolloutByName(ctx context.Context, name string) (*model.Feature, error) {
	ret := _m.Called(ctx, name)

	var r0 *model.Feature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Feature, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Feature); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Feature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutByNameAndVersion provides a mock function with given fields: ctx, name, version
func (_m *Repo) RolloutByNameAndVersion(ctx context.Context, name string, version string) (*model.Rollout, error) {
	ret := _m.Called(ctx, name, version)

	var r0 *model.Rollout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Rollout, error)); ok {
		return rf(ctx, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Rollout); ok {
		r0 = rf(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Rollout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutCalculateDone provides a mock function with given fields: ctx, rolloutID
func (_m *Repo) RolloutCalculateDone(ctx context.Context, rolloutID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, rolloutID)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, rolloutID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, rolloutID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, rolloutID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutCreate provides a mock function with given fields: ctx, name, version
func (_m *Repo) RolloutCreate(ctx context.Context, name string, version string) (*model.Rollout, error) {
	ret := _m.Called(ctx, name, version)

	var r0 *model.Rollout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Rollout, error)); ok {
		return rf(ctx, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Rollout); ok {
		r0 = rf(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Rollout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutDelete provides a mock function with given fields: ctx, name
func (_m *Repo) RolloutDelete(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RolloutEventCreate provides a mock function with given fields: ctx, rollout, failure, _a3, data
func (_m *Repo) RolloutEventCreate(ctx context.Context, rollout uuid.UUID, failure bool, _a3 string, data map[string]interface{}) error {
	ret := _m.Called(ctx, rollout, failure, _a3, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, rollout, failure, _a3, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RolloutEvents provides a mock function with given fields: ctx, rolloutID
func (_m *Repo) RolloutEvents(ctx context.Context, rolloutID uuid.UUID) ([]*model.RolloutEvent, error) {
	ret := _m.Called(ctx, rolloutID)

	var r0 []*model.RolloutEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.RolloutEvent, error)); ok {
		return rf(ctx, rolloutID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.RolloutEvent); ok {
		r0 = rf(ctx, rolloutID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RolloutEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, rolloutID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutStatesGet provides a mock function with given fields: ctx, envID
func (_m *Repo) RolloutStatesGet(ctx context.Context, envID uuid.UUID) ([]*model.FeatureState, error) {
	ret := _m.Called(ctx, envID)

	var r0 []*model.FeatureState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.FeatureState, error)); ok {
		return rf(ctx, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.FeatureState); ok {
		r0 = rf(ctx, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.FeatureState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutStatus provides a mock function with given fields: ctx, name
func (_m *Repo) RolloutStatus(ctx context.Context, name string) (model.RolloutStatus, error) {
	ret := _m.Called(ctx, name)

	var r0 model.RolloutStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.RolloutStatus, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.RolloutStatus); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.RolloutStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutsForFeature provides a mock function with given fields: ctx, name
func (_m *Repo) RolloutsForFeature(ctx context.Context, name string) ([]*model.Rollout, error) {
	ret := _m.Called(ctx, name)

	var r0 []*model.Rollout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Rollout, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Rollout); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Rollout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RolloutsUpdateStatus provides a mock function with given fields: ctx, status, name, completed
func (_m *Repo) RolloutsUpdateStatus(ctx context.Context, status model.RolloutStatus, name string, completed bool) error {
	ret := _m.Called(ctx, status, name, completed)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RolloutStatus, string, bool) error); ok {
		r0 = rf(ctx, status, name, completed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TenantCI provides a mock function with given fields: ctx
func (_m *Repo) TenantCI(ctx context.Context) (*model.Tenant, error) {
	ret := _m.Called(ctx)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.Tenant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.Tenant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantCreate provides a mock function with given fields: ctx, t
func (_m *Repo) TenantCreate(ctx context.Context, t *model.TenantCreate) (*model.Tenant, error) {
	ret := _m.Called(ctx, t)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantCreate) (*model.Tenant, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.TenantCreate) *model.Tenant); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.TenantCreate) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantEnvironments provides a mock function with given fields: ctx, onlyReconciled
func (_m *Repo) TenantEnvironments(ctx context.Context, onlyReconciled bool) ([]*model.TenantEnvironment, error) {
	ret := _m.Called(ctx, onlyReconciled)

	var r0 []*model.TenantEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]*model.TenantEnvironment, error)); ok {
		return rf(ctx, onlyReconciled)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []*model.TenantEnvironment); ok {
		r0 = rf(ctx, onlyReconciled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.TenantEnvironment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, onlyReconciled)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantGet provides a mock function with given fields: ctx, id
func (_m *Repo) TenantGet(ctx context.Context, id uuid.UUID) (*model.Tenant, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Tenant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantGetByName provides a mock function with given fields: ctx, name
func (_m *Repo) TenantGetByName(ctx context.Context, name string) (*model.Tenant, error) {
	ret := _m.Called(ctx, name)

	var r0 *model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Tenant, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Tenant); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantsGet provides a mock function with given fields: ctx
func (_m *Repo) TenantsGet(ctx context.Context) ([]*model.Tenant, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Tenant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Tenant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxFunc provides a mock function with given fields: ctx, fn
func (_m *Repo) TxFunc(ctx context.Context, fn database.TXFunc) error {
	ret := _m.Called(ctx, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.TXFunc) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Warnings provides a mock function with given fields: ctx, environmentID, tenantID
func (_m *Repo) Warnings(ctx context.Context, environmentID *uuid.UUID, tenantID *uuid.UUID) ([]model.Warning, error) {
	ret := _m.Called(ctx, environmentID, tenantID)

	var r0 []model.Warning
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *uuid.UUID) ([]model.Warning, error)); ok {
		return rf(ctx, environmentID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *uuid.UUID) []model.Warning); ok {
		r0 = rf(ctx, environmentID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Warning)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, *uuid.UUID) error); ok {
		r1 = rf(ctx, environmentID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: ctx
func (_m *Repo) WithTx(ctx context.Context) (database.Repo, pgx.Tx, error) {
	ret := _m.Called(ctx)

	var r0 database.Repo
	var r1 pgx.Tx
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (database.Repo, pgx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) database.Repo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Repo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) pgx.Tx); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepo(t mockConstructorTestingTNewRepo) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
