{{- $top := . -}}
{{- range .Values.upstreams }}
{{- $host := include "oidcproxy.ingressHost" (dict "upstream" . "domain" $top.Values.ingressDomain) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "oidcproxy.fullname" $top) (include "oidcproxy.upstreamName" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "oidcproxy.labels" $top | nindent 4 }}
spec:
  ingressClassName: {{ $top.Values.ingressClassName }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /.well-known/openid-configuration
            pathType: Exact
            backend:
              service:
                name: {{ include "oidcproxy.fullname" $top }}
                port:
                  name: http
          - path: /openid/v1/jwks
            pathType: Exact
            backend:
              service:
                name: {{ include "oidcproxy.fullname" $top }}
                port:
                  name: http
{{- end }}
