// Code generated by sqlc. DO NOT EDIT.

package sqlgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nais/fasit/internal/database/types"
)

type Deployment struct {
	ID          uuid.UUID
	FeatureName string
	Version     string
	Target      types.EnvironmentLabels
	Created     pgtype.Timestamptz
	GhRef       []byte
	Description *string
	Active      bool
}

type FeatureDatum struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []types.EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}
