// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const getFeatureAssignment = `-- name: GetFeatureAssignment :one
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.id = $1::UUID
`

type GetFeatureAssignmentRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) GetFeatureAssignment(ctx context.Context, id uuid.UUID) (GetFeatureAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getFeatureAssignment, id)
	var i GetFeatureAssignmentRow
	err := row.Scan(
		&i.FeatureAssignment.ID,
		&i.FeatureAssignment.FeatureName,
		&i.FeatureAssignment.Version,
		&i.FeatureAssignment.Target,
		&i.FeatureAssignment.Created,
		&i.FeatureAssignment.GhRef,
		&i.FeatureAssignment.Description,
		&i.FeatureAssignment.Active,
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
	)
	return i, err
}

const listTenantsWithEnvironments = `-- name: ListTenantsWithEnvironments :many
SELECT
	t.id, t.name, t.description, t.created, t.last_modified, t.ci,
	e.id, e.tenant_id, e.name, e.kind, e.description, e.created, e.last_modified, e.reconcile, e.labels,
	ev.value AS gcp_project_id
FROM
	tenants t
	JOIN environments e ON e.tenant_id = t.id
	LEFT JOIN environment_values ev ON ev.environment_id = e.id
		AND ev.key = 'project_id'
		AND ev.secret = FALSE
	ORDER BY
		t.name,
		e.name
`

type ListTenantsWithEnvironmentsRow struct {
	Tenant       Tenant
	Environment  Environment
	GcpProjectID []byte
}

func (q *Queries) ListTenantsWithEnvironments(ctx context.Context) ([]ListTenantsWithEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listTenantsWithEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsWithEnvironmentsRow{}
	for rows.Next() {
		var i ListTenantsWithEnvironmentsRow
		if err := rows.Scan(
			&i.Tenant.ID,
			&i.Tenant.Name,
			&i.Tenant.Description,
			&i.Tenant.Created,
			&i.Tenant.LastModified,
			&i.Tenant.Ci,
			&i.Environment.ID,
			&i.Environment.TenantID,
			&i.Environment.Name,
			&i.Environment.Kind,
			&i.Environment.Description,
			&i.Environment.Created,
			&i.Environment.LastModified,
			&i.Environment.Reconcile,
			&i.Environment.Labels,
			&i.GcpProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
