// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

const getFeatureAssignment = `-- name: GetFeatureAssignment :one
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.id = $1::UUID
`

type GetFeatureAssignmentRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) GetFeatureAssignment(ctx context.Context, id uuid.UUID) (GetFeatureAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getFeatureAssignment, id)
	var i GetFeatureAssignmentRow
	err := row.Scan(
		&i.FeatureAssignment.ID,
		&i.FeatureAssignment.FeatureName,
		&i.FeatureAssignment.Version,
		&i.FeatureAssignment.Target,
		&i.FeatureAssignment.Created,
		&i.FeatureAssignment.GhRef,
		&i.FeatureAssignment.Description,
		&i.FeatureAssignment.Active,
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
	)
	return i, err
}
