apiVersion: v2
name: oidcproxy
description: Reverse proxy exposing on-prem Kubernetes apiserver OIDC discovery and JWKS endpoints to Fasit

sources:
  - https://github.com/nais/fasit/tree/main/charts/oidcproxy

type: application

version: 0.1.0

appVersion: "0.1.0"
