scalar RawMessage

type Configuration {
    id: ID!
    environmentID: ID
    feature: String!
    description: String
    key: String!
    value: RawMessage!
    secret: Boolean!
    created: Time!
    deleted: Boolean!
}
input NewConfiguration {
    environmentID: ID
    feature: String!
    description: String
    key: String!
    value: RawMessage!
}
extend type Query {
    configuration(feature: String!): Configuration!
}
extend type Mutation {
    configurationCreate(configuration: NewConfiguration!): Configuration!
}
