enum ConfigType {
    STRING
    INT
    BOOL
    STRING_ARRAY
}

type Configuration {
    id: ID!
    environmentID: ID
    feature: String!
    description: String
    key: String!
    value: RawMessage!
    secret: Boolean!
    created: Time!
    type: ConfigType!
}
input NewConfiguration {
    environmentID: ID
    feature: String!
    description: String
    key: String!
    value: RawMessage!
}
extend type Query {
    configuration(feature: String!, envID: ID): [Configuration!]!
}
extend type Mutation {
    configurationCreate(configuration: NewConfiguration!): Configuration!
}
