extend type Mutation {
	deleteDeployment(deploymentID: ID!): Boolean!
}

extend type Query {
	deployments(feature: String): [Deployment!]!
}

type Deployment {
	id: ID!
	feature: Feature!
	target: [EnvironmentLabel!]!
	created: Time!
	statuses: [DeploymentStatus!]!
}

type DeploymentStatus {
	deployment: Deployment!
	environment: Environment!
	state: DeploymentStatusState!
	message: String!
	lastModified: Time!
	created: Time!
}

enum DeploymentStatusState {
	UNKNOWN
	CREATED
	PENDING
	DEPLOYED
	FAILED
}
