enum EnvironmentKind {
  TENANT
  MANAGEMENT
  ONPREM
  LEGACY
}

type Health {
  reportedAt: Time!
}

type Release {
  name: String!
  feature: Feature
  version: String!
  status: String!
  revision: Int!
  lastDeployed: Time!
  created: Time!
  lastModified: Time!
}

type Environment {
  id: ID!
  name: String!
  description: String
  featureStates: [FeatureState!]!
  created: Time!
  lastModified: Time!
  kind: EnvironmentKind!
  gcpProjectID: String
  health: Health!
  releases: [Release!]!
  nodes: [KubernetesNode!]!
  values: [EnvironmentValue!]!
  tenant: Tenant!
  warnings: [Warning!]!
  auditLog(featureName: String): [AuditLog!]!
  features: [Feature!]!
  feature(name: String!): Feature!
  reconcile: Boolean!
  versions: Versions!
  runningOperations: [Operation!]!
}

type Operation {
  id: String!
  status: String!
  type: String!
  detail: String!
  startTime: Time!
  progress: Progress!
}

type Progress {
  metrics: [ProgressMetric!]!
}

type ProgressMetric {
  name: String!
  value: Int!
}

type Versions {
  apiserver: String!
  availableVersions: [String!]!
  channel: String!
}

type EnvironmentValue {
  key: String!
  value: RawMessage!
  knownUses: Int!
}

"""
EnvironmentCreate contains metadata for creating an environment
"""
input EnvironmentCreate {
  name: String!
  description: String
  tenantID: ID!
  kind: EnvironmentKind!
}

"""
UpdateEnvironment contains metadata for updating an environment
"""
input EnvironmentUpdate {
  "description of the environment"
  description: String
}

extend type Mutation {
  environmentCreate(environment: EnvironmentCreate!): Environment!
  """
  updateEnvironment updates an existing environment
  """
  environmentUpdate(
    "id of requested environment."
    id: ID!
    "input contains information about the updated environment."
    input: EnvironmentUpdate!
  ): Environment!

  """
  Change the reconcile flag for an environment
  """
  environmentSetReconcile(id: ID!, reconcile: Boolean!): Environment!

  """
  Upgrade environment k8s cluster
  """
  environmentUpgrade(id: ID!, k8sVersion: String!): Environment!
}
