enum EnvironmentKind {
    TENANT, MANAGEMENT
}
type Environment {
    id: ID!
    name: String!
    description: String
    featureStates: [FeatureState!]!
    created: Time!
    lastModified: Time!
    kind: EnvironmentKind!
}

"""
EnvironmentCreate contains metadata for creating an environment
"""
input EnvironmentCreate {
    name: String!
    description: String
    tenantID: ID!
    kind: EnvironmentKind!
}

"""
UpdateEnvironment contains metadata for updating an environment
"""
input EnvironmentUpdate {
    "description of the environment"
    description: String
}


extend type Query {
    """
    Environment returns the given environment.
    """
    environment(
        "id of the requested environment."
        id: ID!
    ): Environment!
    """
    Environments returns the environments for a tenant.
    """
    environments(
        "id of the requested tenant."
        tenantID: ID!
    ): [Environment!]!
}

extend type Mutation {
    environmentCreate(environment: EnvironmentCreate!): Environment!
    """
    updateEnvironment updates an existing environment
    """
    environmentUpdate(
        "id of requested environment."
        id: ID!
        "input contains information about the updated environment."
        input: EnvironmentUpdate!
    ): Environment!
}
