type OutdatedInfo {
  feature: Feature!
  dependency: Boolean!
  dependencyName: String!
  newVersion: String!
}

type Feature {
  name: String!
  chart: String!
  version: String!
  repo: String!
  source: String!
  dependsOn: [Dependency!]!
  config: RawMessage!
  environmentKinds: [EnvironmentKind!]!
  rolloutSummaries: [RolloutSummary!]!
  configoverrides: [ConfigOverride!]!
  outdatedInfo: [OutdatedInfo]!
}

type ConfigOverride {
  environment: Environment!
  keys: [String!]!
}

type Dependency {
  anyOf: [String!]!
  allOf: [String!]!
}

extend type Query {
  features(kind: EnvironmentKind): [Feature!]!
  outdatedInfo: [OutdatedInfo]!
}
