type Computed {
  template: String!
}
type Config {
  type: ConfigType!
  secret: Boolean!
}

type Value {
  key: String! @goField(name: "GraphQLKey")
  displayName: String!
  description: String!
  required: Boolean!
  computed: Computed
  config: Config
}

enum HelmValueDifference {
  FULL_MATCH
  SUPERSET_MATCH
  NO_MATCH
  INVALID_JSON
}

type HelmValueDiff {
  difference: HelmValueDifference!
  diff: String!
}

type Feature {
  name: String!
  chart: String!
  version: String!
  activeVersion: String!
  source: String!
  description: String!
  dependencies: [Dependency!]!
  environmentKinds: [EnvironmentKind!]!
  configoverrides: [ConfigOverride!]!
  configuration: Configurations!
  specVersion: String!

  state: FeatureState
  status: Status
  histories: [FeatureHistory!]!
  helmValueDiff: HelmValueDiff!
}

type ConfigOverride {
  environment: Environment!
  keys: [String!]!
}

type Dependency {
  anyOf: [String!]!
  allOf: [String!]!
}

type FeatureHistory {
  id: ID!
  version: String!
  status: RolloutStatus!
  created: Time!
  lastModified: Time!
  log: [LogLine!]!
  helmValueDiff: HelmValueDiff!
}

extend type Query {
  features: [Feature!]!
  feature(name: String!): Feature!
  history(id: ID!): FeatureHistory!
}
