enum KubernetesNodePhase {
  PENDING
  RUNNING
  TERMINATED
}

enum KubernetesNodeConditionType {
  READY
  MEMORY_PRESSURE
  DISK_PRESSURE
  PID_PRESSURE
  NETWORK_UNAVAILABLE
}

enum ConditionStatus {
  TRUE
  FALSE
  UNKNOWN
}

type KubernetesNodeCondition {
  type: KubernetesNodeConditionType!
  status: ConditionStatus!
  reason: String!
  message: String!
  lastHeartbeat: Time!
  lastTransition: Time!
}

type KubernetesNodeResources {
  cpu: Int!
  memory: Int!
  storage: Int!
  pods: Int!
}

type KubernetesNode {
  name: String!
  phase: KubernetesNodePhase!
  kernelVersion: String!
  osImage: String!
  containerRuntimeVersion: String!
  kubeletVersion: String!
  kubeProxyVersion: String!
  operatingSystem: String!
  architecture: String!
  conditions: [KubernetesNodeCondition!]!
  allocatable: KubernetesNodeResources!
  capacity: KubernetesNodeResources!
}
