enum RolloutStatus {
  UNKNOWN
  CREATED
  PENDING
  DEPLOYED
  FAILED
}

type LogLine {
  id: ID!
  timestamp: Time!
  message: String!
}

type Status {
  id: ID!
  environmentID: ID!
  version: String!
  status: RolloutStatus!
  created: Time!
  lastModified: Time!
  log: [LogLine!]!
}

union Update = Status | Configuration | FeatureState

type Subscription {
  logs(environmentID: ID!, featureName: String!, lastLogID: String): LogLine!

  """
  Updates notifies whenever a feature state has been changed.
  """
  updates: Update!
}
