// Code generated by sqlc. DO NOT EDIT.
// source: deploy_instructions.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listDeployInstructions = `-- name: ListDeployInstructions :many
SELECT
	di.id, di.environment_id, di.feature_name, di.feature_version, di.status, di.hash, di.created, di.last_modified, di.values, di.feature_assignment_id,
	e.name AS environment_name,
	t.name AS tenant_name
FROM
	deploy_instructions di
	JOIN environments e ON e.id = di.environment_id
	JOIN tenants t ON t.id = e.tenant_id
WHERE
	di.feature_assignment_id = $1
ORDER BY
	di.created DESC
`

type ListDeployInstructionsRow struct {
	ID                  uuid.UUID
	EnvironmentID       uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Status              string
	Hash                string
	Created             pgtype.Timestamptz
	LastModified        pgtype.Timestamptz
	Values              []byte
	FeatureAssignmentID *uuid.UUID
	EnvironmentName     string
	TenantName          string
}

func (q *Queries) ListDeployInstructions(ctx context.Context, featureAssignmentID *uuid.UUID) ([]ListDeployInstructionsRow, error) {
	rows, err := q.db.Query(ctx, listDeployInstructions, featureAssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployInstructionsRow{}
	for rows.Next() {
		var i ListDeployInstructionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.FeatureName,
			&i.FeatureVersion,
			&i.Status,
			&i.Hash,
			&i.Created,
			&i.LastModified,
			&i.Values,
			&i.FeatureAssignmentID,
			&i.EnvironmentName,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
