// Code generated by sqlc. DO NOT EDIT.
// source: features.sql

package sqlgen

import (
	"context"
	"time"
)

const featureVersions = `-- name: FeatureVersions :many
SELECT
	fd.name,
	fd.version,
	fd.description,
	fd.source,
	MAX(COALESCE(fa.created, '0001-01-01 00:00:00+00'))::TIMESTAMPTZ AS last_updated
FROM
	feature_data fd
	LEFT JOIN feature_assignments fa ON fa.feature_name = fd.name
		AND fa.version = fd.version
WHERE
	fd.name = $1
GROUP BY
	fd.name,
	fd.version,
	fd.description,
	fd.source
ORDER BY
	last_updated DESC,
	fd.version DESC
`

type FeatureVersionsRow struct {
	Name        string
	Version     string
	Description string
	Source      string
	LastUpdated time.Time
}

func (q *Queries) FeatureVersions(ctx context.Context, featureName string) ([]FeatureVersionsRow, error) {
	rows, err := q.db.Query(ctx, featureVersions, featureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureVersionsRow{}
	for rows.Next() {
		var i FeatureVersionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Description,
			&i.Source,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFeatures = `-- name: ListActiveFeatures :many
SELECT DISTINCT ON (d.feature_name)
	fd.name,
	fd.description,
	fd.source
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.active = TRUE
ORDER BY
	d.feature_name,
	d.created DESC
`

type ListActiveFeaturesRow struct {
	Name        string
	Description string
	Source      string
}

func (q *Queries) ListActiveFeatures(ctx context.Context) ([]ListActiveFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listActiveFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveFeaturesRow{}
	for rows.Next() {
		var i ListActiveFeaturesRow
		if err := rows.Scan(&i.Name, &i.Description, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
