// Code generated by sqlc. DO NOT EDIT.

package sqlgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type Environment struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	Kind         types.EnvironmentKind
	Description  *string
	Created      time.Time
	LastModified time.Time
	Reconcile    bool
	Labels       types.EnvironmentLabels
}

type Log struct {
	ID                int64
	DeployInstruction uuid.UUID
	Time              time.Time
	Message           string
	Kind              string
}

type Tenant struct {
	ID           uuid.UUID
	Name         string
	Description  *string
	Created      time.Time
	LastModified time.Time
	Ci           bool
}
