// Code generated by sqlc. DO NOT EDIT.

package sqlgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ListReleaseStatuses(ctx context.Context, environmentID uuid.UUID) ([]ReleaseStatus, error)
	ListTenantEnvironments(ctx context.Context, tenantID uuid.UUID) ([]Environment, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
}

var _ Querier = (*Queries)(nil)
