# Default values for clamav.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gcp: false

muescheli:
  image:
    repository: navikt/muescheli
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "18.11.1"
  securityContext:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
daemon:
  image:
    repository: navikt/docker-clamav
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "8"
  securityContext:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 101

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
