// Code generated by sqlc. DO NOT EDIT.

package naisdstatussql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Get(ctx context.Context, environmentID uuid.UUID) (HealthStatus, error)
	Set(ctx context.Context, arg SetParams) (HealthStatus, error)
}

var _ Querier = (*Queries)(nil)
