// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package sqlgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments(
	name,
	description,
	tenant_id,
	kind,
	labels)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5)
RETURNING
	id, tenant_id, name, kind, description, created, last_modified, reconcile, labels, oidc_issuer, oidc_discovery_url
`

type CreateEnvironmentParams struct {
	Name        string
	Description *string
	TenantID    uuid.UUID
	Kind        types.EnvironmentKind
	Labels      types.EnvironmentLabels
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.Name,
		arg.Description,
		arg.TenantID,
		arg.Kind,
		arg.Labels,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Reconcile,
		&i.Labels,
		&i.OidcIssuer,
		&i.OidcDiscoveryUrl,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants(
	name,
	description)
VALUES (
	$1,
	$2)
RETURNING
	id, name, description, created, last_modified, ci
`

type CreateTenantParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const deleteEnvironmentValue = `-- name: DeleteEnvironmentValue :exec
DELETE FROM environment_values
WHERE environment_id = $1
	AND key = $2
`

type DeleteEnvironmentValueParams struct {
	EnvironmentID uuid.UUID
	Key           string
}

func (q *Queries) DeleteEnvironmentValue(ctx context.Context, arg DeleteEnvironmentValueParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentValue, arg.EnvironmentID, arg.Key)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT
	id, tenant_id, name, kind, description, created, last_modified, reconcile, labels, oidc_issuer, oidc_discovery_url
FROM
	environments
WHERE
	id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Reconcile,
		&i.Labels,
		&i.OidcIssuer,
		&i.OidcDiscoveryUrl,
	)
	return i, err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT
	id, tenant_id, name, kind, description, created, last_modified, reconcile, labels, oidc_issuer, oidc_discovery_url
FROM
	environments
WHERE
	tenant_id = $1
	AND name = $2
`

type GetEnvironmentByNameParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, arg.TenantID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Reconcile,
		&i.Labels,
		&i.OidcIssuer,
		&i.OidcDiscoveryUrl,
	)
	return i, err
}

const getEnvironmentValue = `-- name: GetEnvironmentValue :one
SELECT
	"environment_id",
	"key",
	"secret",
(
		CASE WHEN secret THEN
			CASE WHEN $1::BOOL THEN
				value
			ELSE
				'"*****"'
			END
		ELSE
			value
		END)::JSONB AS "value"
FROM
	environment_values
WHERE
	"environment_id" = $2
	AND "key" = $3
`

type GetEnvironmentValueParams struct {
	ShowSensitive bool
	EnvironmentID uuid.UUID
	Key           string
}

type GetEnvironmentValueRow struct {
	EnvironmentID uuid.UUID
	Key           string
	Secret        bool
	Value         []byte
}

func (q *Queries) GetEnvironmentValue(ctx context.Context, arg GetEnvironmentValueParams) (GetEnvironmentValueRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentValue, arg.ShowSensitive, arg.EnvironmentID, arg.Key)
	var i GetEnvironmentValueRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.Key,
		&i.Secret,
		&i.Value,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT
	id, name, description, created, last_modified, ci
FROM
	tenants
WHERE
	id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT
	id, name, description, created, last_modified, ci
FROM
	tenants
WHERE
	name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.LastModified,
		&i.Ci,
	)
	return i, err
}

const listEnvironmentValuesForKey = `-- name: ListEnvironmentValuesForKey :many
SELECT
	ev.environment_id,
	ev.key,
	ev.secret,
	ev.value,
	t.id AS tenant_id,
	t.name AS tenant_name,
	e.name AS environment_name
FROM
	environment_values ev
	JOIN environments e ON e.id = ev.environment_id
	JOIN tenants t ON t.id = e.tenant_id
WHERE
	ev.key = $1
ORDER BY
	e.name ASC
`

type ListEnvironmentValuesForKeyRow struct {
	EnvironmentID   uuid.UUID
	Key             string
	Secret          bool
	Value           []byte
	TenantID        uuid.UUID
	TenantName      string
	EnvironmentName string
}

func (q *Queries) ListEnvironmentValuesForKey(ctx context.Context, key string) ([]ListEnvironmentValuesForKeyRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentValuesForKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentValuesForKeyRow{}
	for rows.Next() {
		var i ListEnvironmentValuesForKeyRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Key,
			&i.Secret,
			&i.Value,
			&i.TenantID,
			&i.TenantName,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnvironmentLabels = `-- name: SetEnvironmentLabels :exec
UPDATE
	environments
SET
	labels = $1
WHERE
	id = $2
`

type SetEnvironmentLabelsParams struct {
	Labels types.EnvironmentLabels
	ID     uuid.UUID
}

func (q *Queries) SetEnvironmentLabels(ctx context.Context, arg SetEnvironmentLabelsParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentLabels, arg.Labels, arg.ID)
	return err
}

const setEnvironmentOIDC = `-- name: SetEnvironmentOIDC :exec
UPDATE
	environments
SET
	oidc_issuer = $1,
	oidc_discovery_url = $2
WHERE
	id = $3
`

type SetEnvironmentOIDCParams struct {
	OidcIssuer       *string
	OidcDiscoveryUrl *string
	ID               uuid.UUID
}

func (q *Queries) SetEnvironmentOIDC(ctx context.Context, arg SetEnvironmentOIDCParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentOIDC, arg.OidcIssuer, arg.OidcDiscoveryUrl, arg.ID)
	return err
}

const setEnvironmentValue = `-- name: SetEnvironmentValue :exec
INSERT INTO environment_values(
	"environment_id",
	"key",
	"value",
	"secret")
VALUES (
	$1,
	$2,
	$3,
	$4)
ON CONFLICT (
	"environment_id",
	"key")
	DO UPDATE SET
		"value" = $3,
		"secret" = $4
`

type SetEnvironmentValueParams struct {
	EnvironmentID uuid.UUID
	Key           string
	Value         []byte
	Secret        bool
}

func (q *Queries) SetEnvironmentValue(ctx context.Context, arg SetEnvironmentValueParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentValue,
		arg.EnvironmentID,
		arg.Key,
		arg.Value,
		arg.Secret,
	)
	return err
}
