{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1alpha3" }}
{{- $parts := splitList ":" .Values.fasitAddress }}
{{- $host := index $parts 0 }}
{{- $port := "443" }}
{{- if gt (len $parts) 1 }}{{ $port = index $parts 1 }}{{- end }}
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name }}-fasit
  labels:
    {{- include "fasitd.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
  - to:
    - fqdns:
      - {{ $host | quote }}
    ports:
    - protocol: TCP
      port: {{ $port | int }}
{{- end }}
