chart: oci://europe-north1-docker.pkg.dev/nais-io/nais/logging
source: https://github.com/nais/helm-charts/tree/main/charts/logging
version: 2.0.2
description: "Logging operator"
environmentKinds:
  - "tenant"
  - "onprem"
  - "legacy"
  - "management"
dependsOn:
  - allOf:
      - "monitoring"

config:
  fluentd.replicas:
    type: string
    displayName: Fluentd replicas
  fluentd.cpu.request:
    type: string
    displayName: Fluentd cpu request
  fluentd.memory:
    type: string
    displayName: Fluentd memory

mapping:
  # disable networkpolicies in onprem clusters
  networkPolicy.enabled:
    template: "false"
    ignoreKind:
      - management
      - tenant
      - legacy
