chart: prometheus
version: 15.6.0
repo: "https://prometheus-community.github.io/helm-charts"
config:
  alertmanager.ingress.enabled: bool
  alertmanager.ingress.hosts: string_array
  server.ingress.enabled: bool
  server.ingress.hosts: string_array
  server.baseURL: string
  server.persistentVolume.enabled: bool
