package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/graph/graphgen"
	"github.com/nais/fasit/internal/graph/model"
)

// Statuses is the resolver for the deploymentStatuses field.
func (r *deploymentResolver) Statuses(ctx context.Context, obj *model.Deployment) ([]*model.DeploymentStatus, error) {
	return r.Repo.V3DeploymentStatusesGet(ctx, obj.ID)
}

// Deployment is the resolver for the deployment field.
func (r *deploymentStatusResolver) Deployment(ctx context.Context, obj *model.DeploymentStatus) (*model.Deployment, error) {
	d, err := r.Repo.V3DeploymentGet(ctx, obj.DeploymentID)
	if err != nil {
		return nil, fmt.Errorf("get deployment: %w", err)
	}

	target := make([]*model.EnvironmentLabel, 0)
	for k, v := range d.Target {
		target = append(target, &model.EnvironmentLabel{
			Key:   k,
			Value: v,
		})
	}

	return &model.Deployment{
		ID:      d.ID,
		Target:  target,
		Created: d.Created,
		Feature: d.Feature,
	}, nil
}

// Environment is the resolver for the environment field.
func (r *deploymentStatusResolver) Environment(ctx context.Context, obj *model.DeploymentStatus) (*model.Environment, error) {
	return r.Repo.EnvironmentGet(ctx, obj.EnvironmentID)
}

// DeleteDeployment is the resolver for the deleteDeployment field.
func (r *mutationResolver) DeleteDeployment(ctx context.Context, deploymentID uuid.UUID) (bool, error) {
	if err := r.Repo.V3DeploymentDelete(ctx, deploymentID); err != nil {
		return false, fmt.Errorf("delete deployment: %w", err)
	}

	return true, nil
}

// Deployments is the resolver for the deployments field.
func (r *queryResolver) Deployments(ctx context.Context, feature *string) ([]*model.Deployment, error) {
	if feature != nil {
		return r.Repo.V3DeploymentsGetByFeature(ctx, *feature)
	}

	return r.Repo.V3DeploymentsGet(ctx)
}

// Deployment returns graphgen.DeploymentResolver implementation.
func (r *Resolver) Deployment() graphgen.DeploymentResolver { return &deploymentResolver{r} }

// DeploymentStatus returns graphgen.DeploymentStatusResolver implementation.
func (r *Resolver) DeploymentStatus() graphgen.DeploymentStatusResolver {
	return &deploymentStatusResolver{r}
}

type (
	deploymentResolver       struct{ *Resolver }
	deploymentStatusResolver struct{ *Resolver }
)
