package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/graph/graphgen"
	"github.com/nais/fasit/internal/graph/model"
)

// ID is the resolver for the id field.
func (r *statusResolver) ID(ctx context.Context, obj *model.Status) (uuid.UUID, error) {
	return fakeUUID(obj.EnvironmentID.String(), obj.Feature), nil
}

// Log is the resolver for the log field.
func (r *statusResolver) Log(ctx context.Context, obj *model.Status) ([]*model.LogLine, error) {
	return r.Repo.LogsGet(ctx, obj.DeployInstructionID)
}

// Logs is the resolver for the logs field.
func (r *subscriptionResolver) Logs(ctx context.Context, environmentID uuid.UUID, featureName string, lastLogID *string) (<-chan *model.LogLine, error) {
	di, err := r.Repo.DeployInstructionsLatestForFeature(ctx, environmentID, featureName)
	if err != nil {
		return nil, err
	}

	if di == nil {
		return nil, fmt.Errorf("no deploy instructions found for feature %s in environment %s", featureName, environmentID)
	}

	lastID := 0
	extraLogs := []*model.LogLine{}
	if lastLogID != nil {
		parts := strings.Split(*lastLogID, "-")
		if len(parts) == 1 {
			return nil, fmt.Errorf("invalid lastLogID: %s", *lastLogID)
		}

		lastID, err = strconv.Atoi(parts[len(parts)-1])
		if err != nil {
			return nil, fmt.Errorf("invalid lastLogID: %s", *lastLogID)
		}

		logs, err := r.Repo.LogsGet(ctx, di.ID)
		if err != nil {
			return nil, err
		}

		for _, log := range logs {
			if log.IntID > lastID {
				extraLogs = append(extraLogs, log)
			}
		}
	}

	notch := make(chan *model.LogLine, 10)
	r.logNotifier.Subscribe(di.ID.String(), notch)

	ret := make(chan *model.LogLine, 1)

	go func() {
		for _, log := range extraLogs {
			select {
			case <-ctx.Done():
			case ret <- log:
			}
		}

		for {
			select {
			case <-ctx.Done():
				r.logNotifier.Unsubscribe(di.ID.String(), notch)
				close(ret)
				close(notch)
				return
			case msg, ok := <-notch:
				if ok && msg.IntID > lastID {
					ret <- msg
				}
			}
		}
	}()

	return ret, nil
}

// Updates is the resolver for the updates field.
func (r *subscriptionResolver) Updates(ctx context.Context) (<-chan model.Update, error) {
	ret := make(chan model.Update, 1)
	r.diNotifier.Subscribe(ret)

	go func() {
		<-ctx.Done()
		r.diNotifier.Unsubscribe(ret)
		close(ret)
	}()

	return ret, nil
}

// Status returns graphgen.StatusResolver implementation.
func (r *Resolver) Status() graphgen.StatusResolver { return &statusResolver{r} }

// Subscription returns graphgen.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphgen.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	statusResolver       struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
