// Code generated by sqlc. DO NOT EDIT.
// source: deploy_instructions.sql

package featureassignmentsql

import (
	"context"

	"github.com/google/uuid"
)

const createDeployInstruction = `-- name: CreateDeployInstruction :one
INSERT INTO deploy_instructions(
	environment_id,
	feature_name,
	feature_version,
	hash,
	"values",
	feature_assignment_id)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6)
RETURNING
	id
`

type CreateDeployInstructionParams struct {
	EnvironmentID       uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Hash                string
	Values              []byte
	FeatureAssignmentID *uuid.UUID
}

func (q *Queries) CreateDeployInstruction(ctx context.Context, arg CreateDeployInstructionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDeployInstruction,
		arg.EnvironmentID,
		arg.FeatureName,
		arg.FeatureVersion,
		arg.Hash,
		arg.Values,
		arg.FeatureAssignmentID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDeployInstructionByFeatureAssignmentAndEnvironmentID = `-- name: GetDeployInstructionByFeatureAssignmentAndEnvironmentID :one
SELECT
	di.id, di.environment_id, di.feature_name, di.feature_version, di.status, di.hash, di.created, di.last_modified, di.values, di.feature_assignment_id,
	e.name AS environment_name,
	t.name AS tenant_name
FROM
	deploy_instructions di
	JOIN environments e ON e.id = di.environment_id
	JOIN tenants t ON t.id = e.tenant_id
WHERE
	di.feature_assignment_id = $1
	AND di.environment_id = $2
`

type GetDeployInstructionByFeatureAssignmentAndEnvironmentIDParams struct {
	FeatureAssignmentID *uuid.UUID
	EnvironmentID       uuid.UUID
}

type GetDeployInstructionByFeatureAssignmentAndEnvironmentIDRow struct {
	DeployInstruction DeployInstruction
	EnvironmentName   string
	TenantName        string
}

func (q *Queries) GetDeployInstructionByFeatureAssignmentAndEnvironmentID(ctx context.Context, arg GetDeployInstructionByFeatureAssignmentAndEnvironmentIDParams) (GetDeployInstructionByFeatureAssignmentAndEnvironmentIDRow, error) {
	row := q.db.QueryRow(ctx, getDeployInstructionByFeatureAssignmentAndEnvironmentID, arg.FeatureAssignmentID, arg.EnvironmentID)
	var i GetDeployInstructionByFeatureAssignmentAndEnvironmentIDRow
	err := row.Scan(
		&i.DeployInstruction.ID,
		&i.DeployInstruction.EnvironmentID,
		&i.DeployInstruction.FeatureName,
		&i.DeployInstruction.FeatureVersion,
		&i.DeployInstruction.Status,
		&i.DeployInstruction.Hash,
		&i.DeployInstruction.Created,
		&i.DeployInstruction.LastModified,
		&i.DeployInstruction.Values,
		&i.DeployInstruction.FeatureAssignmentID,
		&i.EnvironmentName,
		&i.TenantName,
	)
	return i, err
}

const invalidateDeployInstruction = `-- name: InvalidateDeployInstruction :exec
UPDATE
	deploy_instructions
SET
	hash = '',
	status = 'invalidated'
WHERE
	id =(
		SELECT
			di.id
		FROM
			deploy_instructions di
		WHERE
			di.feature_name = $1
			AND di.environment_id = $2
		ORDER BY
			di.created DESC
		LIMIT 1)
`

type InvalidateDeployInstructionParams struct {
	FeatureName   string
	EnvironmentID uuid.UUID
}

func (q *Queries) InvalidateDeployInstruction(ctx context.Context, arg InvalidateDeployInstructionParams) error {
	_, err := q.db.Exec(ctx, invalidateDeployInstruction, arg.FeatureName, arg.EnvironmentID)
	return err
}

const updateDeployInstructionStatus = `-- name: UpdateDeployInstructionStatus :exec
UPDATE
	deploy_instructions
SET
	status = $1
WHERE
	id = $2
`

type UpdateDeployInstructionStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateDeployInstructionStatus(ctx context.Context, arg UpdateDeployInstructionStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeployInstructionStatus, arg.Status, arg.ID)
	return err
}
