// Code generated by sqlc. DO NOT EDIT.
// source: feature_assignments.sql

package featureassignmentsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

const createFeatureAssignment = `-- name: CreateFeatureAssignment :one
INSERT INTO feature_assignments(
	feature_name,
	version,
	target,
	gh_ref,
	description)
VALUES (
	$1::TEXT,
	$2,
	$3,
	$4,
	$5)
RETURNING
	id, feature_name, version, target, created, gh_ref, description, active
`

type CreateFeatureAssignmentParams struct {
	FeatureName string
	Version     string
	Target      types.EnvironmentLabels
	GhRef       []byte
	Description *string
}

func (q *Queries) CreateFeatureAssignment(ctx context.Context, arg CreateFeatureAssignmentParams) (FeatureAssignment, error) {
	row := q.db.QueryRow(ctx, createFeatureAssignment,
		arg.FeatureName,
		arg.Version,
		arg.Target,
		arg.GhRef,
		arg.Description,
	)
	var i FeatureAssignment
	err := row.Scan(
		&i.ID,
		&i.FeatureName,
		&i.Version,
		&i.Target,
		&i.Created,
		&i.GhRef,
		&i.Description,
		&i.Active,
	)
	return i, err
}

const deactivateActiveFeatureAssignmentForTarget = `-- name: DeactivateActiveFeatureAssignmentForTarget :exec
UPDATE
	feature_assignments
SET
	active = FALSE
WHERE
	feature_name = $1::TEXT
	AND target = $2
	AND active = TRUE
`

type DeactivateActiveFeatureAssignmentForTargetParams struct {
	FeatureName string
	Target      types.EnvironmentLabels
}

func (q *Queries) DeactivateActiveFeatureAssignmentForTarget(ctx context.Context, arg DeactivateActiveFeatureAssignmentForTargetParams) error {
	_, err := q.db.Exec(ctx, deactivateActiveFeatureAssignmentForTarget, arg.FeatureName, arg.Target)
	return err
}

const deactivateFeatureAssignment = `-- name: DeactivateFeatureAssignment :exec
UPDATE
	feature_assignments
SET
	active = FALSE
WHERE
	id = $1::UUID
`

func (q *Queries) DeactivateFeatureAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateFeatureAssignment, id)
	return err
}

const deactivateFeatureAssignmentsByFeatureAndTarget = `-- name: DeactivateFeatureAssignmentsByFeatureAndTarget :exec
UPDATE
	feature_assignments
SET
	active = FALSE
WHERE
	feature_name = $1::TEXT
	AND target = $2
	AND active = TRUE
`

type DeactivateFeatureAssignmentsByFeatureAndTargetParams struct {
	FeatureName string
	Target      types.EnvironmentLabels
}

func (q *Queries) DeactivateFeatureAssignmentsByFeatureAndTarget(ctx context.Context, arg DeactivateFeatureAssignmentsByFeatureAndTargetParams) error {
	_, err := q.db.Exec(ctx, deactivateFeatureAssignmentsByFeatureAndTarget, arg.FeatureName, arg.Target)
	return err
}

const getFeatureAssignment = `-- name: GetFeatureAssignment :one
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.id = $1::UUID
`

type GetFeatureAssignmentRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) GetFeatureAssignment(ctx context.Context, id uuid.UUID) (GetFeatureAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getFeatureAssignment, id)
	var i GetFeatureAssignmentRow
	err := row.Scan(
		&i.FeatureAssignment.ID,
		&i.FeatureAssignment.FeatureName,
		&i.FeatureAssignment.Version,
		&i.FeatureAssignment.Target,
		&i.FeatureAssignment.Created,
		&i.FeatureAssignment.GhRef,
		&i.FeatureAssignment.Description,
		&i.FeatureAssignment.Active,
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
	)
	return i, err
}

const hasActiveAssignments = `-- name: HasActiveAssignments :one
SELECT
	EXISTS (
		SELECT
			1
		FROM
			feature_assignments
		WHERE
			feature_name = $1::TEXT
			AND active = TRUE) AS has_active
`

func (q *Queries) HasActiveAssignments(ctx context.Context, featureName string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAssignments, featureName)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const listAllFeatureAssignments = `-- name: ListAllFeatureAssignments :many
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN ( SELECT DISTINCT ON (feature_name, target)
			id
		FROM
			feature_assignments
		ORDER BY
			feature_name,
			target,
			active DESC,
			created DESC) best ON d.id = best.id
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
	ORDER BY
		d.created DESC
`

type ListAllFeatureAssignmentsRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) ListAllFeatureAssignments(ctx context.Context) ([]ListAllFeatureAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listAllFeatureAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllFeatureAssignmentsRow{}
	for rows.Next() {
		var i ListAllFeatureAssignmentsRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFeatureAssignmentsByFeature = `-- name: ListAllFeatureAssignmentsByFeature :many
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	fd.name = $1::TEXT
ORDER BY
	d.active DESC,
	d.created DESC
`

type ListAllFeatureAssignmentsByFeatureRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) ListAllFeatureAssignmentsByFeature(ctx context.Context, featureName string) ([]ListAllFeatureAssignmentsByFeatureRow, error) {
	rows, err := q.db.Query(ctx, listAllFeatureAssignmentsByFeature, featureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllFeatureAssignmentsByFeatureRow{}
	for rows.Next() {
		var i ListAllFeatureAssignmentsByFeatureRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionStatuses = `-- name: ListDecisionStatuses :many
SELECT
	environment_id,
	action,
	message,
	created
FROM
	decision_status
WHERE
	feature_assignment_id = $1::UUID
ORDER BY
	environment_id ASC
`

type ListDecisionStatusesRow struct {
	EnvironmentID uuid.UUID
	Action        string
	Message       string
	Created       time.Time
}

// Latest reconciler decision per environment for a feature assignment. The
// deploy rollout state and disabled-feature membership are joined in Go
// (ReconcileStatuses).
func (q *Queries) ListDecisionStatuses(ctx context.Context, featureAssignmentID uuid.UUID) ([]ListDecisionStatusesRow, error) {
	rows, err := q.db.Query(ctx, listDecisionStatuses, featureAssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecisionStatusesRow{}
	for rows.Next() {
		var i ListDecisionStatusesRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Action,
			&i.Message,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployStatuses = `-- name: ListDeployStatuses :many
SELECT
	environment_id,
	status,
	created
FROM
	deploy_status
WHERE
	feature_assignment_id = $1::UUID
ORDER BY
	environment_id ASC
`

type ListDeployStatusesRow struct {
	EnvironmentID uuid.UUID
	Status        string
	Created       time.Time
}

// Latest deploy rollout state per environment for a feature assignment.
func (q *Queries) ListDeployStatuses(ctx context.Context, featureAssignmentID uuid.UUID) ([]ListDeployStatusesRow, error) {
	rows, err := q.db.Query(ctx, listDeployStatuses, featureAssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployStatusesRow{}
	for rows.Next() {
		var i ListDeployStatusesRow
		if err := rows.Scan(&i.EnvironmentID, &i.Status, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledEnvironments = `-- name: ListDisabledEnvironments :many
SELECT
	e.id AS environment_id,
	df.disabled_at
FROM
	environments e
	JOIN disabled_features df ON df.environment_id = e.id
	JOIN feature_assignments d ON df.feature = d.feature_name
WHERE
	e.labels @> d.target
	AND d.id = $1::UUID
ORDER BY
	environment_id ASC
`

type ListDisabledEnvironmentsRow struct {
	EnvironmentID uuid.UUID
	DisabledAt    time.Time
}

// Environments the assignment targets where the feature is disabled.
func (q *Queries) ListDisabledEnvironments(ctx context.Context, featureAssignmentID uuid.UUID) ([]ListDisabledEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listDisabledEnvironments, featureAssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisabledEnvironmentsRow{}
	for rows.Next() {
		var i ListDisabledEnvironmentsRow
		if err := rows.Scan(&i.EnvironmentID, &i.DisabledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureAssignmentsByFeature = `-- name: ListFeatureAssignmentsByFeature :many
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	fd.name = $1::TEXT
	AND d.active = TRUE
ORDER BY
	d.created DESC
`

type ListFeatureAssignmentsByFeatureRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) ListFeatureAssignmentsByFeature(ctx context.Context, featureName string) ([]ListFeatureAssignmentsByFeatureRow, error) {
	rows, err := q.db.Query(ctx, listFeatureAssignmentsByFeature, featureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureAssignmentsByFeatureRow{}
	for rows.Next() {
		var i ListFeatureAssignmentsByFeatureRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureAssignmentsForEnvironment = `-- name: ListFeatureAssignmentsForEnvironment :many
SELECT DISTINCT ON (d.feature_name, d.target)
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details,
(df.feature IS NOT NULL)::BOOL AS disabled
FROM
	feature_assignments d
	JOIN environments e ON e.id = $1::UUID
		AND e.labels @> d.target
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
	LEFT JOIN disabled_features df ON df.environment_id = e.id
		AND df.feature = d.feature_name
WHERE
	d.active = TRUE
ORDER BY
	d.feature_name,
	d.target,
	d.created DESC
`

type ListFeatureAssignmentsForEnvironmentRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
	Disabled          bool
}

func (q *Queries) ListFeatureAssignmentsForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]ListFeatureAssignmentsForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listFeatureAssignmentsForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureAssignmentsForEnvironmentRow{}
	for rows.Next() {
		var i ListFeatureAssignmentsForEnvironmentRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureAssignmentsForFeatureInEnvironment = `-- name: ListFeatureAssignmentsForFeatureInEnvironment :many
SELECT DISTINCT ON (d.feature_name, d.target)
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN environments e ON e.id = $1::UUID
		AND e.labels @> d.target
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.feature_name = $2::TEXT
	AND d.active = TRUE
ORDER BY
	d.feature_name,
	d.target,
	d.created DESC
`

type ListFeatureAssignmentsForFeatureInEnvironmentParams struct {
	EnvironmentID uuid.UUID
	FeatureName   string
}

type ListFeatureAssignmentsForFeatureInEnvironmentRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) ListFeatureAssignmentsForFeatureInEnvironment(ctx context.Context, arg ListFeatureAssignmentsForFeatureInEnvironmentParams) ([]ListFeatureAssignmentsForFeatureInEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listFeatureAssignmentsForFeatureInEnvironment, arg.EnvironmentID, arg.FeatureName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeatureAssignmentsForFeatureInEnvironmentRow{}
	for rows.Next() {
		var i ListFeatureAssignmentsForFeatureInEnvironmentRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFeatureAssignments = `-- name: ListRecentFeatureAssignments :many
SELECT
	d.id, d.feature_name, d.version, d.target, d.created, d.gh_ref, d.description, d.active,
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
	ORDER BY
		d.created DESC
	LIMIT 50
`

type ListRecentFeatureAssignmentsRow struct {
	FeatureAssignment FeatureAssignment
	FeatureDatum      FeatureDatum
}

func (q *Queries) ListRecentFeatureAssignments(ctx context.Context) ([]ListRecentFeatureAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listRecentFeatureAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentFeatureAssignmentsRow{}
	for rows.Next() {
		var i ListRecentFeatureAssignmentsRow
		if err := rows.Scan(
			&i.FeatureAssignment.ID,
			&i.FeatureAssignment.FeatureName,
			&i.FeatureAssignment.Version,
			&i.FeatureAssignment.Target,
			&i.FeatureAssignment.Created,
			&i.FeatureAssignment.GhRef,
			&i.FeatureAssignment.Description,
			&i.FeatureAssignment.Active,
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
