// Code generated by sqlc. DO NOT EDIT.

package featureassignmentsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nais/fasit/internal/database/types"
)

type DeployInstruction struct {
	ID                  uuid.UUID
	EnvironmentID       uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Status              string
	Hash                string
	Created             pgtype.Timestamptz
	LastModified        pgtype.Timestamptz
	Values              []byte
	FeatureAssignmentID *uuid.UUID
}

type FeatureAssignment struct {
	ID          uuid.UUID
	FeatureName string
	Version     string
	Target      types.EnvironmentLabels
	Created     pgtype.Timestamptz
	GhRef       []byte
	Description *string
	Active      bool
}

type FeatureDatum struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []types.EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

type FeatureReconcileStatus struct {
	FeatureAssignmentID uuid.UUID
	EnvironmentID       uuid.UUID
	Status              string
	Message             string
	LastModified        pgtype.Timestamptz
	Created             pgtype.Timestamptz
}

type ReleaseStatus struct {
	EnvironmentID uuid.UUID
	Feature       string
	Version       string
	Status        string
	Revision      int32
	LastDeployed  pgtype.Timestamptz
	Created       pgtype.Timestamptz
	LastModified  pgtype.Timestamptz
}
