// Code generated by sqlc. DO NOT EDIT.

package featureassignmentsql

import (
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type FeatureAssignment struct {
	ID          uuid.UUID
	FeatureName string
	Version     string
	Target      types.EnvironmentLabels
	Created     time.Time
	GhRef       []byte
	Description *string
	Active      bool
}

type FeatureDatum struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []types.EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

type FeatureReconcileStatus struct {
	FeatureAssignmentID uuid.UUID
	EnvironmentID       uuid.UUID
	Status              string
	Message             string
	LastModified        time.Time
	Created             time.Time
}
