// Code generated by sqlc. DO NOT EDIT.
// source: reconciler.sql

package reconcilersql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type AppendDecisionsParams struct {
	EnvironmentID       uuid.UUID
	FeatureAssignmentID uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Action              string
	Message             string
}

const appendDeployStatus = `-- name: AppendDeployStatus :exec
INSERT INTO deploy_log(
	diid,
	environment_id,
	feature_assignment_id,
	feature_name,
	feature_version,
	status,
	hash)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7)
`

type AppendDeployStatusParams struct {
	Diid                uuid.UUID
	EnvironmentID       uuid.UUID
	FeatureAssignmentID uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Status              string
	Hash                string
}

func (q *Queries) AppendDeployStatus(ctx context.Context, arg AppendDeployStatusParams) error {
	_, err := q.db.Exec(ctx, appendDeployStatus,
		arg.Diid,
		arg.EnvironmentID,
		arg.FeatureAssignmentID,
		arg.FeatureName,
		arg.FeatureVersion,
		arg.Status,
		arg.Hash,
	)
	return err
}

type AppendDeploysParams struct {
	Diid                uuid.UUID
	EnvironmentID       uuid.UUID
	FeatureAssignmentID uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Status              string
	Hash                string
	Vals                []byte
}

const deleteReleaseStatusesInEnvironment = `-- name: DeleteReleaseStatusesInEnvironment :exec
DELETE FROM release_statuses
WHERE environment_id = $1
`

func (q *Queries) DeleteReleaseStatusesInEnvironment(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReleaseStatusesInEnvironment, environmentID)
	return err
}

const latestDeployByDIID = `-- name: LatestDeployByDIID :one
SELECT
	environment_id,
	feature_assignment_id,
	feature_name,
	feature_version,
	hash,
	created
FROM
	deploy_log
WHERE
	diid = $1
ORDER BY
	created DESC,
	id DESC
LIMIT 1
`

type LatestDeployByDIIDRow struct {
	EnvironmentID       uuid.UUID
	FeatureAssignmentID uuid.UUID
	FeatureName         string
	FeatureVersion      string
	Hash                string
	Created             time.Time
}

func (q *Queries) LatestDeployByDIID(ctx context.Context, diid uuid.UUID) (LatestDeployByDIIDRow, error) {
	row := q.db.QueryRow(ctx, latestDeployByDIID, diid)
	var i LatestDeployByDIIDRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.FeatureAssignmentID,
		&i.FeatureName,
		&i.FeatureVersion,
		&i.Hash,
		&i.Created,
	)
	return i, err
}

const listAllEnvConfigs = `-- name: ListAllEnvConfigs :many
SELECT
	id,
	environment_id,
	feature,
	key,
	value,
	secret,
	created
FROM
	configurations_environment
ORDER BY
	environment_id,
	feature,
	key
`

type ListAllEnvConfigsRow struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	Feature       string
	Key           string
	Value         []byte
	Secret        bool
	Created       time.Time
}

func (q *Queries) ListAllEnvConfigs(ctx context.Context) ([]ListAllEnvConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAllEnvConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEnvConfigsRow{}
	for rows.Next() {
		var i ListAllEnvConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Secret,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllEnvironmentValues = `-- name: ListAllEnvironmentValues :many
SELECT
	ev.environment_id,
	ev.key,
	ev.value
FROM
	environment_values ev
ORDER BY
	ev.environment_id,
	ev.key
`

type ListAllEnvironmentValuesRow struct {
	EnvironmentID uuid.UUID
	Key           string
	Value         []byte
}

func (q *Queries) ListAllEnvironmentValues(ctx context.Context) ([]ListAllEnvironmentValuesRow, error) {
	rows, err := q.db.Query(ctx, listAllEnvironmentValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEnvironmentValuesRow{}
	for rows.Next() {
		var i ListAllEnvironmentValuesRow
		if err := rows.Scan(&i.EnvironmentID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGlobalConfigs = `-- name: ListAllGlobalConfigs :many
SELECT
	id,
	feature,
	key,
	value,
	secret,
	created
FROM
	configurations_global
ORDER BY
	feature,
	key
`

type ListAllGlobalConfigsRow struct {
	ID      uuid.UUID
	Feature string
	Key     string
	Value   []byte
	Secret  bool
	Created time.Time
}

func (q *Queries) ListAllGlobalConfigs(ctx context.Context) ([]ListAllGlobalConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAllGlobalConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGlobalConfigsRow{}
	for rows.Next() {
		var i ListAllGlobalConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Secret,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTenantEnvironments = `-- name: ListAllTenantEnvironments :many
SELECT
	e.id,
	e.name,
	e.kind,
	e.labels,
	e.reconcile,
	t.id AS tenant_id,
	t.name AS tenant_name
FROM
	environments e
	JOIN tenants t ON t.id = e.tenant_id
ORDER BY
	t.name,
	e.name
`

type ListAllTenantEnvironmentsRow struct {
	ID         uuid.UUID
	Name       string
	Kind       types.EnvironmentKind
	Labels     types.EnvironmentLabels
	Reconcile  bool
	TenantID   uuid.UUID
	TenantName string
}

func (q *Queries) ListAllTenantEnvironments(ctx context.Context) ([]ListAllTenantEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listAllTenantEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTenantEnvironmentsRow{}
	for rows.Next() {
		var i ListAllTenantEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Labels,
			&i.Reconcile,
			&i.TenantID,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployedFeatures = `-- name: ListDeployedFeatures :many
SELECT
	environment_id,
	feature_name
FROM
	deploy_status
WHERE
	status = 'deployed'
ORDER BY
	environment_id,
	feature_name
`

type ListDeployedFeaturesRow struct {
	EnvironmentID uuid.UUID
	FeatureName   string
}

func (q *Queries) ListDeployedFeatures(ctx context.Context) ([]ListDeployedFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listDeployedFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployedFeaturesRow{}
	for rows.Next() {
		var i ListDeployedFeaturesRow
		if err := rows.Scan(&i.EnvironmentID, &i.FeatureName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledFeatures = `-- name: ListDisabledFeatures :many
SELECT
	environment_id,
	feature
FROM
	disabled_features
ORDER BY
	environment_id,
	feature
`

type ListDisabledFeaturesRow struct {
	EnvironmentID uuid.UUID
	Feature       string
}

func (q *Queries) ListDisabledFeatures(ctx context.Context) ([]ListDisabledFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listDisabledFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisabledFeaturesRow{}
	for rows.Next() {
		var i ListDisabledFeaturesRow
		if err := rows.Scan(&i.EnvironmentID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthStatuses = `-- name: ListHealthStatuses :many
SELECT
	environment_id,
	reported_at
FROM
	health_statuses
ORDER BY
	environment_id
`

func (q *Queries) ListHealthStatuses(ctx context.Context) ([]HealthStatus, error) {
	rows, err := q.db.Query(ctx, listHealthStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthStatus{}
	for rows.Next() {
		var i HealthStatus
		if err := rows.Scan(&i.EnvironmentID, &i.ReportedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDecisions = `-- name: ListLatestDecisions :many
SELECT
	environment_id,
	feature_name,
	feature_assignment_id,
	feature_version,
	action,
	message
FROM
	decision_status
ORDER BY
	environment_id,
	feature_name
`

type ListLatestDecisionsRow struct {
	EnvironmentID       uuid.UUID
	FeatureName         string
	FeatureAssignmentID uuid.UUID
	FeatureVersion      string
	Action              string
	Message             string
}

func (q *Queries) ListLatestDecisions(ctx context.Context) ([]ListLatestDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listLatestDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestDecisionsRow{}
	for rows.Next() {
		var i ListLatestDecisionsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.FeatureName,
			&i.FeatureAssignmentID,
			&i.FeatureVersion,
			&i.Action,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDeploys = `-- name: ListLatestDeploys :many
SELECT
	environment_id,
	feature_name,
	hash,
	status,
	feature_assignment_id
FROM
	deploy_status
ORDER BY
	environment_id,
	feature_name
`

type ListLatestDeploysRow struct {
	EnvironmentID       uuid.UUID
	FeatureName         string
	Hash                string
	Status              string
	FeatureAssignmentID uuid.UUID
}

func (q *Queries) ListLatestDeploys(ctx context.Context) ([]ListLatestDeploysRow, error) {
	rows, err := q.db.Query(ctx, listLatestDeploys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestDeploysRow{}
	for rows.Next() {
		var i ListLatestDeploysRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.FeatureName,
			&i.Hash,
			&i.Status,
			&i.FeatureAssignmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestFeatureAssignments = `-- name: ListLatestFeatureAssignments :many
SELECT DISTINCT ON (d.feature_name, d.target)
	d.id,
	d.feature_name,
	d.version,
	d.target,
	d.created,
	fd.name AS fd_name,
	fd.version AS fd_version,
	fd.chart,
	fd.description,
	fd.source,
	fd.kinds,
	fd.dependencies,
	fd."values",
	fd.default_values,
	fd.timeout,
	fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.active = TRUE
ORDER BY
	d.feature_name,
	d.target,
	d.created DESC
`

type ListLatestFeatureAssignmentsRow struct {
	ID            uuid.UUID
	FeatureName   string
	Version       string
	Target        types.EnvironmentLabels
	Created       time.Time
	FdName        string
	FdVersion     string
	Chart         string
	Description   string
	Source        string
	Kinds         []types.EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

func (q *Queries) ListLatestFeatureAssignments(ctx context.Context) ([]ListLatestFeatureAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listLatestFeatureAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestFeatureAssignmentsRow{}
	for rows.Next() {
		var i ListLatestFeatureAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeatureName,
			&i.Version,
			&i.Target,
			&i.Created,
			&i.FdName,
			&i.FdVersion,
			&i.Chart,
			&i.Description,
			&i.Source,
			&i.Kinds,
			&i.Dependencies,
			&i.Values,
			&i.DefaultValues,
			&i.Timeout,
			&i.TplDetails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReleaseStatus = `-- name: SetReleaseStatus :exec
INSERT INTO release_statuses(
	environment_id,
	feature,
	version,
	status,
	revision,
	last_deployed)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6)
ON CONFLICT (
	environment_id,
	feature)
	DO UPDATE SET
		version = EXCLUDED.version,
		status = EXCLUDED.status,
		revision = EXCLUDED.revision,
		last_deployed = EXCLUDED.last_deployed
`

type SetReleaseStatusParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Version       string
	Status        string
	Revision      int32
	LastDeployed  time.Time
}

func (q *Queries) SetReleaseStatus(ctx context.Context, arg SetReleaseStatusParams) error {
	_, err := q.db.Exec(ctx, setReleaseStatus,
		arg.EnvironmentID,
		arg.Feature,
		arg.Version,
		arg.Status,
		arg.Revision,
		arg.LastDeployed,
	)
	return err
}

const timeoutPendingDeploys = `-- name: TimeoutPendingDeploys :exec
INSERT INTO deploy_log(
	diid,
	environment_id,
	feature_assignment_id,
	feature_name,
	feature_version,
	status,
	hash)
SELECT
	diid,
	environment_id,
	feature_assignment_id,
	feature_name,
	feature_version,
	'failed',
	hash
FROM
	deploy_status
WHERE
	status IN ('sent', 'installing')
	AND created < NOW() - INTERVAL '1 hour'
`

func (q *Queries) TimeoutPendingDeploys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, timeoutPendingDeploys)
	return err
}
