// Code generated by sqlc. DO NOT EDIT.
// source: batch.go

package featuresql

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const logsCreate = `-- name: LogsCreate :batchexec
INSERT INTO logs(
	deploy_instruction,
	TIME,
	message,
	kind)
VALUES (
	$1,
	$2,
	$3,
	$4)
`

type LogsCreateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LogsCreateParams struct {
	DeployInstruction uuid.UUID
	Time              pgtype.Timestamptz
	Message           string
	Kind              string
}

func (q *Queries) LogsCreate(ctx context.Context, arg []LogsCreateParams) *LogsCreateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DeployInstruction,
			a.Time,
			a.Message,
			a.Kind,
		}
		batch.Queue(logsCreate, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LogsCreateBatchResults{br, len(arg), false}
}

func (b *LogsCreateBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LogsCreateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
