// Code generated by sqlc. DO NOT EDIT.
// source: configurations.sql

package featuresql

import (
	"context"

	"github.com/google/uuid"
)

const deleteEnvConfig = `-- name: DeleteEnvConfig :exec
DELETE FROM configurations_environment
WHERE id = $1
`

func (q *Queries) DeleteEnvConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvConfig, id)
	return err
}

const deleteGlobalConfig = `-- name: DeleteGlobalConfig :exec
DELETE FROM configurations_global
WHERE id = $1
`

func (q *Queries) DeleteGlobalConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGlobalConfig, id)
	return err
}

const getEnvConfigByID = `-- name: GetEnvConfigByID :one
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	id = $1
`

func (q *Queries) GetEnvConfigByID(ctx context.Context, id uuid.UUID) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvConfigByID, id)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const getEnvConfigByKey = `-- name: GetEnvConfigByKey :one
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	environment_id = $1
	AND feature = $2
	AND key = $3
`

type GetEnvConfigByKeyParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Key           string
}

func (q *Queries) GetEnvConfigByKey(ctx context.Context, arg GetEnvConfigByKeyParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvConfigByKey, arg.EnvironmentID, arg.Feature, arg.Key)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const getGlobalConfigByID = `-- name: GetGlobalConfigByID :one
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	id = $1
`

func (q *Queries) GetGlobalConfigByID(ctx context.Context, id uuid.UUID) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, getGlobalConfigByID, id)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const getGlobalConfigByKey = `-- name: GetGlobalConfigByKey :one
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	feature = $1
	AND key = $2
`

type GetGlobalConfigByKeyParams struct {
	Feature string
	Key     string
}

func (q *Queries) GetGlobalConfigByKey(ctx context.Context, arg GetGlobalConfigByKeyParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, getGlobalConfigByKey, arg.Feature, arg.Key)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const listAllEnvConfigByFeature = `-- name: ListAllEnvConfigByFeature :many
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	feature = $1
ORDER BY
	environment_id,
	key ASC
`

func (q *Queries) ListAllEnvConfigByFeature(ctx context.Context, feature string) ([]ConfigurationsEnvironment, error) {
	rows, err := q.db.Query(ctx, listAllEnvConfigByFeature, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsEnvironment{}
	for rows.Next() {
		var i ConfigurationsEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvConfigByFeature = `-- name: ListEnvConfigByFeature :many
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	feature = $1
	AND environment_id = $2
ORDER BY
	key ASC
`

type ListEnvConfigByFeatureParams struct {
	Feature       string
	EnvironmentID uuid.UUID
}

func (q *Queries) ListEnvConfigByFeature(ctx context.Context, arg ListEnvConfigByFeatureParams) ([]ConfigurationsEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvConfigByFeature, arg.Feature, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsEnvironment{}
	for rows.Next() {
		var i ConfigurationsEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalConfigByFeature = `-- name: ListGlobalConfigByFeature :many
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	feature = $1
ORDER BY
	key ASC
`

func (q *Queries) ListGlobalConfigByFeature(ctx context.Context, feature string) ([]ConfigurationsGlobal, error) {
	rows, err := q.db.Query(ctx, listGlobalConfigByFeature, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsGlobal{}
	for rows.Next() {
		var i ConfigurationsGlobal
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvConfig = `-- name: UpdateEnvConfig :one
UPDATE
	configurations_environment
SET
	description = $1,
	value = $2
WHERE
	id = $3
RETURNING
	id, feature, key, value, description, secret, created, environment_id
`

type UpdateEnvConfigParams struct {
	Description *string
	Value       []byte
	ID          uuid.UUID
}

func (q *Queries) UpdateEnvConfig(ctx context.Context, arg UpdateEnvConfigParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, updateEnvConfig, arg.Description, arg.Value, arg.ID)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const updateGlobalConfig = `-- name: UpdateGlobalConfig :one
UPDATE
	configurations_global
SET
	description = $1,
	value = $2
WHERE
	id = $3
RETURNING
	id, feature, key, value, description, secret, created
`

type UpdateGlobalConfigParams struct {
	Description *string
	Value       []byte
	ID          uuid.UUID
}

func (q *Queries) UpdateGlobalConfig(ctx context.Context, arg UpdateGlobalConfigParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, updateGlobalConfig, arg.Description, arg.Value, arg.ID)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const upsertEnvConfig = `-- name: UpsertEnvConfig :one
INSERT INTO configurations_environment(
	environment_id,
	feature,
	description,
	secret,
	key,
	value)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6)
ON CONFLICT (
	environment_id,
	feature,
	key)
	DO UPDATE SET
		value = EXCLUDED.value,
		description = EXCLUDED.description
	RETURNING
		id, feature, key, value, description, secret, created, environment_id
`

type UpsertEnvConfigParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Description   *string
	Secret        bool
	Key           string
	Value         []byte
}

func (q *Queries) UpsertEnvConfig(ctx context.Context, arg UpsertEnvConfigParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, upsertEnvConfig,
		arg.EnvironmentID,
		arg.Feature,
		arg.Description,
		arg.Secret,
		arg.Key,
		arg.Value,
	)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const upsertGlobalConfig = `-- name: UpsertGlobalConfig :one
INSERT INTO configurations_global(
	feature,
	description,
	secret,
	key,
	value)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5)
ON CONFLICT (
	feature,
	key)
	DO UPDATE SET
		value = EXCLUDED.value,
		description = EXCLUDED.description
	RETURNING
		id, feature, key, value, description, secret, created
`

type UpsertGlobalConfigParams struct {
	Feature     string
	Description *string
	Secret      bool
	Key         string
	Value       []byte
}

func (q *Queries) UpsertGlobalConfig(ctx context.Context, arg UpsertGlobalConfigParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, upsertGlobalConfig,
		arg.Feature,
		arg.Description,
		arg.Secret,
		arg.Key,
		arg.Value,
	)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}
