// Code generated by sqlc. DO NOT EDIT.
// source: configurations.sql

package featuresql

import (
	"context"

	"github.com/google/uuid"
)

const configForEnvironmentFilteredByKeys = `-- name: ConfigForEnvironmentFilteredByKeys :many
WITH "combined" AS (
	SELECT
		"id",
		"feature",
		"key",
		"value",
		NULL::UUID AS environment_id
	FROM
		ONLY configurations_global glob
	WHERE
		glob.feature = $1
		AND glob.key = ANY ($2::TEXT[])
	UNION
	SELECT
		"id",
		"feature",
		"key",
		"value",
		"environment_id"
	FROM
		ONLY configurations_environment env
	WHERE
		env.feature = $1
		AND environment_id = $3
		AND env.key = ANY ($2::TEXT[])
),
"filtered" AS (
	SELECT
		id, feature, key, value, environment_id,
		RANK() OVER (PARTITION BY "key" ORDER BY environment_id ASC,
			key ASC)
	FROM "combined"
)
SELECT
	id, feature, key, value, environment_id, rank
FROM
	filtered
WHERE
	RANK = 1
`

type ConfigForEnvironmentFilteredByKeysParams struct {
	Feature       string
	Includedkeys  []string
	EnvironmentID uuid.UUID
}

type ConfigForEnvironmentFilteredByKeysRow struct {
	ID            uuid.UUID
	Feature       string
	Key           string
	Value         []byte
	EnvironmentID *uuid.UUID
	Rank          int64
}

// orignal name: EnvConfigOnlyKnown
func (q *Queries) ConfigForEnvironmentFilteredByKeys(ctx context.Context, arg ConfigForEnvironmentFilteredByKeysParams) ([]ConfigForEnvironmentFilteredByKeysRow, error) {
	rows, err := q.db.Query(ctx, configForEnvironmentFilteredByKeys, arg.Feature, arg.Includedkeys, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigForEnvironmentFilteredByKeysRow{}
	for rows.Next() {
		var i ConfigForEnvironmentFilteredByKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.EnvironmentID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
