// Code generated by sqlc. DO NOT EDIT.
// source: configurations.sql

package featuresql

import (
	"context"

	"github.com/google/uuid"
)

const configEnvDelete = `-- name: ConfigEnvDelete :exec
DELETE FROM configurations_environment
WHERE id = $1
`

func (q *Queries) ConfigEnvDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, configEnvDelete, id)
	return err
}

const configEnvGetByID = `-- name: ConfigEnvGetByID :one
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	id = $1
`

func (q *Queries) ConfigEnvGetByID(ctx context.Context, id uuid.UUID) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, configEnvGetByID, id)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const configEnvGetByKey = `-- name: ConfigEnvGetByKey :one
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	environment_id = $1
	AND feature = $2
	AND key = $3
`

type ConfigEnvGetByKeyParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Key           string
}

func (q *Queries) ConfigEnvGetByKey(ctx context.Context, arg ConfigEnvGetByKeyParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, configEnvGetByKey, arg.EnvironmentID, arg.Feature, arg.Key)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const configEnvListByFeature = `-- name: ConfigEnvListByFeature :many
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	feature = $1
ORDER BY
	environment_id,
	key ASC
`

func (q *Queries) ConfigEnvListByFeature(ctx context.Context, feature string) ([]ConfigurationsEnvironment, error) {
	rows, err := q.db.Query(ctx, configEnvListByFeature, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsEnvironment{}
	for rows.Next() {
		var i ConfigurationsEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configEnvListByFeatureAndEnv = `-- name: ConfigEnvListByFeatureAndEnv :many
SELECT
	id, feature, key, value, description, secret, created, environment_id
FROM
	configurations_environment
WHERE
	feature = $1
	AND environment_id = $2
ORDER BY
	key ASC
`

type ConfigEnvListByFeatureAndEnvParams struct {
	Feature       string
	EnvironmentID uuid.UUID
}

func (q *Queries) ConfigEnvListByFeatureAndEnv(ctx context.Context, arg ConfigEnvListByFeatureAndEnvParams) ([]ConfigurationsEnvironment, error) {
	rows, err := q.db.Query(ctx, configEnvListByFeatureAndEnv, arg.Feature, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsEnvironment{}
	for rows.Next() {
		var i ConfigurationsEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
			&i.EnvironmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configEnvUpdate = `-- name: ConfigEnvUpdate :one
UPDATE
	configurations_environment
SET
	description = $1,
	value = $2
WHERE
	id = $3
RETURNING
	id, feature, key, value, description, secret, created, environment_id
`

type ConfigEnvUpdateParams struct {
	Description *string
	Value       []byte
	ID          uuid.UUID
}

func (q *Queries) ConfigEnvUpdate(ctx context.Context, arg ConfigEnvUpdateParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, configEnvUpdate, arg.Description, arg.Value, arg.ID)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const configEnvUpsert = `-- name: ConfigEnvUpsert :one
INSERT INTO configurations_environment(
	environment_id,
	feature,
	description,
	secret,
	key,
	value)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6)
ON CONFLICT (
	environment_id,
	feature,
	key)
	DO UPDATE SET
		value = EXCLUDED.value,
		description = EXCLUDED.description
	RETURNING
		id, feature, key, value, description, secret, created, environment_id
`

type ConfigEnvUpsertParams struct {
	EnvironmentID uuid.UUID
	Feature       string
	Description   *string
	Secret        bool
	Key           string
	Value         []byte
}

func (q *Queries) ConfigEnvUpsert(ctx context.Context, arg ConfigEnvUpsertParams) (ConfigurationsEnvironment, error) {
	row := q.db.QueryRow(ctx, configEnvUpsert,
		arg.EnvironmentID,
		arg.Feature,
		arg.Description,
		arg.Secret,
		arg.Key,
		arg.Value,
	)
	var i ConfigurationsEnvironment
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
		&i.EnvironmentID,
	)
	return i, err
}

const configGlobalDelete = `-- name: ConfigGlobalDelete :exec
DELETE FROM configurations_global
WHERE id = $1
`

func (q *Queries) ConfigGlobalDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, configGlobalDelete, id)
	return err
}

const configGlobalGetByID = `-- name: ConfigGlobalGetByID :one
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	id = $1
`

func (q *Queries) ConfigGlobalGetByID(ctx context.Context, id uuid.UUID) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, configGlobalGetByID, id)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const configGlobalGetByKey = `-- name: ConfigGlobalGetByKey :one
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	feature = $1
	AND key = $2
`

type ConfigGlobalGetByKeyParams struct {
	Feature string
	Key     string
}

func (q *Queries) ConfigGlobalGetByKey(ctx context.Context, arg ConfigGlobalGetByKeyParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, configGlobalGetByKey, arg.Feature, arg.Key)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const configGlobalListByFeature = `-- name: ConfigGlobalListByFeature :many
SELECT
	id, feature, key, value, description, secret, created
FROM
	configurations_global
WHERE
	feature = $1
ORDER BY
	key ASC
`

func (q *Queries) ConfigGlobalListByFeature(ctx context.Context, feature string) ([]ConfigurationsGlobal, error) {
	rows, err := q.db.Query(ctx, configGlobalListByFeature, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationsGlobal{}
	for rows.Next() {
		var i ConfigurationsGlobal
		if err := rows.Scan(
			&i.ID,
			&i.Feature,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.Secret,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const configGlobalUpdate = `-- name: ConfigGlobalUpdate :one
UPDATE
	configurations_global
SET
	description = $1,
	value = $2
WHERE
	id = $3
RETURNING
	id, feature, key, value, description, secret, created
`

type ConfigGlobalUpdateParams struct {
	Description *string
	Value       []byte
	ID          uuid.UUID
}

func (q *Queries) ConfigGlobalUpdate(ctx context.Context, arg ConfigGlobalUpdateParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, configGlobalUpdate, arg.Description, arg.Value, arg.ID)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}

const configGlobalUpsert = `-- name: ConfigGlobalUpsert :one
INSERT INTO configurations_global(
	feature,
	description,
	secret,
	key,
	value)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5)
ON CONFLICT (
	feature,
	key)
	DO UPDATE SET
		value = EXCLUDED.value,
		description = EXCLUDED.description
	RETURNING
		id, feature, key, value, description, secret, created
`

type ConfigGlobalUpsertParams struct {
	Feature     string
	Description *string
	Secret      bool
	Key         string
	Value       []byte
}

func (q *Queries) ConfigGlobalUpsert(ctx context.Context, arg ConfigGlobalUpsertParams) (ConfigurationsGlobal, error) {
	row := q.db.QueryRow(ctx, configGlobalUpsert,
		arg.Feature,
		arg.Description,
		arg.Secret,
		arg.Key,
		arg.Value,
	)
	var i ConfigurationsGlobal
	err := row.Scan(
		&i.ID,
		&i.Feature,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.Secret,
		&i.Created,
	)
	return i, err
}
