// Code generated by sqlc. DO NOT EDIT.
// source: disabled_features.sql

package featuresql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDisabledFeature = `-- name: DeleteDisabledFeature :exec
DELETE FROM disabled_features
WHERE environment_id = $1
	AND feature = $2
`

type DeleteDisabledFeatureParams struct {
	EnvironmentID uuid.UUID
	Feature       string
}

func (q *Queries) DeleteDisabledFeature(ctx context.Context, arg DeleteDisabledFeatureParams) error {
	_, err := q.db.Exec(ctx, deleteDisabledFeature, arg.EnvironmentID, arg.Feature)
	return err
}

const getDisabledFeature = `-- name: GetDisabledFeature :one
SELECT
	environment_id, feature, disabled_at
FROM
	disabled_features
WHERE
	environment_id = $1
	AND feature = $2
`

type GetDisabledFeatureParams struct {
	EnvironmentID uuid.UUID
	Feature       string
}

func (q *Queries) GetDisabledFeature(ctx context.Context, arg GetDisabledFeatureParams) (DisabledFeature, error) {
	row := q.db.QueryRow(ctx, getDisabledFeature, arg.EnvironmentID, arg.Feature)
	var i DisabledFeature
	err := row.Scan(&i.EnvironmentID, &i.Feature, &i.DisabledAt)
	return i, err
}

const listDisabledFeatureEnvironments = `-- name: ListDisabledFeatureEnvironments :many
SELECT
	environment_id,
	disabled_at
FROM
	disabled_features
WHERE
	feature = $1
ORDER BY
	environment_id
`

type ListDisabledFeatureEnvironmentsRow struct {
	EnvironmentID uuid.UUID
	DisabledAt    time.Time
}

func (q *Queries) ListDisabledFeatureEnvironments(ctx context.Context, feature string) ([]ListDisabledFeatureEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listDisabledFeatureEnvironments, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisabledFeatureEnvironmentsRow{}
	for rows.Next() {
		var i ListDisabledFeatureEnvironmentsRow
		if err := rows.Scan(&i.EnvironmentID, &i.DisabledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledFeaturesByEnvironment = `-- name: ListDisabledFeaturesByEnvironment :many
SELECT
	environment_id, feature, disabled_at
FROM
	disabled_features
WHERE
	environment_id = $1
ORDER BY
	feature
`

func (q *Queries) ListDisabledFeaturesByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]DisabledFeature, error) {
	rows, err := q.db.Query(ctx, listDisabledFeaturesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DisabledFeature{}
	for rows.Next() {
		var i DisabledFeature
		if err := rows.Scan(&i.EnvironmentID, &i.Feature, &i.DisabledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDisabledFeature = `-- name: SetDisabledFeature :exec
INSERT INTO disabled_features(
	environment_id,
	feature)
VALUES (
	$1,
	$2)
ON CONFLICT (
	environment_id,
	feature)
	DO NOTHING
`

type SetDisabledFeatureParams struct {
	EnvironmentID uuid.UUID
	Feature       string
}

func (q *Queries) SetDisabledFeature(ctx context.Context, arg SetDisabledFeatureParams) error {
	_, err := q.db.Exec(ctx, setDisabledFeature, arg.EnvironmentID, arg.Feature)
	return err
}
