// Code generated by sqlc. DO NOT EDIT.
// source: features.sql

package featuresql

import (
	"context"
)

const featureDataCreate = `-- name: FeatureDataCreate :exec
INSERT INTO feature_data(
	name,
	version,
	chart,
	description,
	source,
	kinds,
	dependencies,
	"values",
	default_values,
	timeout,
	tpl_details)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
(
		$6::TEXT[]) ::environment_kind[],
	$7,
	$8,
	$9,
	$10,
	$11)
`

type FeatureDataCreateParams struct {
	FeatureName   string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

func (q *Queries) FeatureDataCreate(ctx context.Context, arg FeatureDataCreateParams) error {
	_, err := q.db.Exec(ctx, featureDataCreate,
		arg.FeatureName,
		arg.Version,
		arg.Chart,
		arg.Description,
		arg.Source,
		arg.Kinds,
		arg.Dependencies,
		arg.Values,
		arg.DefaultValues,
		arg.Timeout,
		arg.TplDetails,
	)
	return err
}

const featureIndexRows = `-- name: FeatureIndexRows :many
SELECT DISTINCT ON (d.feature_name)
	fd.name,
	fd.description,
	fd.source
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.active = TRUE
	ORDER BY
		d.feature_name,
		d.created DESC
`

type FeatureIndexRowsRow struct {
	Name        string
	Description string
	Source      string
}

func (q *Queries) FeatureIndexRows(ctx context.Context) ([]FeatureIndexRowsRow, error) {
	rows, err := q.db.Query(ctx, featureIndexRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeatureIndexRowsRow{}
	for rows.Next() {
		var i FeatureIndexRowsRow
		if err := rows.Scan(&i.Name, &i.Description, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const featureNames = `-- name: FeatureNames :many
SELECT DISTINCT
	feature_name
FROM
	feature_assignments
WHERE
	active = TRUE
ORDER BY
	feature_name
`

func (q *Queries) FeatureNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, featureNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var feature_name string
		if err := rows.Scan(&feature_name); err != nil {
			return nil, err
		}
		items = append(items, feature_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestFeatureData = `-- name: LatestFeatureData :one
SELECT
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details
FROM
	feature_assignments d
	JOIN feature_data fd ON d.feature_name = fd.name
		AND d.version = fd.version
WHERE
	d.feature_name = $1
	AND d.active = TRUE
ORDER BY
	d.created DESC
LIMIT 1
`

type LatestFeatureDataRow struct {
	FeatureDatum FeatureDatum
}

func (q *Queries) LatestFeatureData(ctx context.Context, featureName string) (LatestFeatureDataRow, error) {
	row := q.db.QueryRow(ctx, latestFeatureData, featureName)
	var i LatestFeatureDataRow
	err := row.Scan(
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
	)
	return i, err
}
