// Code generated by sqlc. DO NOT EDIT.
// source: features.sql

package featuresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const featureByName = `-- name: FeatureByName :one
SELECT
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details,
	features.created,
	features.last_modified
FROM
	features
	JOIN feature_data fd ON features.name = fd.name
		AND features.version = fd.version
WHERE
	fd.name = $1
`

type FeatureByNameRow struct {
	FeatureDatum FeatureDatum
	Created      pgtype.Timestamptz
	LastModified pgtype.Timestamptz
}

func (q *Queries) FeatureByName(ctx context.Context, name string) (FeatureByNameRow, error) {
	row := q.db.QueryRow(ctx, featureByName, name)
	var i FeatureByNameRow
	err := row.Scan(
		&i.FeatureDatum.Name,
		&i.FeatureDatum.Version,
		&i.FeatureDatum.Chart,
		&i.FeatureDatum.Description,
		&i.FeatureDatum.Source,
		&i.FeatureDatum.Kinds,
		&i.FeatureDatum.Dependencies,
		&i.FeatureDatum.Values,
		&i.FeatureDatum.DefaultValues,
		&i.FeatureDatum.Timeout,
		&i.FeatureDatum.TplDetails,
		&i.Created,
		&i.LastModified,
	)
	return i, err
}

const featureDataCreate = `-- name: FeatureDataCreate :exec
INSERT INTO feature_data(
	name,
	version,
	chart,
	description,
	source,
	kinds,
	dependencies,
	"values",
	default_values,
	timeout,
	tpl_details)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
(
		$6::TEXT[]) ::environment_kind[],
	$7,
	$8,
	$9,
	$10,
	$11)
`

type FeatureDataCreateParams struct {
	FeatureName   string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []string
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

func (q *Queries) FeatureDataCreate(ctx context.Context, arg FeatureDataCreateParams) error {
	_, err := q.db.Exec(ctx, featureDataCreate,
		arg.FeatureName,
		arg.Version,
		arg.Chart,
		arg.Description,
		arg.Source,
		arg.Kinds,
		arg.Dependencies,
		arg.Values,
		arg.DefaultValues,
		arg.Timeout,
		arg.TplDetails,
	)
	return err
}

const featureVersionUpdate = `-- name: FeatureVersionUpdate :exec
INSERT INTO features(
	name,
	version)
VALUES (
	$1,
	$2)
ON CONFLICT (
	name)
	DO UPDATE SET
		version = EXCLUDED.version
`

type FeatureVersionUpdateParams struct {
	Name    string
	Version string
}

func (q *Queries) FeatureVersionUpdate(ctx context.Context, arg FeatureVersionUpdateParams) error {
	_, err := q.db.Exec(ctx, featureVersionUpdate, arg.Name, arg.Version)
	return err
}

const features = `-- name: Features :many
SELECT
	fd.name, fd.version, fd.chart, fd.description, fd.source, fd.kinds, fd.dependencies, fd.values, fd.default_values, fd.timeout, fd.tpl_details,
	features.created,
	features.last_modified
FROM
	features
	JOIN feature_data fd ON features.name = fd.name
		AND features.version = fd.version
	ORDER BY
		features.name
`

type FeaturesRow struct {
	FeatureDatum FeatureDatum
	Created      pgtype.Timestamptz
	LastModified pgtype.Timestamptz
}

func (q *Queries) Features(ctx context.Context) ([]FeaturesRow, error) {
	rows, err := q.db.Query(ctx, features)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturesRow{}
	for rows.Next() {
		var i FeaturesRow
		if err := rows.Scan(
			&i.FeatureDatum.Name,
			&i.FeatureDatum.Version,
			&i.FeatureDatum.Chart,
			&i.FeatureDatum.Description,
			&i.FeatureDatum.Source,
			&i.FeatureDatum.Kinds,
			&i.FeatureDatum.Dependencies,
			&i.FeatureDatum.Values,
			&i.FeatureDatum.DefaultValues,
			&i.FeatureDatum.Timeout,
			&i.FeatureDatum.TplDetails,
			&i.Created,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
