// Code generated by sqlc. DO NOT EDIT.

package featuresql

import (
	"time"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/database/types"
)

type ConfigurationsEnvironment struct {
	ID            uuid.UUID
	Feature       string
	Key           string
	Value         []byte
	Description   *string
	Secret        bool
	Created       time.Time
	EnvironmentID uuid.UUID
}

type ConfigurationsGlobal struct {
	ID          uuid.UUID
	Feature     string
	Key         string
	Value       []byte
	Description *string
	Secret      bool
	Created     time.Time
}

type DisabledFeature struct {
	EnvironmentID uuid.UUID
	Feature       string
	DisabledAt    time.Time
}

type FeatureDatum struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []types.EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
}

type Log struct {
	ID                int64
	DeployInstruction uuid.UUID
	Time              time.Time
	Message           string
	Kind              string
}
