// Code generated by sqlc. DO NOT EDIT.

package featuresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfigEnvDelete(ctx context.Context, id uuid.UUID) error
	ConfigEnvGetByID(ctx context.Context, id uuid.UUID) (ConfigurationsEnvironment, error)
	ConfigEnvGetByKey(ctx context.Context, arg ConfigEnvGetByKeyParams) (ConfigurationsEnvironment, error)
	ConfigEnvListAllByFeature(ctx context.Context, feature string) ([]ConfigurationsEnvironment, error)
	ConfigEnvListByFeature(ctx context.Context, arg ConfigEnvListByFeatureParams) ([]ConfigurationsEnvironment, error)
	ConfigEnvUpdate(ctx context.Context, arg ConfigEnvUpdateParams) (ConfigurationsEnvironment, error)
	ConfigEnvUpsert(ctx context.Context, arg ConfigEnvUpsertParams) (ConfigurationsEnvironment, error)
	ConfigGlobalDelete(ctx context.Context, id uuid.UUID) error
	ConfigGlobalGetByID(ctx context.Context, id uuid.UUID) (ConfigurationsGlobal, error)
	ConfigGlobalGetByKey(ctx context.Context, arg ConfigGlobalGetByKeyParams) (ConfigurationsGlobal, error)
	ConfigGlobalListByFeature(ctx context.Context, feature string) ([]ConfigurationsGlobal, error)
	ConfigGlobalUpdate(ctx context.Context, arg ConfigGlobalUpdateParams) (ConfigurationsGlobal, error)
	ConfigGlobalUpsert(ctx context.Context, arg ConfigGlobalUpsertParams) (ConfigurationsGlobal, error)
	DisabledFeatureDelete(ctx context.Context, arg DisabledFeatureDeleteParams) error
	DisabledFeatureEnvironments(ctx context.Context, feature string) ([]DisabledFeatureEnvironmentsRow, error)
	DisabledFeatureGet(ctx context.Context, arg DisabledFeatureGetParams) (DisabledFeature, error)
	DisabledFeatureSet(ctx context.Context, arg DisabledFeatureSetParams) error
	DisabledFeaturesByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]DisabledFeature, error)
	FeatureDataByVersion(ctx context.Context, arg FeatureDataByVersionParams) (FeatureDataByVersionRow, error)
	FeatureDataCreate(ctx context.Context, arg FeatureDataCreateParams) error
	FeatureIndexRows(ctx context.Context) ([]FeatureIndexRowsRow, error)
	FeatureNames(ctx context.Context) ([]string, error)
	FeatureVersionRows(ctx context.Context, featureName string) ([]FeatureVersionRowsRow, error)
	// Deploy state is derived from deploy_log. Per-environment current state comes
	// from the deploy_status view (latest row per environment x feature). Deploy
	// history (one entry per deploy) is grouped by diid in Go from ListDeployLog.
	GetLatestDeployInstruction(ctx context.Context, arg GetLatestDeployInstructionParams) (GetLatestDeployInstructionRow, error)
	GetLatestDeployedDeployInstruction(ctx context.Context, arg GetLatestDeployedDeployInstructionParams) (GetLatestDeployedDeployInstructionRow, error)
	LatestFeatureData(ctx context.Context, featureName string) (LatestFeatureDataRow, error)
	ListDeployLog(ctx context.Context, arg ListDeployLogParams) ([]ListDeployLogRow, error)
	ListLatestDeployInstructionsForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]ListLatestDeployInstructionsForEnvironmentRow, error)
	ListLatestDeployInstructionsForFeature(ctx context.Context, featureName string) ([]ListLatestDeployInstructionsForFeatureRow, error)
	ListLatestDeployedForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]ListLatestDeployedForEnvironmentRow, error)
	ListLatestDeployedForFeature(ctx context.Context, featureName string) ([]ListLatestDeployedForFeatureRow, error)
	// original name: MappingValuesForTenant
	ListMappingValuesForTenant(ctx context.Context, arg ListMappingValuesForTenantParams) ([]ListMappingValuesForTenantRow, error)
	ListSecretKeysForTenant(ctx context.Context, tenantid uuid.UUID) ([]ListSecretKeysForTenantRow, error)
}

var _ Querier = (*Queries)(nil)
