// Code generated by sqlc. DO NOT EDIT.

package deploymentsql

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nais/fasit/internal/environment"
)

type EnvironmentKind string

const (
	EnvironmentKindTenant     EnvironmentKind = "tenant"
	EnvironmentKindManagement EnvironmentKind = "management"
	EnvironmentKindOnprem     EnvironmentKind = "onprem"
	EnvironmentKindLegacy     EnvironmentKind = "legacy"
)

func (e *EnvironmentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnvironmentKind(s)
	case string:
		*e = EnvironmentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EnvironmentKind: %T", src)
	}
	return nil
}

type NullEnvironmentKind struct {
	EnvironmentKind EnvironmentKind
	Valid           bool // Valid is true if EnvironmentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironmentKind) Scan(value interface{}) error {
	if value == nil {
		ns.EnvironmentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnvironmentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironmentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnvironmentKind), nil
}

type DeployInstruction struct {
	ID             uuid.UUID
	EnvironmentID  uuid.UUID
	FeatureName    string
	FeatureVersion string
	Status         string
	Hash           string
	Created        pgtype.Timestamptz
	LastModified   pgtype.Timestamptz
	Values         []byte
	DeploymentID   *uuid.UUID
}

type Deployment struct {
	ID          uuid.UUID
	FeatureName string
	Version     string
	Target      environment.Labels
	Created     pgtype.Timestamptz
	GhRef       []byte
	Description *string
	Ci          bool
}

type DeploymentStatus struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	Status        string
	Message       string
	LastModified  pgtype.Timestamptz
	Created       pgtype.Timestamptz
}

type Environment struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Name              string
	Kind              EnvironmentKind
	Description       *string
	Created           pgtype.Timestamptz
	LastModified      pgtype.Timestamptz
	Ci                bool
	Reconcile         bool
	AutoUpgrade       bool
	UpgradeDelayDays  int32
	MaintenanceWindow []byte
	Labels            environment.Labels
}

type FeatureDatum struct {
	Name          string
	Version       string
	Chart         string
	Description   string
	Source        string
	Kinds         []EnvironmentKind
	Dependencies  []byte
	Values        []byte
	DefaultValues []byte
	Timeout       int64
	TplDetails    []byte
	Rename        []byte
}
