// Code generated by sqlc. DO NOT EDIT.

package deploymentsql

import (
	"context"

	"github.com/google/uuid"
	"github.com/nais/fasit/internal/environment"
)

type Querier interface {
	DeployInstructionsGetDeployedFeatures(ctx context.Context, arg DeployInstructionsGetDeployedFeaturesParams) ([]string, error)
	DeploymentCreate(ctx context.Context, arg DeploymentCreateParams) (Deployment, error)
	DeploymentDelete(ctx context.Context, id uuid.UUID) error
	DeploymentGet(ctx context.Context, id uuid.UUID) (DeploymentGetRow, error)
	DeploymentStatusCreateOrUpdate(ctx context.Context, arg DeploymentStatusCreateOrUpdateParams) error
	DeploymentStatusGet(ctx context.Context, deploymentID uuid.UUID) ([]DeploymentStatus, error)
	DeploymentsForEnvironmentToReconcile(ctx context.Context, environmentID uuid.UUID) ([]DeploymentsForEnvironmentToReconcileRow, error)
	DeploymentsGet(ctx context.Context) ([]DeploymentsGetRow, error)
	DeploymentsGetByFeature(ctx context.Context, featureName string) ([]DeploymentsGetByFeatureRow, error)
	FeatureEnabled(ctx context.Context, arg FeatureEnabledParams) (bool, error)
	GetCIEnvironmentsForTarget(ctx context.Context, target environment.Labels) ([]GetCIEnvironmentsForTargetRow, error)
	InsertEnvironmentFeature(ctx context.Context, arg InsertEnvironmentFeatureParams) error
	LatestStatusForDeploymentInEnvironment(ctx context.Context, arg LatestStatusForDeploymentInEnvironmentParams) (string, error)
}

var _ Querier = (*Queries)(nil)
