name: Build and deploy
on:
  push:
    paths-ignore:
      - "charts/**"
      - ".github/workflows/*_chart.yaml"

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images

jobs:
  prereqs:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
  meta_build_and_push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: naisd
          - name: fasit
          - name: fasit-frontend
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
      - name: Docker meta ${{ matrix.name }}
        id: metadata-${{ matrix.name }}
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.name }}
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and push naisd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_${{ matrix.name }}
          push: true
          tags: ${{ steps.${{ matrix.name }}.outputs.tags }}
          labels: ${{ steps.${{ matrix.name }}.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_helm_chart:
    runs-on: [ 'fasit' ]
    steps:
      - name: Deploy fasit-frontend
        uses: ./.github/actions/helm_install
        with:
          name: fasit-frontend
          chart: ${{ env.REGISTRY }}/fasit-frontend
          version: 0.1.0
          imageTag: ${{ steps.metadata.fasit-frontend.outputs.tags }}