name: Build and deploy fasit
on:
  push:
    paths-ignore:
      - "charts/**"
      - ".github/workflows/*_chart.yaml"
      - ".github/workflows/build_and_push_image_fasit-frontend.yaml"
      - "frontend/**"
      - "features/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILDER_IMG: "cgr.dev/chainguard/go:1.20"
  RUNNER_IMG: "cgr.dev/chainguard/static"
  BASEIMG_IDENTITY: "https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main"
  BASEIMG_ISSUER: "https://token.actions.githubusercontent.com"

jobs:
  tests:
    runs-on: ubuntu-latest-4-cores
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.2"
      - run: go test -cover -tags integration_test ./...
      - name: Vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

  build_and_push_backend:
    if: github.ref == 'refs/heads/main'
    needs: [tests]
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - fasit
          - naisd
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0'
      - name: Verify builder image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.BUILDER_IMG }}
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - uses: nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          dockerfile: Dockerfile_${{ matrix.image }}
          name: ${{ matrix.image }}
          google_service_account: gh-fasit
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: ${{ github.actor != 'dependabot[bot]' }}

  deploy_fasit:
    if: github.ref == 'refs/heads/main'
    runs-on: ["fasit-deploy"]
    needs: ["build_and_push_backend"]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v3.5.0
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Install prereqs
        uses: ./.github/actions/helm_install
      - name: Get credentials
        shell: bash
        run: |
          gcloud container clusters get-credentials nais-io --project nais-io --region europe-north1
      - name: deploy fasit
        env:
          VERSION: ${{ needs.build_and_push_backend.outputs.version }}
        shell: bash
        run: |
          helm upgrade fasit-backend oci://europe-north1-docker.pkg.dev/nais-io/nais/fasit --install --wait --version 0.3.1 --set image.tag=${VERSION} --namespace nais-system --reuse-values
