name: Build and deploy fasit-frontend
on:
  push:
    paths:
      - ".github/workflows/build_and_push_image_fasit-frontend.yaml"
      - ".github/actions/helm_install/**"
      - "frontend/**"
      - "Dockerfile_fasit-frontend"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images

jobs:
  build_and_test_fasit-frontend:
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v3.2.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta fasit-frontend
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/fasit-frontend
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and test fasit-frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_fasit-frontend
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha

  build_and_push_fasit-frontend:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v3.2.0
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Docker meta fasit-frontend
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/fasit-frontend
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and push fasit-frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_fasit-frontend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_fasit-frontend:
    if: github.ref == 'refs/heads/main'
    runs-on: ["fasit"]
    needs: ["build_and_push_fasit-frontend"]
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v3.2.0
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1.0.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Install prereqs
        uses: ./.github/actions/helm_install
      - name: Get credentials
        shell: bash
        run: |
          gcloud container clusters get-credentials nais-io --project nais-io --region europe-north1
      - name: deploy fasit-frontend
        shell: bash
        run: |
          helm upgrade fasit-frontend oci://europe-north1-docker.pkg.dev/nais-io/nais/fasit-frontend --install --wait --version 0.2.0 --set image.tag="sha-${GITHUB_SHA::7}" --namespace nais-system
