name: Build and deploy
on:
  push:
    paths-ignore:
      - "charts/**"
      - ".github/workflows/*_chart.yaml"

env:
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images

jobs:
  prereqs:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fasit
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.6.0"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Docker meta naisd
        id: metadata_naisd
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/naisd
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and push naisd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_naisd
          push: true
          tags: ${{ steps.metadata_naisd.outputs.tags }}
          labels: ${{ steps.metadata_naisd.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta fasit
        id: metadata_fasit
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/fasit
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build and push fasit
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_fasit
          push: true
          tags: ${{ steps.metadata_fasit.outputs.tags }}
          labels: ${{ steps.metadata_fasit.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker meta fasit-frontend
        id: metadata_fasit_frontend
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/fasit-frontend
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha
      - name: Build and push fasit-frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_fasit-frontend
          push: true
          tags: ${{ steps.metadata_fasit_frontend.outputs.tags }}
          labels: ${{ steps.metadata_fasit_frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy_helm_chart:
    runs-on: [ 'fasit' ]
    steps:
      - name: Deploy fasit-frontend
        uses: ./.github/actions/helm_install
        with:
          name: fasit-frontend
          chart: ${{ env.REGISTRY }}/fasit-frontend
          version: 0.1.0
          imageTag: ${{ steps.metadata_fasit_frontend.outputs.version }}