name: Build and push fasit chart
on:
  push:
    branches:
      - main
    paths:
      - "charts/fasit/**"
      - ".github/workflows/fasit_chart.yaml"

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"

    name: Build and push fasit chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d" # ratchet:google-github-actions/auth@v2.1.2
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@f0990588f1e5b5af6827153b93673613abdc6ec7" # ratchet:google-github-actions/setup-gcloud@v1
      - name: "Log in to Google Artifact Registry"
        run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://europe-north1-docker.pkg.dev
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # ratchet:azure/setup-helm@v4
        name: "Setup Helm"
        with:
          version: "3.9.3"

      - name: Build Chart
        run: |-
          helm package charts/fasit

      - name: Push Chart
        run: |-
          helm push fasit*.tgz oci://europe-north1-docker.pkg.dev/nais-io/nais
