name: Push features to GCS
on:
  push:
    branches:
      - main
    paths:
      - "schema/jsonschema/feature.json"
      - ".github/workflows/push_jsonschema.yaml"

env:
  BUCKET: "fasit-jsonschema"

jobs:
  upload_jsonschema:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@5a50e581162a13f4baa8916d01180d2acbc04363" # ratchet:google-github-actions/auth@v2.1.0
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-fasit@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200" # ratchet:google-github-actions/setup-gcloud@v1
      - name: Sync jsonschema to GCS
        run: |-
          gsutil cp schema/jsonschema/feature.json gs://${{ env.BUCKET }}
