apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "fasit-frontend.labels" . | nindent 4}}
  name: {{ include "fasit-frontend.fullname" . }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    {{ include "fasit-frontend.selectorLabels" . | nindent 4}}
  sessionAffinity: None
  type: ClusterIP
