apiVersion: v1
kind: Service
metadata:
  labels:
    team: nais
  name: {{ include "fasit-frontend.fullname" . }}
  namespace: nais-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "fasit-frontend.fullname"}}
  sessionAffinity: None
  type: ClusterIP
